### ISSUE TITLE
Can not See Cards after Deploy

### ISSUE THREAD

**Issue by BarteusX** [vlocityinc/vlocity_build#108]
Hello, I started using Vlocity Summer Release and with Vlocity Build 1.5.5. and the same with 1.7.6. After deploy I can't see cards, I have to go to cards and manually deactivate layout after that I have to Deactivate and Activate all cards and Activate Layout. It fix problem but after next deploy is the same.

I need urgent help.

**Comment by rutlabaga** [comment]
Sorry for the delay, but you will have to file a support@vlocity.com case to look into this.
