### ISSUE TITLE
Deployment creating all Version 1 and more than 1 element activated in same type/subtype

### ISSUE THREAD

**Issue by inglazarev** [vlocityinc/vlocity_build#113]
After a migration from one environment to another we are facing version 1 issues.
The elements, OS and IPs are being created all with version 1, if you create a new version from it, it is always creating version one, and the funny part is that we found that there are 2 activated elements in the same type/subtype

Screenshot:
https://photos.app.goo.gl/DMjtppcwJXTtSUrJ6

**Comment by rutlabaga** [comment]
This is caused by the triggers being off. Please make sure they are enabled during deploy.
