### ISSUE TITLE
unable to control colored output via noColor flag

### ISSUE THREAD

**Issue by murtazamoin** [vlocityinc/vlocity_build#114]

**Comment by murtazamoin** [comment]
In executing vlocity commands using command line scripts throws color escape sequences in console. Attempting to disable color in log is not working. I have used -noColor true but it is not performing as desired.

**Comment by rutlabaga** [comment]
Sorry, I put the wrong key in the README. It is actually `--simpleLogging`

**Comment by murtazamoin** [comment]
vlocity -simpleLogging true -propertyfile test.properties -job releases\vlocity-181109\saskproddep.yaml cleanOrgData

I tried running above command and still it produces colored output. What wrong I am doing here?

**Comment by rutlabaga** [comment]
What version are you using?

**Comment by murtazamoin** [comment]
Vlocity Build v1.6.3

**Comment by rutlabaga** [comment]
You should update to the latest version. That feature did not exist in 1.6.3.

**Comment by murtazamoin** [comment]
Thanks for the update
