### ISSUE TITLE
Having issues with installing vlocity build

### ISSUE THREAD

**Issue by LamereMichael** [vlocityinc/vlocity_build#117]
I use to have an older version that I got by cloning the repo, I am now trying to get it installed on a new laptop and having some issues. I tried to unlink the cloned repo and reinstall it by using the npm command. 

below I have attached screen shots of the install and folder location

![image](https://user-images.githubusercontent.com/5972241/48576145-5bc53c00-e8d9-11e8-8796-33f15e2cdbf7.png)

![image](https://user-images.githubusercontent.com/5972241/48576169-6bdd1b80-e8d9-11e8-849a-833dd4d2206b.png)

**Comment by rutlabaga** [comment]
Best to use `npm install vlocity -g`
