### ISSUE TITLE
v1.7.5: Issue in importing Entity Filter

### ISSUE THREAD

**Issue by edogaldo** [vlocityinc/vlocity_build#118]
Hello, trying to import some entity filters I get following error message:
`EntityFilter/974e5581-2073-34d0-0779-7e4c96c13cf1 -- DataPack >> Promo_41489_BloccataDa -- Error Message -- No match found for %vlocity_namespace%__EntityFilterConditionArgument__c.%vlocity_namespace%__FilterConditionId__c - uniqueId=%vlocity_namespace%__EntityFilterCondition__c/AutoGenerated (%vlocity_namespace%)`

Could you please help?

Thanks in advance and best regards, E.

**Comment by rutlabaga** [comment]
This should be fixed in v.1.7.9. Requires re-exporting your EntityFilter. The EntityFilter conditions will show changes when they are exported from different orgs, so there is an open issue with that.
