### ISSUE TITLE
Cannot export Template Document Contents

### ISSUE THREAD

**Issue by thvd** [vlocityinc/vlocity_build#122]
When we export a Template Document the `vlocity_cmt__TemplateDocument__c` is there, but the `ContentVersion` (Thats including the docx file) is missing. I think we should modify the `lib/datapacksexpanddefinition.yaml` file, but not sure how to approach this.

**Comment by rutlabaga** [comment]
Which version of the Vlocity Package are you on?

**Comment by thvd** [comment]
I am on version 1.7.8

**Comment by rutlabaga** [comment]
Which version of the Vlocity Managed Package in Salesforce?

**Comment by thvd** [comment]
The managed package is 900.163

**Comment by rutlabaga** [comment]
The mechanism for this is the mappings. But Content Version is not supported in that version of the Managed Package as a DataPack.

**Comment by thvd** [comment]
@rutlabaga thanks for the response. In which version it is?

**Comment by rutlabaga** [comment]
Actually I think I am wrong. Do you have a Custum Metadata Object for VlocityDataPackConfiguration with Type ContentVersion? I may just need to fix the mapping for this.

**Comment by rutlabaga** [comment]
You were right. I updated the settings. The issue was the ContentVersion does not have a Name field, which was causing the issue. Fixed in v1.7.9
