### ISSUE TITLE
manifestOnly: false does nothing

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#128]
When I have manifest and queries in one job file, only components listed in manifest are exported. 
manifestOnly setting seems not to have any influence on what is actually exported.

I am testing Vlocity Build 1.7.8.

**Comment by rutlabaga** [comment]
Manifest and Queries cannot both be in file. Best to use the following workflow:
https://drive.google.com/open?id=1FRKBrPqtfB2I_U57lJToHvWcR3Tld74s
