### ISSUE TITLE
Custom data validation step

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#129]
I am trying to add our custom step for data validation with executing pre apex job:
preJobApex:
  Export: ../CI/scripts/ValidateDates.cls

Problem is I cannot pass information what is wrong from apex to Vlocity Build. I tried two approaches:
`throw new Exception('Wrong number of Price List Elements for ' + product.ProductCode);`
or
`System.assertEquals(2, plesForProduct.size(), 'Wrong number of Price List Elements for ' + product.ProductCode);
`
Both of them give the same poor result in the command line:
[exec] {
     [exec]     "action": "Export",
     [exec]     "message": "",
     [exec]     "records": [
     [exec]     ],
     [exec]     "status": "error"
     [exec] }
     [exec] Result: 1

What is the best practice to accomplish this?

**Comment by rutlabaga** [comment]
This doesn't really work like this for Apex. It may be easier to do with JavaScript.
