### ISSUE TITLE
Unhandled promise rejection when trying to deploy

### ISSUE THREAD

**Issue by IIvanov8888** [vlocityinc/vlocity_build#13]
Hi , 
I am experiencing the following issues when trying to deploy OmniScript and Layouts => 

**(node:27060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ERROR_HTTP_414: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>**

**Comment by rutlabaga** [comment]
I believe this is due to having a preJobApex which is sending too much data. It is best to use preStepApex or to delete the //BaseUtilities.cls from your preJobApex file if you have a lot of items. 

If this is not the issue, can you please paste the job file you are using.

**Comment by IIvanov8888** [comment]
Hi, 
Thank you , I actually managed to do it with this approach **preStepApex**, closing the issue
