### ISSUE TITLE
refreshVlocityBase errors on DPAAssets and DPAImages

### ISSUE THREAD

**Issue by DripLeBuk** [vlocityinc/vlocity_build#143]
Running vlocity --nojob packUpdateSettings refreshVlocityBase (version 1.7.11) on a new Dev type org refreshed from Production, without a prior cleanOrgData or refreshProject, generates the following errors:

```
  Beginning Deployment >> DPAAssets
  Error Processing >> DPAAssets SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\david.kubel\AppData\Roaming\npm\node_modules\vlocity1711\lib\datapacksjob.js:1277:56
    at C:\Users\david.kubel\AppData\Roaming\npm\node_modules\vlocity1711\node_modules\salesforce-alm\node_modules\jsforce\lib\promise.js:72:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
  Beginning Deployment >> DPAImages
  Error Processing >> DPAImages SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\david.kubel\AppData\Roaming\npm\node_modules\vlocity1711\lib\datapacksjob.js:1277:56
    at C:\Users\david.kubel\AppData\Roaming\npm\node_modules\vlocity1711\node_modules\salesforce-alm\node_modules\jsforce\lib\promise.js:72:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
  Formatting Response
RefreshVlocityBase success:
10 Refreshed

```

Production has Vlocity CMT 900.107 (Summer'17) installed. 

[Start201901081706 17711_template2_packUpdateSettings_refreshVlocityBase.log](https://github.com/vlocityinc/vlocity_build/files/2737786/Start201901081706.17711_template2_packUpdateSettings_refreshVlocityBase.log)

**Comment by rutlabaga** [comment]
This is an oversight on the tools part where it is accidentally pulling in some files it should not. I have just now fixed this in v1.8.0 which is just now released.

**Comment by DripLeBuk** [comment]
Query:  The README.md is unclear about the command sequence that should be followed immediately after completing an SF refresh on a Dev or DevPro type org.  Which sequence?

Option A)

  1.  –nojob packUpdateSettings refreshVlocityBase
  2.  -job xxx.yaml cleanOrgData
  3.  -job xxx.yaml refreshProject
  4.  -job xxx.yaml packUpdateSettings
  5.  -job xxx.yaml packDeploy

Option B)

  1.  -job xxx.yaml cleanOrgData
  2.  -job xxx.yaml refreshProject
  3.  -job xxx.yaml packUpdateSettings refreshVlocityBase
  4.  -job xxx.yaml packDeploy

Option C)

  1.  –nojob refreshVlocityBase
  2.  -job xxx.yaml cleanOrgData
  3.  -job xxx.yaml refreshProject
  4.  -job xxx.yaml packUpdateSettings
  5.  -job xxx.yaml packDeploy

Option D)

  1.  -job xxx.yaml cleanOrgData
  2.  -job xxx.yaml refreshProject
  3.  --nojob packUpdateSettings refreshVlocityBase
  4.  -job xxx.yaml packUpdateSettings
  5.  -job xxx.yaml packDeploy

Or what?

Regards,

__________________________________________________________
David Kubel
Business Analyst | Salesforce | Application Services UK
Planned Absences: February 11th, 12th & 20th

Capgemini UK | North West England
Mob.: +44 (0) 7717 726438
www.capgemini.com<http://www.capgemini.com/>

[https://visualidentity.capgemini.com/capgemini.png]                                                           A 2018 World’s Most Ethical Companies® Honouree<http://www.worldsmostethicalcompanies.com/honorees/>
____________________________________________________________________
Connect with Capgemini:
[cid:image002.png@01D4A7FF.F2D6A7C0]<https://www.capgemini.com/insights-and-resources/blogs>[cid:image003.png@01D4A7FF.F2D6A7C0]<https://www.twitter.com/capgemini> [cid:image004.png@01D4A7FF.F2D6A7C0] <https://www.facebook.com/capgemini>  [cid:image005.png@01D4A7FF.F2D6A7C0] <https://www.linkedin.com/company/capgemini>  [cid:image006.png@01D4A7FF.F2D6A7C0] <https://www.youtube.com/capgeminimedia>  [cid:image007.png@01D4A7FF.F2D6A7C0] <https://www.slideshare.net/capgemini>  [cid:image008.png@01D4A7FF.F2D6A7C0] <https://plus.google.com/+CapgeminiGlobal>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by DripLeBuk** [comment]
So when going through the Org to Org Migration process for a given target for the very first time, the sequence would be:

# Target Org (first-time only for a new Dev/DevPRO)

vlocity -propertyfile build_target.properties --nojob packUpdateSettings installVlocityInitial
vlocity -propertyfile build_target.properties -job EPC.yaml packDeploy
vlocity -propertyfile build_target.properties -job EPC.yaml packRetry # If any errors

and subsequent migrations would be:

# Target Org
vlocity -propertyfile build_target.properties -job EPC.yaml cleanOrgData
vlocity -propertyfile build_target.properties -job EPC.yaml refreshProject
vlocity -propertyfile build_target.properties -job EPC.yaml packUpdateSettings
vlocity -propertyfile build_target.properties -job EPC.yaml packDeploy
vlocity -propertyfile build_target.properties -job EPC.yaml packRetry # If any errors


Regards,

__________________________________________________________
David Kubel
Business Analyst | Salesforce | Application Services UK
Planned Absences: February 11th, 12th & 20th

Capgemini UK | North West England
Mob.: +44 (0) 7717 726438
www.capgemini.com<http://www.capgemini.com/>

[https://visualidentity.capgemini.com/capgemini.png]                                                           A 2018 World’s Most Ethical Companies® Honouree<http://www.worldsmostethicalcompanies.com/honorees/>
____________________________________________________________________
Connect with Capgemini:
[cid:image016.png@01D4A8C9.9ABB0E30]<https://www.capgemini.com/insights-and-resources/blogs> [cid:image017.png@01D4A8C9.9ABB0E30] <https://www.twitter.com/capgemini>  [cid:image018.png@01D4A8C9.9ABB0E30] <https://www.facebook.com/capgemini>  [cid:image019.png@01D4A8C9.9ABB0E30] <https://www.linkedin.com/company/capgemini>  [cid:image020.png@01D4A8C9.9ABB0E30] <https://www.youtube.com/capgeminimedia>  [cid:image021.png@01D4A8C9.9ABB0E30] <https://www.slideshare.net/capgemini>  [cid:image022.png@01D4A8C9.9ABB0E30] <https://plus.google.com/+CapgeminiGlobal>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.
