### ISSUE TITLE
installVlocityInitial errors on DPAAssets and DPAImages

### ISSUE THREAD

**Issue by DripLeBuk** [vlocityinc/vlocity_build#147]
Running vlocity --nojob packUpdateSettings installVlocityInitial on a new Dev type org refreshed from Production, without a prior cleanOrgData or refreshProject, generates the following errors:

`  Beginning Deployment >> DPAAssets`
`  Error >> SyntaxError: Unexpected token P in JSON at position 0`
`    at JSON.parse (<anonymous>)`
`    at module.exports.DataPacksJob.installFromStaticResourceQuery (C:\Users\david.kubel\AppData\Roaming\npm\node_modules\vlocity181\lib\datapacksjob.js:1431:67)`
`    at process.internalTickCallback (internal/process/next_tick.js:77:7)`
`  Beginning Deployment >> DPAImages`
`  Error >> SyntaxError: Unexpected token P in JSON at position 0`
`    at JSON.parse (<anonymous>)`
`    at module.exports.DataPacksJob.installFromStaticResourceQuery (C:\Users\david.kubel\AppData\Roaming\npm\node_modules\vlocity181\lib\datapacksjob.js:1431:67)`
 `   at process.internalTickCallback (internal/process/next_tick.js:77:7)`
`  Formatting Response >> InstallVlocityInitial`
`  Job Complete >> InstallVlocityInitial`
`InstallVlocityInitial success:`
`10 Refreshed`

[Start201901141451 181_template3_packUpdateSettings_installVlocityInitial.log](https://github.com/vlocityinc/vlocity_build/files/2755883/Start201901141451.181_template3_packUpdateSettings_installVlocityInitial.log)

Production has Vlocity CMT 900.107 (Summer'17) installed. I'm using Vlocity Built Tool v1.8.1 with node.js v11.6.

Also please confirm that when going through the Org to Org Migration process for the very first time for a given target that is not a Fully-Copy, Partial-Copy, or Clone, that the sequence should be:

# Target Org (first-time only for a new Dev/DevPRO)

vlocity -propertyfile build_target.properties --nojob packUpdateSettings installVlocityInitial
vlocity -propertyfile build_target.properties -job EPC.yaml packDeploy
vlocity -propertyfile build_target.properties -job EPC.yaml packRetry # If any errors

and subsequent migrations would be:

# Target Org
vlocity -propertyfile build_target.properties -job EPC.yaml cleanOrgData
vlocity -propertyfile build_target.properties -job EPC.yaml refreshProject
vlocity -propertyfile build_target.properties -job EPC.yaml packUpdateSettings
vlocity -propertyfile build_target.properties -job EPC.yaml packDeploy
vlocity -propertyfile build_target.properties -job EPC.yaml packRetry # If any errors

**Comment by rutlabaga** [comment]
Hi,

These DPAAssets and DPAImages are not part of the Vlocity Package, they just happen to follow the same naming convention as our default DataPacks. There is no good way to filter these out, so you can just ignore. It should not be causing issues.
