### ISSUE TITLE
 CreateProcess error=193, %1 is not a valid Win32 application while using ant command

### ISSUE THREAD

**Issue by nuhas** [vlocityinc/vlocity_build#15]
When I try to use the command 

ant packExport -buildfile c:/Users/Documents/vlocity_build/build.xml -propertyfile c:/Users/Desktop/deployment-toolkit/temp/Item-02755_retrieve.properties
 
I am getting an error as 
c:\Users\Documents\vlocity_build\build.xml:98: The following error occurred while executing this line:
c:\Users\Documents\vlocity_build\build.xml:109: c:\Users\Documents\vlocity_build\build.xml:114: Execute failed: java.io.IOException: Cannot run program "c:\Users\Documents\vlocity_build\bin\run-grunt" (in directory "c:\Users\Documents\vlocity_build"): CreateProcess error=193, %1 is not a valid Win32 application

Can I anyone have any thoughts?

**Comment by IIvanov8888** [comment]
I recommend that you use **Grunt** for deploying

**Comment by rutlabaga** [comment]
I agree with comment above. Please use grunt command instead of ant. If there is still an issue, I will look into it further.
