### ISSUE TITLE
Multiple Imported Records will incorrecty create the same Saleforce Record. 

### ISSUE THREAD

**Issue by padlakha** [vlocityinc/vlocity_build#154]
getting error while deploying in target Org :-

vlocity -propertyfile build_target.properties -job EPC.yaml cleanOrgData --> success
vlocity -propertyfile build_target.properties -job EPC.yaml refreshProject --> success
vlocity -propertyfile build_target.properties -job EPC.yaml packUpdateSettings --> success
vlocity -propertyfile build_target.properties -job EPC.yaml packDeploy --> failure (facing below errors) 
- 'Product2/4e5828c2-4832-10c8-c343-88934cc2cb1c -- DataPack >> Amount Discount Product -- Error Message -- Incorrect Import Data. Multiple Imported Records will incorrecty create the same Saleforce Record. %vlocity_namespace%__AttributeAssignment__c: TempAA-ATT_INS_PRICE'
- 'Product2/a1dd8cf9-5617-763f-0d65-b8f671bbc848 -- DataPack >> One Drive -- Error Message -- Incorrect Import Data. Multiple Imported Records will incorrecty create the same Saleforce Record. %vlocity_namespace%__AttributeAssignment__c: TempAA-ATT_RT_CMTP Override'

vlocity -propertyfile build_target.properties -job EPC.yaml packRetry # If any errors

Tried to delete records from attribute assignment using below query:

SELECT Id, Name, vlocity_cmt__ObjectType__c, vlocity_cmt__ObjectId__c FROM vlocity_cmt__AttributeAssignment__c WHERE Name = 'TempAA-ATT_INS_PRICE'

It didn't help and still, after deleting records we are getting the same error.

**Comment by rutlabaga** [comment]
This is related to missing Matching Key for AttributeAssignment with Matching Key Fields = %vlocity_namespace%__GlobalKey__c
