### ISSUE TITLE
Unable to deploy VlocityUITemplate with @import

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#16]
Warning: DataPacks Job Failed - Deploy - Item-01982 - Error: SASS compilation failed, see error message for details: Error

[exec]  SASS compilation failed, see error message for details: Error: 
     [exec]         on line 2 of /stdin
     [exec] >> @import "variables";
     [exec]    --------^
     [exec]  >>  
     [exec] 
     [exec]  Failed to compile SCSS for >>  /Users/stepan/Workspace/bin/deployUtils/config/deploymentsVlocity/Item-01982/vlocity//VlocityUITemplate/Test-card--pradeep/Test-card--pradeep.scss

**Comment by rutlabaga** [comment]
For this you need to also export the variables VlocityUITemplate. Otherwise you should set the compileOnBuild: false if you don't want to have Sass compilation also run offline.

**Comment by Stepan007** [comment]
Hi Adam, thank you for your response. I had those variables exported too. I think the issue was that the variables didn't exist on the environment and they were imported in wrong order so that I had to deploy variables first and then the rest of the package. I can try it again and play around a little bit with the configuration when I have time. I will let you know.

**Comment by rutlabaga** [comment]
The @import variables file must exist in a VlocityUITemplate folder in the currently deploying directory. The compile happens in the deploy scripts, not in Salesforce, so it is important that you are exporting and deploying everything together when using Sass. It is a TODO to better surface dependencies on @import files and also export them during an export of a Template that relies on them.

**Comment by Kleytman** [comment]
> 
> 
> The @import variables file must exist in a VlocityUITemplate folder in the currently deploying directory. The compile happens in the deploy scripts, not in Salesforce, so it is important that you are exporting and deploying everything together when using Sass. It is a TODO to better surface dependencies on @import files and also export them during an export of a Template that relies on them.

Hi Rutlabaga, how do I exactly export this @import variable files?

**Comment by rutlabaga** [comment]
Generally you can just do:

`packExport` -key VlocityUITemplate/TemplateName`

As long as it is Active it will get exported by Name

**Comment by Kleytman** [comment]
I ran that command and it does not work either, I get the same error, I check the folder where the files are getting exported VlocityUITemplate\campaign-detail and there are 4 files, none of them contain those variables, in the sass field of the vlocity template are 2 imports, 
@import "campaign-variables";
@import "campaign-mixins";

so I get one error:
Deploy error:
SASS Compilation Error VlocityUITemplate/campaign-detail Failed to compile SCSS: D:\datapacks_PME\VlocityUITemplate\campaign-detail\campaign-detail.sc
        on line 1 of /stdin
>> @import "campaign-variables";
   --------^

**Comment by rutlabaga** [comment]
Do you have `VlocityUITemplate/campaign-variables` and `VlocityUITemplate/campaign-mixins` folders in your project?

**Comment by Kleytman** [comment]
Those folder you mention dont get exported, do you mean those variables exists as other templates? So I must include them in the export?

**Comment by rutlabaga** [comment]
Yes, they must be separately exported with:

`packExport -key VlocityUITemplate/campaign-variables`

`packExport -key VlocityUITemplate/campaign-mixins`

Unfortunately the tool does not resolve these dependencies until compile time right now as it is only referenced as part of the actual SASS file and not as a list of metadata in the object.

**Comment by Kleytman** [comment]
Finally I got it, thanks a lot, as you mentioned, after I exported the other templates campaign-variables and campaign-mixins I got those other folder and the deploy process was successful, the real problem was I didn't knew those variables represented another cards.
