### ISSUE TITLE
Vlocity Build Tool issue during migration from Org to Org VERSION 103 in TELECOM ARGENTINA

### ISSUE THREAD

**Issue by MarianaSanchezIBM** [vlocityinc/vlocity_build#164]
We are creating a Datapack for migration of the Vlocity EPC catalog from an Origin development Org (EPC02Org ID = 00Dq0000000DLQT) to a Target Org (Merge02). Both are Orgs with the v103.1 functionality.  When we import the data pack into the Target Org we find some errors, where the most important one is the following:  Product2/1752456c-471e-15db-3acb-0ee81257b257 -- DataPack >> Xperia XA1 - Negro -- Error Message -- Post Process Failed - Message: Update failed. First exception on row 0 with id 01tc0000005JSpyAAG; first error: STRING_TOO_LONG, JSONAttribute: data value too large: {"FAN_ATTCAT_000042":[{"$$AttributeDefinitionStart$$":null,"objectid__c":"01tc0000005JSpyAAG","attributeid__c":"a0Jc0000008Mr5gEAC","attributecategoryid__c":"a0Ic000000HHYRYEA5","categorycode__c":"FAN_ATTCAT_000042","categoryname__c":"Integracion","attributeuniquecode__c":"FAN_ATT_000084","attributeconfigurable__c":true,"attributedisplaysequence__c":"1","attributefilterable__c":true,"attributecloneable__c":true,"isactive__c":true,"attributedisplayname__c":"Charge Code","displaysequence__c":"31","categorydisplaysequence__c":31,"customconfiguitemplate__c":null,"formatmask__c":null,"hasrule__c":false,"isconfigurable__c":false,"ishidden__c":false,"valueinnumber__c":null,"objecttype__c":"Product2","querycode__c":null,"isreadonly__c":false,"isquerydriven__c":false,"querylabel__c":null,"id":"a0G2a000004VVzNEAW","isrequired__c":false,"rulemessage__c":null,"uidisplaytype__c":"Dropdown","value__c":"C_OT_MB_EQUIPMENT_PHONES","valuedatatype__c":"Picklist","valuedescription__c":null,"isnottranslatable__c":false,"attributeRunTimeInfo":{"dataType":"Picklist","uiDisplayType":"Dropdown","default":[{"value":"C_OT_MB_EQUIPMENT_PHONES","id":20,"displayText":"Telefono"}],"values":[{"value":"C_OT_MB_ADMINISTRATIVOS","id":10,"displayText":"Cargo por Cambio o Baja"},{"value":"C_OT_MB_EQUIPMENT_ACCESORIOS","id":50,"displayText":"Accesorio"},{"value":"C_OT_MB_EQUIPMENT_MODEMS","id":30,"displayText":"Modem"},{"value":"C_OT_MB_EQUIPMENT_NETBOOK","id":60,"displayText":"Netbook"},{"value":"C_OT_MB_EQUIPMENT_PHONES","id":20,"displayText":"Telefono"},{"value":"C_OT_MB_EQUIPMENT_SIM","id":40,"displayText":"Simcard"}]},"$$AttributeDefinitionEnd$$":null},{"$$AttributeDefinitionStart$$":null,"objectid__c":"01tc0000005JSpyAAG","attributeid__c":"a0Jc0000008Mr5gEAC","attributecategoryid__c":"a0Ic000000HHYRYEA5","categorycode__c":"FAN_ATTCAT_000042","categoryname__c":"Integracion","attributeuniquecode__c":"FAN_ATT_000084","attributeconfigurable__c":true,"attributedisplaysequence__c"... (max length=1310...: [vlocity_cmt__JSONAttribute__c]  Can you help us to solve it?  Thanks in advance, Mariana
Edit Description
Steps to Reproduce
Steps to Reproduce:  ========================== 1) We are following the next steps: https://github.com/vlocityinc/vlocity_build#org-to-org-migration 2) See SOURCE AND TARGET documentation attached.
[EPC ORG TARGET CATALOG IMPORT ERRORS LOG.txt](https://github.com/vlocityinc/vlocity_build/files/2846320/EPC.ORG.TARGET.CATALOG.IMPORT.ERRORS.LOG.txt)
<img width="1132" alt="case 154058 - json attribute screenshot" src="https://user-images.githubusercontent.com/47457660/52497158-21a3c780-2bb4-11e9-8ed5-fac13f4a90bc.png">
[Case 154058 - maximum size of JSON field analysis in Source and Target orgs.docx](https://github.com/vlocityinc/vlocity_build/files/2846322/Case.154058.-.maximum.size.of.JSON.field.analysis.in.Source.and.Target.orgs.docx)
<img width="1440" alt="case 154058 in vlocity" src="https://user-images.githubusercontent.com/47457660/52497159-21a3c780-2bb4-11e9-9e90-0ea7de723fec.png">
[EPC ORG SOURCE Datapack created 20190131.docx](https://github.com/vlocityinc/vlocity_build/files/2846323/EPC.ORG.SOURCE.Datapack.created.20190131.docx)

**Comment by MarianaSanchezIBM** [comment]
We attempted to deploy one of the products that failed to another v103 Target Org (this org has nothing in common with our Telecom previous target org) and we got the same error. 
![issue 164 - same issue in another v103 org](https://user-images.githubusercontent.com/47457660/52504143-4a34bd00-2bc6-11e9-901f-ebaa03a00ada.jpg)

**Comment by rutlabaga** [comment]
Managed package issue
