### ISSUE TITLE
Unable to get Calculation Matrix imported in target environment

### ISSUE THREAD

**Issue by murtazamoin** [vlocityinc/vlocity_build#169]
I tried exporting a Calculation Matrix (Calculation Matrix, Calculation Matrix Version and Calculation Matrix Row) from source environment to target via Vlocity Build and during import I had encountered following issues:

1. Import failed due to Header column entries due to uniqueness error. I changed Name of Header entries to Header1, Header2 and able to get through the migration.
Deploy Error >> CalculationMatrix/<CalculationMatrixName> -- DataPack >> <CalculationMatrixName> -- Error Message -- Incorrect Import Data. Multiple Imported Records will incorrecty create the same Saleforce Record.

2. After Import is successful when I visited the Calculation Matrix Version record it showed following errors:
a. Table needs to be resaved before it can be enabled.
b. Your Matrix has no data. Click the "Add Header" button to get started manually, or "Upload CSV" to import data.

When looking at same version from Calculation Matrix view, it shows there are data rows imported.

I need support for following:
1. What exactly criteria to be used as Matching Criteria for Calculation Matrix Row so as Header Rows can also be migrated?
2. What is the issue in the import process causing error "Table to be resaved before it can be enabled" as it does not allow user to access the data from that view.

**Comment by rutlabaga** [comment]
Can you please upload the Calculation Matrix data you are having an issue with? 

If possible please also file a Vlocity Support case to assist with any further troubleshooting / communications.

**Comment by murtazamoin** [comment]
I will open a vlocity support case and upload all details.

I am happy to share Calculation Matrix data but this is confidential (business data) so I can send via email or provide Vlocity Support Case Number for reference.

**Comment by murtazamoin** [comment]
I have opened Vlocity Case # 00155968 for the above issue.

It contains all the relevant screenshots, files and Calculation Matrix data.

**Comment by rutlabaga** [comment]
Handled through Vlocity Support.
