### ISSUE TITLE
When deploying Omniscript with a reusable inactive Omniscript, the inactive one is not deployed

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#17]
When deploying Omniscript with a reusable inactive Omniscript, the inactive one is not deployed. No error message displayed.

**Comment by rutlabaga** [comment]
I do not fully understand this scenario. Do you have an example folder you could share that reproduces the behavior?

**Comment by Stepan007** [comment]
The scenario is that if there is an Omniscript (reusable) which is part of another Omniscript and it is deactivated then it is not deployed (and probably even not retrieved) which makes kind of sense because the vlocity build can't decide which version should export - but is there any mechanism which would inform the user that this reusable Omniscript was omitted? Or would it be at least possible to get a list of deployed components?

**Comment by KaustuvDas** [comment]
You can mention the Omniscript names in below format in project.yaml file.
![image](https://user-images.githubusercontent.com/42804518/47378348-7ad71080-d715-11e8-8b9f-728d0f11f9a9.png)

So the inactive Omniscripts gets omitted while extracting from source Org. You can match with your list of OmniScripts mentioned in the project.yaml file.
For getting all Omniscripts present in a Org, use below command in project.yaml file.

OmniScript:
  VlocityDataPackType: OmniScript
  query: Select Id, %vlocity_namespace%__Type__c, %vlocity_namespace%__SubType__c, %vlocity_namespace%__Language__c from %vlocity_namespace%__OmniScript__c where %vlocity_namespace%__IsActive__c = true AND %vlocity_namespace%__IsProcedure__c = false

**Comment by rutlabaga** [comment]
This is by design. Must be active to be exported.

**Comment by ingridyl09** [comment]
Has anyone found a solution? I have the same problem.

The error even occurs when deploy is related to any other development.

To solve it, I create a new manual version in the org and activate it and it works, but whenever there is a new deploy the same problem occurs
