### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by Shadlimitless** [vlocityinc/vlocity_build#18]
I am using the build to deploy some omniscripts chained together, and I keep getting the error shown in the image below, what could be the cause of this error?
![screen shot 2017-12-01 at 15 24 11](https://user-images.githubusercontent.com/12892045/33486911-ec476352-d6ab-11e7-9ae5-3d3b07e8d933.png)

**Comment by Stepan007** [comment]
What is the profile assigned to the user you are using for the deployment? Try to deploy it with System Admin.

**Comment by rutlabaga** [comment]
This is fixed in v1.4.1. Was a concurrency issue with Activation.
