### ISSUE TITLE
Attempt to de-reference a null object (vlocity_cmt)

### ISSUE THREAD

**Issue by nandinigangadhar** [vlocityinc/vlocity_build#191]
While running the Export command using vlocity build tool command line we are getting the following error   Promotion --- Id: a7J25000000Cec8EAC --- Unhandled Error on Export: Attempt to de-reference a null object (vlocity_cmt)

**Comment by edogaldo** [comment]
+1
Getting the same error with some promotions.
The problem seems related to some promotion items (removing the disturbing ones allows the promo export).
The strange thing is that the same promotion item configuration can be good or bad in different promotions..

**Comment by rutlabaga** [comment]
Requires Vlocity Support Case

**Comment by saisoma12** [comment]
I'm trying to migrate promotions from one org to another and getting this error -
Error Message -- Post Process Failed - Message: Attempt to de-reference a null object

I tried including all the dependencies, but still the promotion migration is still failing.
Any help on this would be highly appreciated!
