### ISSUE TITLE
Broken layout during export of Omniscript

### ISSUE THREAD

**Issue by pbazard** [vlocityinc/vlocity_build#200]
Hi, we have just migrated from one scratch org to another one using the Vlocity build tool. For one of our OS, we have spotted the following OS structure problem: 

**Source org**: the AcctNumDepChildren formula and the AcctNumGrandChildren number field are on the same line (control width of 6)

**Target org**: the AcctNumDepChildren formula is still at the same place but the AcctNumGrandChildren number has been moved at the bottom of the block.

<img width="314" alt="Capture d’écran 2019-04-17 à 13 57 06" src="https://user-images.githubusercontent.com/1006856/56362911-3f605f00-61eb-11e9-8aea-f847b72ddd05.png">
<img width="720" alt="Capture d’écran 2019-04-17 à 14 11 07" src="https://user-images.githubusercontent.com/1006856/56362931-4be4b780-61eb-11e9-8a3b-d7bef8ad6113.png">

**Comment by rutlabaga** [comment]
Please file Vlocity Support case if still persisting.
