### ISSUE TITLE
Installing Older Releases - error in documentation

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#203]
npm install --global https://github.com/vlocityinc/vlocity_build#v1.9.0
installs v.0.0.1
(this is how it is described here:
https://github.com/vlocityinc/vlocity_build#installing-older-releases
)

Command that works for us is:
npm install --global vlocity@1.9.0

**Comment by rutlabaga** [comment]
Fixed. Thanks
