### ISSUE TITLE
Export of Omniscript and Integration Procedure changes order of steps

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#205]
It is not deterministic but sometimes we observe that order of steps in exported file is different than on source environment. This is a huge problem for us.
Example - CancelOrder_RD step is moved after CancellationProcedure_IP:
![VBOrderOfStepsError](https://user-images.githubusercontent.com/36472902/59332771-4e4d2480-8cf7-11e9-86ad-5ec2de7ea507.PNG)
![VBOrderOfStepsError2](https://user-images.githubusercontent.com/36472902/59332775-50af7e80-8cf7-11e9-92d2-2acd12228be1.PNG)

**Comment by rutlabaga** [comment]
Please file a Vlocity Support Ticket
