### ISSUE TITLE
RemoveOldAttributeAssignments Query limit reached

### ISSUE THREAD

**Issue by paferpo** [vlocityinc/vlocity_build#208]
The class RemoveOldAttributeAssignments is exceeding the query limits and it fails the build.

https://github.com/vlocityinc/vlocity_build/blob/dacf7ffd327c016208a0ce9d0db835079e8ed459/apex/RemoveOldAttributeAssignments.cls#L34

Error log:

 Loading Apex >> C:\Program Files\nodejs\node_modules\npm\node_modules\vlocity\apex\RemoveOldAttributeAssignments.cls
24-Jun-2019 16:21:27	APEX Exception StackTrace >> Class.Database.QueryLocatorIterator.hasNext: line 41, column 1
24-Jun-2019 16:21:27	AnonymousBlock: line 34, column 1
24-Jun-2019 16:21:27	APEX Exception Message >> System.LimitException: Too many query rows: 50001
24-Jun-2019 16:21:27	Uncaught Job Error >> Apex Error >> [object Object] APEX code failed to execute but no exception message was provided
24-Jun-2019 16:21:27	  Job Complete >> CleanOrgData
24-Jun-2019 16:21:27	CleanOrgData error:
24-Jun-2019 16:21:27	Apex Error >> [object Object] APEX code failed to execute but no exception message was provided

**Comment by rutlabaga** [comment]
This has been fixed in `v1.11.2` by removing this class from running.
