### ISSUE TITLE
Vlocity Build tool not picking all components for deployment.

### ISSUE THREAD

**Issue by amreshvijay** [vlocityinc/vlocity_build#209]
Hi,

I'm using latest version of Vlocity build tool, 1.11.
When I deploy from Jenkins, VBT does not pick all the components for deployment. From Jenkins, when we run refreshProject, it shows the total component count as 706. In sandbox also, we can see remaining components not getting deployed.

But, when I run the same set of commands from local machine, with same source and same yaml manifest, the total component count comes as 905. And, everything gets deployed correctly.

Kindly help.

**Comment by rutlabaga** [comment]
Please check the Version of Node you are using. There have been issues reported with Node 8 and the latest version v1.11.2 now requires Node 10 to run.
