### ISSUE TITLE
Inform about error druing VLocity Product Catalog Deployment

### ISSUE THREAD

**Issue by rholeszczuk** [vlocityinc/vlocity_build#211]
Hi, during depoyment of PC we got some errors on deployment script 
`    [exec] Deploy error:
     [exec] Activation Error >> CalculationProcedure/Material_Code --- There is no active version for matrix " Material Code" in this effective time range.
     [exec] Activation Error >> CalculationProcedure/SourceTargetAttributePricingProcedure --- There is no active version for matrix " SourceTargetAttributePricingMatrix" in this effective time range.`
whole script didn't end up with an error so our pipelines didn;t notice it. is there any way to inform (error code on script, email or sth else) about those errors ? it will be very helpful in anutomation processes..
Thx
Regards
r.

**Comment by rholeszczuk** [comment]
Any Comment ?

**Comment by rutlabaga** [comment]
Are you on the latest version?

**Comment by rholeszczuk** [comment]
We got this on latest version too, but we don't use it becasue there are other errors, related with activation of omniscripts too.

**Comment by rutlabaga** [comment]
Can you provide the log for the deployment?

**Comment by rholeszczuk** [comment]
yes, this part causing problems :
	[exec] Deploy error: 
	[exec] Activation Error >> CalculationProcedure/Material_Code --- There is no active version for matrix " Material Code" in this effective time range. 
	[exec] Activation Error >> CalculationProcedure/SourceTargetAttributePricingProcedure --- There is no active version for matrix " SourceTargetAttributePricingMatrix" in this effective time range.

**Comment by rutlabaga** [comment]
Can you provide the full log?

**Comment by rholeszczuk** [comment]
Can you provide response for my question ? I will send you logs to email.

**Comment by rutlabaga** [comment]
The process should always have an exit code of 1 when there is an error.

**Comment by EdgarsAvotins** [comment]
Hi, @rutlabaga !
You're correct, it should always have an exit code of 1 when there is an error. But that's the problem - process had an error, but it did not return exit code of 1, instead if returned 0, so the error could not be automatically detected. Is that visible from the logs? (error should be visible there, but in the end - "BUILD SUCCESSFUL")

**Comment by padlakha** [comment]
@rutlabaga 
Customer is facing this issue again and this time [exec] Result: 1
So, the issue on UI build is successful but some when we check target org components are not deployed correctly and then we have to backtrack to find the error.

[exec] Job Complete >> Deploy
[exec] Deploy error:
[exec] Product2/P-30GBDA -- DataPack >> 30 GB -- Error Message -- Incorrect Import Data. Multiple Imported Records will incorrecty create the same Saleforce Record. vlocity_cmt__AttributeAssignment__c: NEW_ATTR-offerType Override
[exec] Product2/P-50GBDA -- DataPack >> 50 GB -- Error Message -- Incorrect Import Data. Multiple Imported Records will incorrecty create the same Saleforce Record. vlocity_cmt__AttributeAssignment__c: NEW_ATTR-offerType Override
[exec] Result: 1

BUILD SUCCESSFUL
Total time: 5 minutes 47 seconds
[go] Task status: passed, took: 5m 52.128s
[go] Current job status: passed

Appreciate your help here !!

**Comment by rutlabaga** [comment]
`[exec] Result: 1`

This is showing that the Vlocity Build Tool returned an exit code of 1 which means it failed. This means the issue must be with the script not failing on exitCode 1.
