### ISSUE TITLE
Error Getting Diffs 

### ISSUE THREAD

**Issue by paferpo** [vlocityinc/vlocity_build#212]
Hi, 

We are getting the following error with gitCheck activated:

`Git Hash >> f82527bc60afe4fd805511c98097b02d2bd42f51  
error fatal: bad object f82527bc60afe4fd805511c98097b02d2bd42f51
error Error Getting Diffs >> Error: Command failed: cd data && git diff --stat f82527bc60afe4fd805511c98097b02d2bd42f51 --raw --no-renames
error fatal: bad object f82527bc60afe4fd805511c98097b02d2bd42f51
error error at checkExecSyncError (child_process.js:616:11)
error at Object.execSync (child_process.js:653:13)
error at module.exports.UtilityService.getGitDiffsFromOrgToLocal (C:\Program Files\nodejs\node_modules\npm\node_modules\vlocity\lib\utilityservice.js:457:43)
error at process._tickCallback (internal/process/next_tick.js:68:7)`

Any idea why this would happen?

**Comment by rutlabaga** [comment]
Your branch / repo does not have the Git Hash that is saved in your Org. You need to make sure you are always deploying the same branch when using the gitCheck feature. You can see the saved hash value in the Custom Setting called General Settings with Name = VBTDeployKey. The value of this object must be a valid hash in your Git repo

**Comment by paferpo** [comment]
Looks like the issue was with a configuration in Bamboo, we had "Use shallow clones" in the repository settings and that's why git was not able to find the hash. Leaving here this info in case someone else has the same issue...
