### ISSUE TITLE
ObjectLayout migrated but Layout not displayed

### ISSUE THREAD

**Issue by murtazamoin** [vlocityinc/vlocity_build#213]
All ObjectLayouts are migrated from Production to Sandbox. When visiting a Product in Vlocity Product Console, the layout is shown in Production but not shown in Sandbox. When ran a Vlocity Build export and comparison of Object Layout for Product2 Object it shown identical but not displaying on the Vlocity Product Console.

Screenshots side-by-side attached for reference
![Product2 Layout Comparison - Production and Sandbox]
(https://user-images.githubusercontent.com/30211777/61318548-92ce5300-a7c2-11e9-83e6-fcf808c431bf.png)

**Comment by rutlabaga** [comment]
Please file a case with support@vlocity.com
