### ISSUE TITLE
Official Docker Hub image

### ISSUE THREAD

**Issue by thvd** [vlocityinc/vlocity_build#227]
Is there an official supported Docker container of Vlocity build tool on Docker Hub? Like there is now for Salesforce DX: https://hub.docker.com/r/salesforce/salesforcedx.

I have seen the Dockerfile (https://github.com/vlocityinc/vlocity_build/blob/master/Dockerfile), so i could build it myself, but it would be nice to have a official supported one on Docker Hub.

**Comment by rutlabaga** [comment]
I'll look into publishing something. Thanks.

**Comment by cossss** [comment]
Would be an awesome feature if this can be published.

**Comment by oxycash** [comment]
Do you guys activate LWC flash cards using puppeteer (default in vlocity build CLI) ? how you solve the puppeteer-sandboxing issue in Docker?
