### ISSUE TITLE
Cannot export multiple PartyRelationshipTypes

### ISSUE THREAD

**Issue by pbazard** [vlocityinc/vlocity_build#231]
When exporting multiple PartyRelationshipTypes with the same Name but with a unique key composed of **{Name,TargetRole}, we get only one record in the export folder. 
The corresponding matching key has been set correctly.

![unnamed](https://user-images.githubusercontent.com/1006856/66029625-f2a1e380-e4ff-11e9-9fa6-57d2a03aa742.png)

**Comment by rutlabaga** [comment]
Sorry, missed this being posted. 

Add to your job file:
`
OverrideSettings:
  SObjects:
    vlocity_namespace__PartyRelationshipType__c:
      FolderName: 
        - Name
        - vlocity_namespace__TargetRole__c
