### ISSUE TITLE
packGetAllAvailableExports output limited to 2000 records

### ISSUE THREAD

**Issue by lmargal** [vlocityinc/vlocity_build#256]
The queries of packGetAllAvailableExports are executed with the query method of https://jsforce.github.io/jsforce/doc/Connection.html without handling properly the QueryResult object received. The QueryResult should be handled to call queryMore when more records are to be retrieved. As a consequence of this issue the packGetAllAvailableExports is limiting the list of available records of a given type to the first 2000 when more than 2000 exist

**Comment by rutlabaga** [comment]
Thanks. This is now fixed in v1.11.20
