### ISSUE TITLE
Question:  is there a Deploy version of packExportSingle?

### ISSUE THREAD

**Issue by leothelocust** [vlocityinc/vlocity_build#266]
Essentially I'd like to be able to do the following:
```
vlocity packExportSingle 
        -propertyfile build.properties 
        --nojob 
        -type 'VlocityUITemplate' 
        -id 'Test-test'
        -depth 0
```
**but with regard to deployment**.

So in essence, something like:
```
vlocity packDeploySingle 
        -propertyfile build.properties 
        --nojob 
        -type 'VlocityUITemplate' 
        -id 'Test-test'
        -depth 0
```

Is there a way to do this?

**Comment by rutlabaga** [comment]
Yes use the `-key VlocityUITemplate/Test-test`. This is not well explained in the documentation but this video has all the details:
https://drive.google.com/file/d/1FRKBrPqtfB2I_U57lJToHvWcR3Tld74s/view?usp=sharing

**Comment by leothelocust** [comment]
Thanks Adam!
