### ISSUE TITLE
Feature: View a "thing" in org

### ISSUE THREAD

**Issue by leothelocust** [vlocityinc/vlocity_build#267]
Would love to see a feature to "browse to a thing" online in the org.

Example:

```sh
$ vlocity gotoOrg -sfdx.username -job job.yaml -key VlocityUITemplate/TestTemplate
```
which would launch the default browser and take you to the correct org and open the Vlocity Template "TestTemplate"

**Comment by manas-sf** [comment]
It is supported in IDX. For VBT we have datapackOpen command, although not fully supported.
