### ISSUE TITLE
Omniscript element with custom template not rendering after deployment

### ISSUE THREAD

**Issue by cossss** [vlocityinc/vlocity_build#268]
Hello,

We have an omniscript block element that has a custom template assigned to it. If we deploy via vlocity_build tool we have to deactivate and activate the omniscript before this template is rendered.

We do have the setting (compileOnBuild: true). Any idea how to solve this problem?

**Comment by rutlabaga** [comment]
Are you using `sfdx.username` parameter? If so, you can add to job file ->
reactivateOmniScriptsWhenEmbeddedTemplateFound: true

**Comment by cossss** [comment]
Thanks for your anwser. I'll try this one out!
