### ISSUE TITLE
Unhandled Error on Export: Attempt to de-reference a null object (vlocity_cmt)

### ISSUE THREAD

**Issue by mechlion** [vlocityinc/vlocity_build#270]
Getting error when exporting Omniscript using below yaml

```
projectPath: ./vlocity-app/
manifestOnly: true
manifest:
  OmniScript:
    - Type: casemanagement 
      Sub Type: create 
      Language: English
```

Error:
  Error >> undefined - Unhandled Error on Export: Attempt to de-reference a null object (vlocity_cmt)

**Comment by rutlabaga** [comment]
Please file a Vlocity Support case if this is still an issue. Sorry for the delay in answering.
