### ISSUE TITLE
Login Failed >> Retrying Login Failed

### ISSUE THREAD

**Issue by edwardh17** [vlocityinc/vlocity_build#272]
Hi, I'm trying to use this tool for the first time but I'm having some issues to login with the parameters on the properties file:

Error Error: Invalid URI "%3C%20https://test.salesforce.com%20%3E/services/Soap/u/42.0" 

I'm using test because I need to login into a sandbox.

This is my 3rd line on properties file:
sf.loginUrl = < https://test.salesforce.com >

Can somebody help me with this? I don't know what I'm doing wrong. Thanks!

**Comment by rutlabaga** [comment]
Remove the <>.
`sf.loginUrl = https://test.salesforce.com`
