### ISSUE TITLE
PricingElementTriggerHandlerException: Script-thrown exception

### ISSUE THREAD

**Issue by edwardh17** [vlocityinc/vlocity_build#273]
Hi, I'm trying to deploy a PriceList from one org to another and I am getting this error:

Deploy error:
PriceList/PRL_TELCOM -- DataPack >> Telecom Price List -- Error Message -- vlocity_cmt.PricingElement: execution of BeforeUpdate

caused by: vlocity_cmt.PricingElementTriggerHandler.PricingElementTriggerHandlerException: Script-thrown exception

Does somebody know something about this issue? Why is this happening? Thanks!

**Comment by rutlabaga** [comment]
Please file a case with Vlocity Support.

**Comment by anbu-selvan** [comment]
@edwardh17  Hi, can you share me the response or fix that was provided by Vlocity. I have already raised a case with Vlocity and mean while I am triaging from my end as well, if its in my boundary to fix it.
Thanks
