### ISSUE TITLE
packGetDiffs and packGetDiffsAndDeploy Always Return State Model as New

### ISSUE THREAD

**Issue by maristei** [vlocityinc/vlocity_build#275]
When using packGetDiffs and packGetDiffsAndDeploy to perform delta deployment, state model is always returned as new even though it was retrieved from same sandbox and was already deployed several times.

Executed command:
vlocity -propertyfile properties\ReleaseItems_source.properties -job dataPacksJobs\ReleaseJob.yaml packGetDiffsAndDeploy

Console output:
New >> VlocityStateModel - VlocityStateModel/Contract State Model

**Comment by manas-sf** [comment]
https://github.com/vlocityinc/vlocity_build#git-changes-based-deploys
