### ISSUE TITLE
Omniscript Error Deploy

### ISSUE THREAD

**Issue by NerioVillalobos** [vlocityinc/vlocity_build#280]
Hi,

I am running a single component Omniscript-like deployment and I get the following error:

Deploy error:
OmniScript/<NameObject> -- DataPack >> <NameObject> -- Error Message -- Unexpected character ('I' (code 73)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at input location [1,2]

Regards,
NerioVillalobos

**Comment by tggagne** [comment]
Did you figure it out?

**Comment by manas-sf** [comment]
Please feel free to raise investigation with Salesforce support with all the details.
