### ISSUE TITLE
Deployment of LWC Omniscripts

### ISSUE THREAD

**Issue by cossss** [vlocityinc/vlocity_build#287]
Hi there,

Is there a way te deploy LWC omniscript including the corresponding LWC component that is generated (e.g. the "deploy LWC")?

Currently we deploy the Omniscript using vlocity_build and the LWC is deployed using sfdx, but the problem is that the Omniscript ID is hardcoded in the LWC Omniscript *_def.js.

So, is there a supported way too overcome this issue?

Thanks!

**Comment by thvd** [comment]
Has been solved by the release of 1.14

https://github.com/vlocityinc/vlocity_build/releases/tag/v1.14.0
