### ISSUE TITLE
Command not found: .username / .loginUrl

### ISSUE THREAD

**Issue by FabienHuot** [vlocityinc/vlocity_build#293]
- sfdx is installed
- vlocity is installed 

When I want to deploy, there is an error with a "Command not found."
Even with the lastest version of Vlocity, I got the same issue.
Any idea? 

![image](https://user-images.githubusercontent.com/1270173/84881068-a991bf80-b08d-11ea-9947-39cae6f69cd0.png)

**Comment by shaneasullivan** [comment]
@FabienHuot  - So I had the same trouble and I found the documentation was misleading.  I had to put the `sfdx.username` command in a properties file for the command to be recognized.  So your .properties files will look like:

```
sfdx.username = shane.something@domain.com.dev1
sf.loginUrl = https://test.salesforce.com
```

Then the command line throw looks like:
`vlocity packExport -propertyfile deployment/build.properties -job .vlocity/exampleMigration.yaml`

You'll know it is working when you see the following output:
```
Vlocity Build v1.12.1
  Org >> shane.something@domain.com.dev1
  Using SFDX >> shane.something@domain.com.dev1
  Refreshing SFDX Session >> shane.something@domain.com.dev1
....
```

I hope that helps and gets you past the login hurdle.

**Comment by ModeratelyComfortableChair** [comment]
@shaneasullivan So essentially we can't use the `-sfdx.username <username/alias>` tag and use an alias connected by sfdx? Ideally we would not want to store our user credentials in a build.properties file. Especially if we want to use this in a pipeline.
