### ISSUE TITLE
Create custom matching keys

### ISSUE THREAD

**Issue by IIvanov8888** [vlocityinc/vlocity_build#31]
How would I create custom matching keys ? I seem to have problem with importing Product2 , due to missing fields, even with manual import/ export. 

```
IPhone 8 (Product2): Field does not exist: vlocity_cmt__EntityFilter__c.vlocity_cmt__GlobalKey__c (vlocity_cmt)

```

**Comment by rutlabaga** [comment]
I recently added a section to the Readme for creating custom matching keys:

https://github.com/vlocityinc/vlocity_build#creating-custom-matching-keys
