### ISSUE TITLE
Packexport getting failed after running 2 weeks 

### ISSUE THREAD

**Issue by bpradeeptime** [vlocityinc/vlocity_build#310]
Result :<--- Last few GCs --->[7132:0x2f77ea0] 1145034719 ms: Mark-sweep 1635.3 (1834.3) -> 1635.2 (1803.1) MB, 279.6 / 0.0 ms (average mu = 0.977, current mu = 0.000) last resort GC in old space requested[7132:0x2f77ea0] 1145034930 ms: Mark-sweep 1635.2 (1803.1) -> 1635.1 (1803.1) MB, 210.9 / 0.0 ms (average mu = 0.958, current mu = 0.000) last resort GC in old space requested<--- JS stacktrace --->==== JS stack trace ========================================= 0: ExitFrame [pc: 0x134c12d]Security context: 0x1536a9ac08d1 1: fromString(aka fromString) [0x28f20f74ad9] [buffer.js:~438] [pc=0x35fb301061c2](this=0x1b4d1d1404b1 ,0x3d5031b09419 ,0x1539485684c1 ) 2: from [0x15394856f879] [buffer.js:302] [bytecode=0x26be65e3fa49 offset=14](this=0x028f20f49771

![image](https://user-images.githubusercontent.com/26279737/89540766-1e29e480-d81b-11ea-86a5-8cd6214c09ab.png)

**Comment by rutlabaga** [comment]
I think probably this is fixed in the v1.12.2 release.
