### ISSUE TITLE
Vlocity Template - a mixture of characters instead of HTML after deployment

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#32]
See the attached picture for details:

<img width="951" alt="screen shot 2018-01-29 at 11 50 41" src="https://user-images.githubusercontent.com/33927875/35506917-4c9b90c6-04eb-11e8-8b3e-fd0529427a32.png">

**Comment by rutlabaga** [comment]
I just pushed a fix that I believe will fix this issue, though I have not reproduced it locally. Please let me know if you still have problems. And if so, please send me the folder with the VlocityUILayout in it.

**Comment by Stepan007** [comment]
Hi Adam, unfortunately, it is still not working. Can you have a look at that? As it is causing us a lot of issues...

**Comment by Stepan007** [comment]
when using dataPacks it works...but almost every omniscript uses templates and it is very annoying to do it manually

**Comment by Stepan007** [comment]
The json files on the harddrive looks good to me...I can provide you both with source retrieved by vlocity_build and dataPacks if needed.

**Comment by rutlabaga** [comment]
Please email me at arutland@vlocity.com with all the details. Thanks!

**Comment by rutlabaga** [comment]
Issue was related to .html in the Name of a VlocityUITemplate. I have fixed this from being an issue in the commit af8c7579a5e5c994aa7faa30ee65813545352298.

Thanks!
