### ISSUE TITLE
packDeploy is not deploying steps within an Omni script

### ISSUE THREAD

**Issue by mweiss427** [vlocityinc/vlocity_build#33]
It looks like when getting a list of the JSON files it is not getting the file paths correctly.  The picture shows the error. 

![2018-01-29_14-51-12 002](https://user-images.githubusercontent.com/22085759/35534849-5bd49904-0507-11e8-8120-b1b7bab743f7.png)
e

**Comment by mweiss427** [comment]
Note: This is currently not a symptom of the feature/manifest_update branch.   All the other active branches currently have an issue with packDeploy

**Comment by rutlabaga** [comment]
I just pushed a fix for this issue. Please let me know if you still have problems.
