### ISSUE TITLE
sf.username and sf.password as ant parameters

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#34]
Would it be possible to pass sf.username and sf.password as ant parameters?

**Comment by Stepan007** [comment]
ant packExport -dsf.username=value1 -dsf.password=value2

**Comment by rutlabaga** [comment]
You can pass in any parameters to the `vlocity` command with just the name of the variable `vlocity -sf.username xyz`. Right now the ant support has not kept up with the newer features. I would have to look into a more generic way to pass in parameters from ant to vlocity.

**Comment by rutlabaga** [comment]
Ant no longer supported
