### ISSUE TITLE
Deployment of Vlocity Objects and Vlocity Layouts

### ISSUE THREAD

**Issue by IIvanov8888** [vlocityinc/vlocity_build#35]
hi,
I am facing the following issues when deploying Vlocity Objects and Layouts 

```
Deploy Error >>  ObjectLayout/79ab53b4-f2fa-82e3-ed1a-d8e5156c4304 --- Layout-a1g0E0000008qcdQAA --- No match found for vlocity_cmt__ObjectLayout__c.vlocity_cmt__SubclassId__c - vlocity_cmt__GlobalKey__c=896b2516-5d54-0075-35b6-9ec9f5780b05 (vlocity_cmt)

```

```
Deploy Error >>  ObjectClass/993399ed-eeaf-1174-463a-3ded233a073e --- DEVICE <<PS>> --- No match found for vlocity_cmt__ObjectClass__c.vlocity_cmt__ParentObjectClassId__c - vlocity_cmt__GlobalKey__c=896b2516-5d54-0075-35b6-9ec9f5780b05 (vlocity_cmt)

```

**Comment by rutlabaga** [comment]
This means that you are missing the ObjectClass with Global Key = 896b2516-5d54-0075-35b6-9ec9f5780b05. Does this exist in your project?

**Comment by IIvanov8888** [comment]
@rutlabaga 
I am getting the following 
Export error:
ObjectLayout --- Id: a1g0E0000008jz7QAA ---  --- Ignored
ObjectLayout --- Id: a1g0E0000008qbQQAQ ---  --- Ignored
ObjectClass --- Id: a1g0E0000008qcdQAA ---  --- Ignored
ObjectLayout --- Id: a1g0E0000008qcdQAA ---  --- Ignored


The user has access to the objects

**Comment by rutlabaga** [comment]
Try pulling the latest from master.

You can also specifically export that ObjectClass with the following:
`vlocity packExport -type ObjectClass -query "Select Id from vlocity_cmt__ObjectClass__c where vlocity_cmt__GlobalKey__c = '896b2516-5d54-0075-35b6-9ec9f5780b05'"`

**Comment by IIvanov8888** [comment]
@rutlabaga after pulling latest master, no issues with exporting , the objects are found but deployment did not work, again with same errors. Could it be access issues on the target env ?

**Comment by IIvanov8888** [comment]
Issue was access of the user on the targer env, closing the issue for now. Thanks @rutlabaga
