### ISSUE TITLE
LWC Omniscript deploy issue

### ISSUE THREAD

**Issue by faugusto7** [vlocityinc/vlocity_build#361]
Hi Sirs,

When we're deploying an omniscript to another org using VBT we are facing an issue that causes omniscript stay inactive.
We always have to deactivate and activate it in order for it work correctly. Also we are deploying the LWC related to the OS via SFDX, and it still requires to deactivate and activate manually.

Is there a way to avoid the manual steps to see the OmniScript correctly after the deploy?

Is there any other component besides the OS that should be deployed in order to avoid the need to deactivate and activate it manually?

Thank you in advance..

**Comment by rutlabaga** [comment]
Sorry for not responding sooner but wasn't sure on the exact day it would be merged. 

This is now a feature in v1.14 Release.

**Comment by camilamamani** [comment]
Hi, 

We have a similar issue, the difference is the deployment works well and the new version is activated in the destination org but when consulted it displays the following error 
**Error
This OmniScript is either inactive or has been replaced with a new version which has not been deployed.**

So we too have to deactivate and activate it in order for it to work correctly.  Is there a way to avoid the need to deactivate and activate it manually? We deploy with Copado tool which is integrated with VBT version 1.15.2.

I would really appreciate help here. Thanks!

**Comment by faugusto7** [comment]
Hi @camilamamani, for deploys with Copado take a look here:

https://docs.copado.com/articles/#!copado-ci-cd-publication/vlocity-integration/a/h2_1264078001


![image](https://user-images.githubusercontent.com/36142870/178076277-9e8e795a-498c-4c5d-9e25-82ae091e4a13.png)
