### ISSUE TITLE
Attribute assignment overrides missing on export

### ISSUE THREAD

**Issue by domrin123** [vlocityinc/vlocity_build#372]
Hi,

I'm trying to work out if the issue I'm running into is the same as the one mentioned in the known issues:

> If you have more than 300 Attribute Assignments or Product Child Items on a Product and use Override Definitions then there can be issues with OverrideDefintions missing Overridden Attritubtes on records where the Overridden Attribute is related to the Product with more than 300 Attribute Assignments or Product Child Items.

In my scenario, I have exported a product which is overridden in a number of promotions, but when I look at the promotion's "Promotion_AttributeOverride.json" it has "OverridingAttributeAssignmentId__c" that references an attribute in the overridden product that doesn't appear in the product's "Product_AttributeAssignments.json". The product does indeed have more than 300 assignments.

Is this the same as the known issue? If so - is there a workaround to export the missing attribute assignments?

Thanks,

Dom

**Comment by rutlabaga** [comment]
Please file a support case with all the details and someone will help you resolve.
