### ISSUE TITLE
Omniscript Activation Error

### ISSUE THREAD

**Issue by enrique-SFBG** [vlocityinc/vlocity_build#386]
Hi, I am having this issue that was fixed in version 1.9 again. Some Omniscripts that are nested are not being activated in the deploy.

`Fixed in v1.9 OmniScripts that are embedded in many other OmniScripts cannot be activated due to SOQL Query limits. Error: System.LimitException: vlocity_cmt:Too many SOQL queries: 101 The datapacks will be deployed, however a manual activation of the latest OmniScript after deployment is required.`

Activation Error >> OmniScript/Details_English --- INVOKE-500
Activation Error >> OmniScript/Mobile_English --- Not Activated

Thank you.

**Comment by rutlabaga** [comment]
Please file a support case so that someone can investigate the possible root cause based on your specific files.

**Comment by burntsugar** [comment]
Was this resolved?
