### ISSUE TITLE
is it possible to deploy from source(Folder) to org?

### ISSUE THREAD

**Issue by jcbenitezh** [vlocityinc/vlocity_build#389]
Is there any way to deploy from datapackMetadata to destination Org?
Maybe using the vlocity plugin from vscode?
I found this url: https://github.com/Codeneos/vlocode
And them have a link to this repo for the yaml documentation, so, i think it can be posible, but
I need it for ci cd,  (working in a github workflow). but i dont know if a temp file is generated like yours (currentJobInfo.json)
Or if you have a solution to deploy from a specific folder, without always retrrieving first from source org.

**Comment by rutlabaga** [comment]
If you setup the Job File to point to your folder then it will deploy from there.  The Project Path can be any absolute or relative path.

**Comment by jcbenitezh** [comment]
I have tried to do that, but if the currentJobInfo.json is not generated from a export, it doesnt to anything 
Example:
![image](https://user-images.githubusercontent.com/83037916/127696381-05ae4303-cc1f-49b5-a6ad-26d4b53eb485.png)

![image](https://user-images.githubusercontent.com/83037916/127696443-302d316c-53ca-40b7-9ec7-6240f846f8fc.png)

where 
project path

![image](https://user-images.githubusercontent.com/83037916/127696700-7461a546-75b0-4bd8-bf06-1eb7f76ba364.png)

I tried using
 - VlocityDataPackType: OmniScript
    query: SELECT id from vlocity_cmt__OmniScript__c  where Name = 'ActivationForced'  LIMIT 1
    
    instead of manifest, but I get the same type of result.
    
I tried to copy the temp_vlocity folder from another one job, and  then run the packdeploy, and it run the .json and deploy the info from there, but maybe it is something wrong in by job file. 

![image](https://user-images.githubusercontent.com/83037916/127697308-492c17c7-4437-4307-928c-c4bd28479f75.png)
