### ISSUE TITLE
APEX_ERROR : System.LimitException: Apex CPU time limit exceeded

### ISSUE THREAD

**Issue by manuelepalmeri** [vlocityinc/vlocity_build#39]
Hi,
we're having problems exporting/importing some (large) Omniscripts because we get "Apex CPU time limit exceeded" error.

Vlocity Support told us that using this script would have solved the problem. (quote: "There is no known limit to the size of the OS that can be moved using the build tool. Its meant to be able to move large amounts of data from one org to the other." ).

Unfortunately, we get the same error we had in UI export/import, as you can see in the picture below.

Is there a way to solve this?

I'm currently using Vlocity CMT 11.43.1.

Best regards,
Manuele.

![errore vlocity](https://user-images.githubusercontent.com/7695615/36380960-65975de0-1584-11e8-8842-2eedbefb7d06.PNG)

**Comment by rutlabaga** [comment]
The one thing you can do is set the DRMapItem__c records where Name = 'OmniScript Migration' AND ConfigurationProcess__c != null to IsDisabled__c = true. This will turn off the linking between objects in DataPacks which may have a performance improvement and mitigate the issue.

Unfortunately the only other options will be to upgrade to a newer version of the Vlocity Managed Package. There is always some finite number of OmniScript Elements that DataPacks can support but it is heavily dependent on release version as we are improving performance for every release.

**Comment by manuelepalmeri** [comment]
Hi rulabaga,
just to be sure, when you say "but it is heavily dependent on release version as we are improving performance for every release" do you mean vlocity version or salesforce version?

**Comment by manuelepalmeri** [comment]
I was able to export the omniscript following your instruction of put "IsDisabled__c" = true.

unfortunatelly I have now problem during deploy:

![import error](https://user-images.githubusercontent.com/7695615/36473953-622f5ba8-16f6-11e8-89b9-a24ca7a2465f.PNG)

I get "Error Processing: Attempt to de-reference a null object" error

Thank you

**Comment by manuelepalmeri** [comment]
Hi,
do you have any news about the problems of Import/Export of Omniscripts that we discussed here and during the call with Vlocity Support Center on February 21st?

The problem is really serious and we are unable to deliver in production until we solve.

Thanks for understanding.

Best regards,
Manuele.

**Comment by rutlabaga** [comment]
You should try exporting / importing with the UI now. The v11 Vlocity Package is not well supported by this build tool. Vlocity recently released v17, so that version is quite old.

**Comment by manuelepalmeri** [comment]
Hi,
so if I upgrade the Vlocity Package I will be able to export and import correctly?

Thank you.

**Comment by rutlabaga** [comment]
I would not necessarily advise upgrading the entire package version jus to solve this one issue, however it will likely work better. Did you try using the UI to export after having disabled the mappings?

**Comment by manuelepalmeri** [comment]
Hi,
like I said this issue is pretty bad and prevent us to deliver the OS in production, so we must fix it

I tried to import using the UI but it gives me the following error:

>  Id: a1v9E000002hLsNQAU : Duplicate Results found for - Related Ids: 0050E000000b1YnQAI,0050E000000b1ajQAA,0050E000000b1aZQAQ,0050E000000b1XkQAI,0050E000000b1bNQAQ,0050E000000b1brQAA,0050E000000b1c6QAA,0050E000000b1cQQAQ,0050E000000b8G7QAI,0050E000000bASPQA2,0050E000000b8b5QAA,0050E000000bPm5QAE,0050E000000bPl2QAE,0050E000001Qdw1QAC,0050E000000b9CLQAY

![image](https://user-images.githubusercontent.com/7695615/36684879-0027eda0-1b22-11e8-9d95-58dca6fdcb29.png)

If I click to "Ignore this error" it says "Import Completed!" but, actually, nothing shows up.

Thank you.

**Comment by rutlabaga** [comment]
What kind of SObject are these Ids?

**Comment by manuelepalmeri** [comment]
The first one (a1v9E000002hLsNQAU) is vlocity_cmt__Omniscript__c, the others are User Id

**Comment by rutlabaga** [comment]
In this case the issue is that you have multiple users with the same Email Address, and one of them likely is set in the OmniScript. You can fix this by running a find / replace on the file for whatever Id field is referencing that User. You can replace that field name with anything else.

**Comment by rutlabaga** [comment]
Managed Package issue. Better performance in more recent versions
