### ISSUE TITLE
Custom fields are not updated on Product2  PackDeploy.

### ISSUE THREAD

**Issue by cleververve** [vlocityinc/vlocity_build#407]
We have a product2 custom field Telia_Contract_Offering_ID__c,  which is exported into DataPack.json in PackExport, but not updated with PackDeploy command in a target org. Fields security is not an issue: the PackDeploy is executed by admin profile user, no custom logics on this field.
![image](https://user-images.githubusercontent.com/45824550/140094592-88dc3393-4b16-49ca-90e2-f40394648da9.png)

**Comment by rutlabaga** [comment]
Is it just that single field? Can you make sure the Case of the field is consistent between the two orgs?

ID vs Id

**Comment by thvd** [comment]
We see the same thing happening, very time consuming to make specific field updates every time.

**Comment by thvd** [comment]
@manas-sf why is this closed? To my knowledge this isn't solved yet.
