### ISSUE TITLE
How to use this Puppeter LWC Auto Compilation in Github Actions?

### ISSUE THREAD

**Issue by AllanOricil** [vlocityinc/vlocity_build#410]
Github Actions currently does not let us run containers that have its dockerfile specifying USER.  So I can't run it with a puppeter user. To use this "Puppeter LWC Auto Compilation" feature on Github Actions as a root user, I understood that I have to pass "--no-sandbox" to puppeter when lauching the browser, but I don't think you allow us to configure it, right? If you do, how can I do it?

Github Actions Doc saying we can't use containers with USER: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user

Stackoverflow Post explaning I have to use "--no-sandbox": https://stackoverflow.com/questions/50662388/running-headless-chrome-puppeteer-with-no-sandbox

This post explains how to use Puppeter as a Root User in Container: https://www.cloudsavvyit.com/13461/how-to-run-puppeteer-and-headless-chrome-in-a-docker-container/

**Comment by rutlabaga** [comment]
This tool already passes --no-sandbox

**Comment by AllanOricil** [comment]
@rutlabaga have you ran it on a Github Action ?

I saw that puppeter options is configured with only  "--no-sandbox", but this post explains other important props when using puppeter from a container: https://www.cloudsavvyit.com/13461/how-to-run-puppeteer-and-headless-chrome-in-a-docker-container/

I would like to have them configured, or at least allow us to configure it, instead of hard coding it

**Comment by rutlabaga** [comment]
We can look into adding configurable properties to be passed in to Puppeteer but it won't be immediately.

I would actually just suggest forking the repo.

Then you can install any repo as a package directly with NPM using the command like:
npm install -g https://github.com/vlocityinc/vlocity_build

So you can easily use your forked repo with just the changes you need in your container.

**Comment by AllanOricil** [comment]
I was able to do what I needed.

**Comment by oxycash** [comment]
@AllanOricil hi Allan, what changes to launch args fixed your issue?

Would mind sharing the details? Like your docker image and the args set?

**Comment by AllanOricil** [comment]
@oxycash this is our image for github actions


````
FROM node:latest

RUN apt-get update -y \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends gnupg apt-utils apt-transport-https curl git openssh-client ca-certificates jq bc gettext xmlstarlet bash python3 libxml2 libxml2-utils \
 && rm -rf /var/lib/apt/lists/*

# add an apt repository of chrome
# google-chrome.list will be overwritten by installing google-chrome-stabe
RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

# install several packages for CI
RUN apt-get update -y \
  && apt-get install -y --no-install-recommends wget gnupg google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
  && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome

COPY dependencies_installer.sh /
COPY package.json /
RUN /dependencies_installer.sh
RUN sfdx plugins:link /usr/local/lib/node_modules/sfdx-git-delta

ENV SFDX_AUTOUPDATE_DISABLE=false
ENV SFDX_JSON_TO_STDOUT=true
ENV SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
ENV SFDX_DOMAIN_RETRY=true
ENV SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true
ENV SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true
ENV SHELL /bin/bash

COPY scripts/ scripts/

RUN echo 'y'
RUN sfdx --version
RUN sfdx plugins --core
RUN vlocity -v
RUN sfdx sgd:source:delta -h

````

**Comment by AllanOricil** [comment]
@oxycash and this is our vlocity deploy configuration file that uses chrome and puppeter to activate our vlocity scripts

````yml
projectPath: .
expansionPath: vlocity
puppeteerHeadless: true
puppeteerExecutablePath: /usr/bin/google-chrome
````

**Comment by AllanOricil** [comment]
@oxycash the `dependencies_installer.sh` script is to allows us to control our dependencies in a package.json in the root of our image repository. This way we can use Dependabot to check if there are new releases for one of the dependencies listed in the package.json.

pacakge.json
````json
{
  "name": "salesforce-build-image",
  "version": "1.0.0",
  "description": "This package controls npm dependencies for this container. It is used by Dependabot to update our dependencies.",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/VodafoneIS/salesforce-build-image.git"
  },
  "author": "allanoricilcos@outlook.com",
  "bugs": {
    "url": "https://github.com/VodafoneIS/salesforce-build-image/issues"
  },
  "homepage": "https://github.com/VodafoneIS/salesforce-build-image#readme",
  "dependencies": {
    "sfdx-cli": "7.132.0",
    "vlocity": "1.14.16",
    "puppeteer": "13.0.1",
    "sfdx-git-delta": "4.12.0"
  }
}
````

dependencies_installer.sh
````
#!/bin/bash

for row in $(cat package.json | jq -c '.dependencies | to_entries | .[]'); do
    name=$(echo $row | jq -r '.key')
    version=$(echo $row | jq -r '.value')
    echo "Installing $name@$version"
    npm install $name@$version -g --unsafe-perm=true --allow-root
done
````

**Comment by oxycash** [comment]
adding exec path to job yml has resolved the issue with chromium launching but now we have tunnel error. we are sure proxy isnt an issue. have you had any such issue?

**Comment by AllanOricil** [comment]
@oxycash no. What vlocity version are you using?

**Comment by oxycash** [comment]
Vlocity Build v1.14.10.

I tried editing the utilityservice.js to pass proxy args for chrome but doesnt seem to work. btw, I am installing chrome separately in addition to puppeteer default and passing that path in job.

**Comment by oxycash** [comment]
> @oxycash Try the way I shared in the comments above. That will surelly work. Then from there you can do whatever you need that is custom

I'll try that, thanks.

I also found that there's a known bug before v1.14.14 which is now fixed. I'll try upgrading first and then test once before i give up on my current model.
