### ISSUE TITLE
Jenkins Git diff problem

### ISSUE THREAD

**Issue by enrique-SFBG** [vlocityinc/vlocity_build#415]
Hi,

We have a problem with the git diff when the tool try to create the delta package, and probably is in our side:

```
09:41:16    SFDX Authenticated - devEnv - ********  
09:41:21    Git Hash >> f835db8f197520ebfe710649f1f50f200fbe0e7c  
09:41:21  fatal: bad object f835db8f197520ebfe710649f1f50f200fbe0e7c
09:41:21    Error Getting Diffs >> Error: Command failed: cd sourcecode/vlocity && git diff --stat f835db8f197520ebfe710649f1f50f200fbe0e7c --raw --no-renames -- .
09:41:21  fatal: bad object f835db8f197520ebfe710649f1f50f200fbe0e7c
```

That git diff error is due to Git not been able to fetching the commit stored in Salesforce Vlocity Custom Metadata Type? You know if we need to fetch the target branch completely? becuase the commit the Tool is searching for is the commit from the last successful deployment, right?

Thank you.

**Comment by rutlabaga** [comment]
Unfortunately we are calling a git command that requires that the old hash be in the git history for the current branch. But you can set the key it uses to check the diffs and make it specific to a single job file:

`gitCheckKey: branch1`

Then you can have multiple branches deployed to the same org. There is no dynamic way to do this as it isn't a variable that can be passed in.
