### ISSUE TITLE
Does it support auth using sfdxUrl like sfdx auth:sfdxurl:store -f authFile.json

### ISSUE THREAD

**Issue by AllanOricil** [vlocityinc/vlocity_build#418]
Does it support auth using sfdxUrl like this sfdx command?

https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_sfdxurl.htm#cli_reference_auth_sfdxurl_store

If yes, how can I do it?

**Comment by rutlabaga** [comment]
You can run that command and then VBT will be able to use that org like any other Salesforce DX Authorized org.
You can find the string that should be in the file by running:

`sfdx force:org:display --verbose -u username@org.com`

The `Sfdx Auth Url` is what goes in the file.
