### ISSUE TITLE
DML errors on deployment after update managed package to 234

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#424]
We were trying to upate vlocity managed package to latest official version 234 (Winter '22 - 234.0.900.444)
Since then we have huge amount of errors on deployment like this: 

> Deploying >> CustomFieldMap/OrderItem>Asset39,CustomFieldMap/OrderItem>Asset4,CustomFieldMap/OrderItem>Asset40,CustomFieldMap/OrderItem>Asset45,CustomFieldMap/OrderItem>Asset46
> Result >> {"Message":"Error Processing: Upsert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, vlocity_cmt.VlocityDataPack: execution of AfterInsert\n\ncaused by: System.DmlException: Update failed. First exception on row 0 with id a5d5E000000SoVjQAK; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 1 records: a5d5E000000SoVjQAK: []\n\n(System Code): []","Status":"Error"} 

I did few tests and it seems that even simple datapacks like field maps which on previous versions were loaded smooth now fail with above issue.

We were in contact with Vlocity specialists on our project and they suggested to add `defaultMaxParallel: 1` to yaml job file. Indeed it mitigated an issue but also made deployment process unacceptable slow.

Raised salesforce ticket #41837051

Due to above issue we reverted the change and stayed on current managed package. For us the new version of managed package is not working with VBT. We are using latest one 1.14.16

**Comment by rutlabaga** [comment]
This should be fixed now in the 1.14.17 release. Please reopen if there are still specific issues.
