### ISSUE TITLE
issues: activate LWC Omniscript component by build tool not working when MFA enabled for user 

### ISSUE THREAD

**Issue by stoevie** [vlocityinc/vlocity_build#427]
Hello, we are implementing Multi Factor Authentication for all our internal SF users so we are compliant with the Salesforce MFA requirements at 1-2-2022. we enabled MFA on the CI/CD user we use for the deployments.

Our deployment process logs in by API. The MFA requirement has no impact when we deploy normal Salesforce and SFI metadata. 
Within the same session we also activate LWC Omniscript components by the Vlocity build tool, version 1.14.17. 

This functionality is not working because the process is using the CI/CD user to access the Salesforce UI and activate the components. At that moment MFA is required and the LWC activation process doesn't reach the UI because it hangs on the MFA screen. This causes the build tool to retry the lwc activation again and again with no succes.

Starting OmniScript LWC Activation >> OmniScript/create_Container_Dutch (a2i4O000000PLpIWAQ)  
  Salesforce Org >> TAContact2  
  Version Info >> v1.14.17 vlocity_cmt 900.437  
  Current Status >> Deploy
  Remaining >> 103
  Success >> 448
  Error >> 5
  Elapsed Time >> 3m 36s
  Migrated 448 items >> Deploying
  Activated >> CalculationProcedure/Create Container Procedure  
  Salesforce Org >> TAContact2  
  Version Info >> v1.14.17 vlocity_cmt 900.437  
  Current Status >> Deploy
  Remaining >> 103
  Success >> 448
  Error >> 5
  Elapsed Time >> 3m 38s
  Migrated 448 items >> Deploying
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 0 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 1 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 2 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 3 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 4 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 5 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 6 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 7 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 8 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 9 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 10 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 11 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 12 of 120  
  OmniScript/create_Container_Dutch >> Loading Page taking too long - Retrying - Tries: 13 of 120  
.....

 What should we do to meet the MFA requirements and still be able to activate the LWC Omniscript components after a deployment?

**Comment by oxycash** [comment]
Is this deployment happening via Docker?

**Comment by stoevie** [comment]
> Is this deployment happening via Docker?

No

**Comment by willianmatheus98** [comment]
The same problem is happening to me, did you found any workaround?

**Comment by jfgarcia268** [comment]
@stoevie If you use OAuth using an SFDX-CLI alias by using "-sfdx.username xxx" rather than the properties file, this should bypass MFA.

**Comment by AllanOricil** [comment]
This one can be solved if you use local compilers
