### ISSUE TITLE
RuleAssignment__c missing for rules assigned to object type

### ISSUE THREAD

**Issue by thvd** [vlocityinc/vlocity_build#447]
RuleAssignment__c records missing in export for rules assigned to object type, like AdjustmentData

Looks like RuleAssignment__c are only retrieved when linked to products.

**Comment by thvd** [comment]
@manas-sf can you please elaborate on why this ticket is closed?

I don't think this problem is fixed already.

**Comment by manas-sf** [comment]
It's designed like this. You may go through https://github.com/vlocityinc/vlocity_build/blob/master/lib/querydefinition.yaml for what is supported and what is not. We do not support AdjustmentData currently.

**Comment by thvd** [comment]
@manas-sf Alright. Can we see this as a feature request then instead?
