### ISSUE TITLE
Would it be possible to standardise output?

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#45]
I have seen you implemented  errors are printed to standard error output now which I really appreciate.

Do you think it would be also possible to standardise output for all actions? E.g. packExport, packDeploy? Now the output is very nice for a human but not very suitable for further machine post processing. It would be great if there was a parameter which would change the output to e.g. json, CSV format.

**Comment by rutlabaga** [comment]
There is a --json argument which will suppress all human readable output and give a standardized response. Small amount of additional details here:

https://github.com/vlocityinc/vlocity_build#cli-api
