### ISSUE TITLE
VBT JSON parser issue

### ISSUE THREAD

**Issue by omgitscurii** [vlocityinc/vlocity_build#458]
VBT is deployed files with a bad JSON structure.

file example:
`
…
  "%vlocity_namespace%__Value__c": "Primary",
        "Name": "NEW_TEF_ATTR_ROUTER_TYPE",
        "VlocityDataPackType": "SObject",
        "VlocityRecordSObjectType": "%vlocity_namespace%__AttributeAssignment__c",
        "VlocityRecordSourceKey": "%vlocity_namespace%__AttributeAssignment__c/03ac840e-9272-dfb4-27c0-0e8f6c6c8ed7",
    },
    {
        "%vlocity_namespace%__AddDate__c": "",
        "%vlocity_namespace%__AttributeAdjustmentComments__c": "",
        "%vlocity_namespace%__AttributeAdjustmentUnits__c": "",
…
`

Notice how the line "...__AttributeAssignment__c/03ac840e-9272-dfb4-27c0-0e8f6c6c8ed7",..." ends with a "," even if it's the last attribute of this JSON object.

This causes deploys to be marked as successful but the file is not deployed.

**Comment by manas-sf** [comment]
Can you file investigation with Salesforce Support providing all details.
