### ISSUE TITLE
Activate LWC Omniscript component by build tool not working when MFA enabled for user

### ISSUE THREAD

**Issue by willianmatheus98** [vlocityinc/vlocity_build#459]
Hi, after MFA activation for all the users, the Omniscript activation is no more working, at the moment I have to activate each one manually because by the tool it takes much time and fails like below

OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 0 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 1 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 2 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 3 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 4 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 5 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 6 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 7 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 8 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 9 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 10 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 11 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 12 of 120
OmniScript/myCustomOmniscript >> Loading Page taking too long - Retrying - Tries: 13 of 120

Is there some workaround for this?

**Comment by jfgarcia268** [comment]
@willianmatheus98 If you use OAuth using an SFDX-CLI alias by using "-sfdx.username xxx" rather than the properties file, this should bypass MFA.

**Comment by willianmatheus98** [comment]
@jfgarcia268 I execute the command as below

`vlocity -sfdx.username sfdx-ci -job vlocity-properties/Deploy_Delta.yaml packDeploy --verbose true --simpleLogging true`
