### ISSUE TITLE
Minimum permissions for packExport?  Error deleting rows from vlocity_ins__VlocityDataPack__c

### ISSUE THREAD

**Issue by tggagne** [vlocityinc/vlocity_build#461]
After downgrading my profile from system administrator, a subsequent `packExport` returned the error, "You do not have permission to delete vlocity_ins__VlocityDataPack__c."

Why would I need to delete rows from `vlocity_ins__VlocityDataPack__c` to do an export?

**Comment by jfgarcia268** [comment]
@tggagne VBT uses Attachments to do Deployments/Exports and vlocity_ins__VlocityDataPack__c is used in that process. It deletes that to save org Space.

**Comment by tggagne** [comment]
@jfgarcia268 , that's helpful.  Thanks.  We can work with that.
