### ISSUE TITLE
VBT Error: Attempt to de-reference a null object 

### ISSUE THREAD

**Issue by saisoma12** [vlocityinc/vlocity_build#465]
I'm trying to migrate promotions from one org to another and getting this error -
Error Message -- Post Process Failed - Message: Attempt to de-reference a null object

I tried including all the dependencies, but still the promotion migration is still failing.
Any help on this would be highly appreciated!

**Comment by jfgarcia268** [comment]
@saisoma12 This needs to be a SF case, you won't get a resolution here.

**Comment by saisoma12** [comment]
@jfgarcia268 - I was able to figure it out, it was an issue with formula fields. JSON files had mappings for few formula fields and I need to take them out to have a successful deployment.
