### ISSUE TITLE
Worrying error about OmniScript compiler

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#467]
Hi,

we are having this worrying error message during deployments on 1.15 `An error occurred while loading OmniScript compiler: Error: Failed to get package '@omnistudio/omniscript-lwc-compiler' Response error 401 Unauthorized ` . It is happening multiple times.

Kindly please make somehow silent, because it is not an error. It should be treated as information that OmniScript compiler is not enabled. And only once please, not every omniscript. Thanks

I feel that having this network roundtrip to try the OmniScript compiler every omniscript might also have little negative impact on performance.

Regards
Paweł Idczak

**Comment by jfgarcia268** [comment]
@pawel-id 
https://github.com/vlocityinc/vlocity_build/pull/471
