### ISSUE TITLE
Git based deploys too extensive logging and repetitions

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#473]
Git changes based deploy sends to standard log output some information on detected changes. Let me show very simple example with one file changed:

```
 Vlocity Build v1.15.3  
  Org >> ORG  
  Using SFDX >> ORG  
  SFDX Authenticated - ORG - cicd@orange.com.navio.int1  
  Git Hash >> fb45e1f40fdd73bb491c8a3306774c0638d29122  
  Git Differences >> :100644 100644 846a76143b... 3e3b0529cd... M	vlo-app/epc-full/Rule/fa1fa529-d74f-c2f7-b05d-f4d9ca98e692/Set-Installment-Plan-values-based-on-Contract-Term-Rule-Order_RuleActions.json
 ...ed-on-Contract-Term-Rule-Order_RuleActions.json | 120 ---------------------
 1 file changed, 120 deletions(-)
  Git Check >> Found Changes for 1 DataPacks [
    "Rule/fa1fa529-d74f-c2f7-b05d-f4d9ca98e692"
]
…
```

We have ‘Git Differences’ section which basically is something like a regular `git diff --name-status hash HEAD` Then we have ‘Git Check’ which shows which datapacks is going to be updated. This is fine unless the amount of changes is small. Now imagine a large project and deployment of a large portion of it. In our case we have 16k files reported line by line by ‘Git Differences’ and c.a. 3.5k datapacks changes reported by ‘Git Check’. This is a huge amount of log, and only 3.5k lines ‘Git Differences’ has an informational value. The former 'Git Differences' could be displayed on demand when needed by anyone having git access.

It happens that sometimes we have an error during VBT deployment. And the VBT has an ability to retry (this is nice). Unfortunately during retrying it is printing again all this Git stuff mentioned above. This is a huge amount of unnecessary information. It can retry few times.
Then running such jobs on cloud environments can cause issues. It is common that a runners has a limit of amount of stdout. Then such a job is failing. Like our case.

Finally we have two kind requests:
1. to stop displaying ‘Git Differences’ by default and have them only in verbose mode. Or some additional switch to enable them.
2. to display Git information only once (don’t repeat them on error retry).

If needed I can send an extensive log with retry and multiple displayed git information.

Regards
Paweł Idczak

**Comment by pawel-id** [comment]
Kindly please consider to limit output of git differences multiple times. In huge Vlocity projects this is really breaking things. Thanks

**Comment by manas-sf** [comment]
It would be great if you can share the logs with us or raise an investigation with Salesforce Support with all the details.

**Comment by pawel-id** [comment]
see ticket Case #43591360 Vlocity Build Tool - huge logging output causing deployment problems
the sample log is attached to the ticket
