### ISSUE TITLE
FlexCard Compilation Error

### ISSUE THREAD

**Issue by lotusboy** [vlocityinc/vlocity_build#475]
Hi,

As part of our vlocity deployment, we have 3 FlexCards which are failing to compile and so cannot subsequently be deployed. Omniscripts are compiling successfully.

Interestingly, if I set lwcCompilerVersion: "890.331", meaning the legacy method is used, the FlexCards get compiled and deployed successfully.

Vlocity Build v1.15.3
Vlocity version 890.331

Log showing the first FlexCard error:
...
  Loading @vlocity-ins/flexcard-compiler@890.331  
  Compiling Flexcard with  FlexCard ID:  >> a6J0E000002GcOkUAK  
  /usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74
            throw new Error("Invalid javascript file " + filePath);
            ^

Error: Invalid javascript file /Users/sloftus/Documents/git/smartchassis/vlocity-temp/plugins/copy-anything/dist/index.cjs
    at PluginVm.load (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74:19)
    at PluginManager.load (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginManager.js:553:24)
    at PluginManager.require (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginManager.js:191:21)
    at PluginVm.sandboxRequire (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:252:33)
    at Object.assign.resolve (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:178:25)
    at /Users/sloftus/Documents/git/smartchassis/vlocity-temp/plugins/less/lib/less/utils.js:8:23
    at /Users/sloftus/Documents/git/smartchassis/vlocity-temp/plugins/less/lib/less/utils.js:127:2
    at Script.runInContext (node:vm:139:12)
    at PluginVm.vmRunScriptInSandbox (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:136:16)
    at PluginVm.load (/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:61:22)  
...

**Comment by depill** [comment]
@lotusboy runtime-plugin-manager-clone looks only for the imports ending with js. copy-anything did ( in my mind an API breaking ) change in 2.0.6 that no longer points to the .js but the cjs. Less depends on it with ^. 

You can manually fix it by copying copy-anything@2.0.1 into the vlocity-temp/plugins folder while waiting for a fix on this.

**Comment by AllanOricil** [comment]
relates: https://github.com/vlocityinc/vlocity_build/issues/486

**Comment by AllanOricil** [comment]
This is where the error is thrown:

https://github.com/davideicardi/live-plugin-manager/blob/master/src/PluginVm.ts#L44-L61

**Comment by centricadean** [comment]
> @lotusboy runtime-plugin-manager-clone looks only for the imports ending with js. copy-anything did ( in my mind an API breaking ) change in 2.0.6 that no longer points to the .js but the cjs. Less depends on it with ^.
> 
> You can manually fix it by copying copy-anything@2.0.1 into the vlocity-temp/plugins folder while waiting for a fix on this.

When we use copy-anything@2.0.1, we get this error:

abort(ReferenceError: sessionStorage is not defined). Build with -s ASSERTIONS=1 for more info.

Anyone else getting this?

**Comment by centricadean** [comment]
Just to add to my above comment, there is an issue in the file: /vlocity-temp/plugins/@omnistudio/flexcard-compiler/src/compiler/flexCardUtility/fetchCustomLabels.js

Lines 8-23 and line 104 mention sessionStorage. If you comment some of those lines out, the compiler will work, although from what I've experienced, the compiler doesn't work well if you're using a Vlocity managed package (vlocity-cmt, vlocity-ins etc)

**Comment by AllanOricil** [comment]
@centricadean use copy-anything@2.0.6. Im using it and I don't get the problem you experienced.
![image](https://user-images.githubusercontent.com/55927613/181225795-033bf9a1-727c-4128-abbc-c4864ba0bca9.png)

**Comment by centricadean** [comment]
> @centricadean use copy-anything@2.0.6. Im using it and I don't get the problem you experienced.
> ![image](https://user-images.githubusercontent.com/55927613/181225795-033bf9a1-727c-4128-abbc-c4864ba0bca9.png)

Is the compiler working on vlocity-cme for you with copy-anything@2.0.6?

**Comment by AllanOricil** [comment]
> > @centricadean use copy-anything@2.0.6. Im using it and I don't get the problem you experienced.
> > ![image](https://user-images.githubusercontent.com/55927613/181225795-033bf9a1-727c-4128-abbc-c4864ba0bca9.png)
> 
> Is the compiler working on vlocity-cme for you with copy-anything@2.0.6? @AllanOricil

Yes, but I had to add this version of copy-anything inside `./vlocity-temp/plugins/`

The flexcard-compiler had a different error and I had to fix it after it was downloaded. Then I also versioned it inside `./vlocity-temp/plugins` so that vlocity-cli doesn't download it again. The issue is that the compiler as is was generating components with namespace `c` instead of `vlocity_cmt`.

**Comment by AllanOricil** [comment]
@centricadean I was also using vlocity-cli@1.15.6

**Comment by centricadean** [comment]
OK will give 2.0.6 a go!

I'm also having an issue with the compiler using namespace c instead of vlocity_cmt. I tried making some changes in the temp folder for the compiler but some components like c:spinner aren't getting compiled as vlocity_cmt-spinner...

#492

**Comment by centricadean** [comment]
@AllanOricil I'm running copy-anything@2.0.6 and I'm getting this error:

```
/usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74
            throw new Error("Invalid javascript file " + filePath);
```

When I downgrade to copy-anything@2.0.1 I get an error to do with sessionStorage in this file:

```
/vlocity-temp/plugins/@vlocity-cme/flexcard-compiler/src/compiler/flexCardUtility/fetchCustomLabels.js
```

Using vlocity@1.15.6 too

**Comment by AllanOricil** [comment]
> @AllanOricil I'm running copy-anything@2.0.6 and I'm getting this error:
> 
> ```
> /usr/local/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74
>             throw new Error("Invalid javascript file " + filePath);
> ```
> 
> When I downgrade to copy-anything@2.0.1 I get an error to do with sessionStorage in this file:
> 
> ```
> /vlocity-temp/plugins/@vlocity-cme/flexcard-compiler/src/compiler/flexCardUtility/fetchCustomLabels.js
> ```
> 
> Using vlocity@1.15.6 too

Inside copy-anything you must ""append"" to their file names `.js`

You have to end up having these files:

index.cjs.js
index.es.js

**Comment by centricadean** [comment]
Thanks @AllanOricil - that works, but then I get the sessionStorage error again. I'm hitting this error when trying to deploy the LWC cart FlexCards which I think use custom labels.

![Uploading Screenshot 2022-07-27 at 1.40.02 pm.png…]()

**Comment by AllanOricil** [comment]
This is possibly a new bug. Could you open an issue describing minimal steps to reproduce this error you are experiencing. This will help people to fix it. I can look at it later. 
Could you also create a custom vlocity component that uses custom labels and see if the same issue happens? Maybe it is not something related to the card component only.

**Comment by centricadean** [comment]
Raised a new issue, will try a custom Vlocity component with custom labels shortly

**Comment by KevinGossentCap** [comment]
Hi @AllanOricil You should look and read back the subject of this ticket.
It's all about localCompile, the feature proposed since 1 year ago and that is still struggling to work on vlocity component themselves.
To make it clearer, here is more of my log where we see clearly that it is the VBT process locally compiling the vlocityCard which is giving the ERROR. And what I ask is "how can we have trust/faith in what's deployed if the job creating what's deployed return such an error

  Loading @vlocity-cme/omniscript-lwc-compiler@latest
  Starting OmniScript LWC Compilation >> OmniScript/CPQ_cartConfigurator_Multi-Language (a336S000003FaBbQAK)
  Retrieving OmniScript definition
  Compiling OmniScript LWC Component
Specified path does not exist. Creating it now...
  LWC for FlexCard will be compiled at the end >> VlocityCard/cpqProductTileList
  Salesforce Org >> sfi_esm_win23
  Version Info >> v1.16.1 vlocity_cmt 900.468
  Current Status >> Deploy
  Remaining >> 0
  Success >> 2
  Error >> 0
  Elapsed Time >> 1m 4s
  Migrated 2 items >> Deploying
  Loading @vlocity-cme/flexcard-compiler@latest
  Compiling Flexcard with  FlexCard ID:  >> a5a6S000007JdoAQAS
APEX_ERROR: System.LimitException: JSON string exceeds heap size limit

(System Code)
    at HttpApi.getError (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:250:13)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:37:12)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:123:15
    at flush (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\asap\raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errorCode: 'APEX_ERROR'
}
Specified path does not exist. Creating it now...
  Deploying generated LWC components
  Using salesforce-alm
  Running source:convert
Source was successfully converted to Metadata API format and written to the location: C:\GitRepos\HubOne\defaultEmpty_CPQ_LWC_240\vlocity-temp\mdapi
  source:convert ended successfully
  Running mdapi:deploy
Job ID | 0Af6S00000pzrnxSAA
MDAPI PROGRESS | ████████████████████████████████████████ | 2/2 Components
  mdapi:deploy ended successfully
  Metadata Deployed >> LightningComponentBundle/cPQCartConfiguratorMultiLanguage
  Metadata Deployed >> LightningComponentBundle/cfCpqProductTileList
  Finalizing Deployment
  Salesforce Org >> sfi_esm_win23
  Version Info >> v1.16.1 vlocity_cmt 900.468
  Current Status >> Deploy
  Remaining >> 0
  Success >> 4
  Error >> 0
  Elapsed Time >> 3m 1s
  Migrated 4 items >> Deploying
  Job Complete >> Deploy 3m 1s
Deploy success:
4 Completed

**Comment by AllanOricil** [comment]
@KevinGossentCap would you be able to zip this flexicard datapack and paste it here. I need to use it to debug the compiler. The error message does not help much to determine the root cause of the problem.

**Comment by KevinGossentCap** [comment]
> @KevinGossentCap would you be able to zip this flexicard datapack and paste it here. I need to use it to debug the compiler. The error message does not help much to determine the root cause of the problem.

Hi @AllanOricil they are both from "industry CPQ LWC" static ressources. So both provided directly by vlocity/Salesforce.
I find it hard to believe they "fixed" the "sessionStorage" error without testing that there was no other error hidden by the first one...

**Comment by KevinGossentCap** [comment]
> @KevinGossentCap could you also run vlocity cli again but with `--verbose`
> 
> ![image](https://user-images.githubusercontent.com/55927613/204589316-17635341-fcbd-4665-b2aa-f9b066f93862.png)
> 
> I'm almost certain it won't show the errors I need because the compiler has its verbose prop hardcoded to `false`, but let's give it a try.
> 
> ![image](https://user-images.githubusercontent.com/55927613/204589695-cd11baaf-7dd6-4dc8-8ffd-b3d988fedb95.png)
> 
> My guess is that one of these custom rest services is causing that system limit exception
> 
> ![image](https://user-images.githubusercontent.com/55927613/204590332-4e241c45-6894-4939-81c4-d30885202d59.png)
> 
> Could you also open your debug logs and try to identify which apex method throws this exception while the compiler is running `APEX_ERROR: System.LimitException: JSON string exceeds heap size limit`

Hi again,
I tested verbose and not much additional information, either on screen or logfile.
On screen I only have an additional information (the Result json I'll paste at the end of this answer).
In the log I have nothing at all (not even the APEX error)

Here for the verbose output giving the additional result json and still the APEX error:
`  LWC for FlexCard will be compiled at the end >> VlocityCard/cpqProductTileList
  Result >> {"Status":"Deleted","VlocityDataPackId":"a5d6S000001Eg9zQAC"}
  Salesforce Org >> sfi_esm_win23
  Version Info >> v1.16.1 vlocity_cmt 900.468
  Log File >> vlocity-temp\logs\vlocity-YAML-CPQ_LWC_3_test-yaml-2022-11-30T07-42-56-768Z-Deploy.yaml
  Current Status >> Deploy
  Remaining >> 0
  Success >> 2
  Error >> 0
  Elapsed Time >> 0m 53s
  Migrated 2 items >> Deploying
  Saving File Start
  Saving File End >> 119
  Checking Valid Imports Start
  Get Package Version
  Loading @vlocity-cme/flexcard-compiler@latest
  Compiling Flexcard with  FlexCard ID:  >> a5a6S000007JdoAQAS
APEX_ERROR: System.LimitException: JSON string exceeds heap size limit

(System Code)
    at HttpApi.getError (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:250:13)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:37:12)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:123:15
    at flush (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\asap\raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errorCode: 'APEX_ERROR'
}
Specified path does not exist. Creating it now...
  Deploying generated LWC components
  Using salesforce-alm
  Running source:convert
Using resolved username kevin.gossent-0586686738@industryapps.com from alias sfi_esm_win23`

**Comment by AllanOricil** [comment]
@KevinGossentCap this does not help. I don't have means to repro your error, so Im going to guide you so that we can at least discover which apex code is causing this exception you are seeing. 

Do you know where the`flexcard-compiler` package is located, right? If not, it is in the root of your sfdx project, in the following dir `vlocity-temp/plugins/@vlocity-cme/flxcard-compiler`

Could you override a function called `executeMethod` in `vlocity-temp/plugins/@vlocity-cme/flxcard-compiler/src/compiler/flexCardUtils/api.js` using the one I pasted below.


````js
function executeMethod(methodName, inputMap, params) {
  const data = {
    sClassName: _namespaceDotNotation + "FlexCardCompiler",
    sMethodName: methodName,
    input: inputMap ? JSON.stringify(inputMap) : "{}",
    options: inputMap ? JSON.stringify(inputMap) : "{}",
    ...params
  };

  console.log('executeMethod data');
  console.log(JSON.stringify(data));

  let url = `${_namespaceSlashNotation}/v1/GenericInvoke/`;
  
  if (_connection) {
    return _connection.apex.post(url, data, (err, res) => {
      if (err) {
        console.log(`Error while executing: ${methodName}`);
        return console.error(err);
      }
      return res;
    });
  }

  return Promise.reject(
    "Connection not set. Please do so using setApi method."
  );
}
````

Then run the cli again and see if it prints more error messages.

**Comment by KevinGossentCap** [comment]
Hi @AllanOricil , here is the new output
```
  Loading @vlocity-cme/flexcard-compiler@latest
  Compiling Flexcard with  FlexCard ID:  >> a5a6S000007JdoAQAS
executeMethod data
{"sClassName":"vlocity_cmt.FlexCardCompiler","sMethodName":"getAllCardsByRecordType","input":"{\"recordType\":\"Flex\"}","options":"{\"recordType\":\"Flex\"}"}
executeMethod data
{"sClassName":"vlocity_cmt.FlexCardCompiler","sMethodName":"getLWCBundles","input":"{\"nextRecordsUrl\":\"\"}","options":"{\"nextRecordsUrl\":\"\"}"}
executeMethod data
{"sClassName":"vlocity_cmt.FlexCardCompiler","sMethodName":"getUserProfile","input":"{}","options":"{}"}
Error while executing: getAllCardsByRecordType
APEX_ERROR: System.LimitException: JSON string exceeds heap size limit

(System Code)
    at HttpApi.getError (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:250:13)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:37:12)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:123:15
    at flush (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\asap\raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errorCode: 'APEX_ERROR'
}
executeMethod data
{"sClassName":"vlocity_cmt.FlexCardCompiler","sMethodName":"getCustomLabels","input":"{\"customLabels\":[\"CPQSeeDetailsLabel\",\"CPQPriceLabel\",\"OneTime\",\"Recurring\",\"CPQAddToCart\",\"CPQConfigure\",\"CPQOneTimeLabel\"]}","options":"{\"customLabels\":[\"CPQSeeDetailsLabel\",\"CPQPriceLabel\",\"OneTime\",\"Recurring\",\"CPQAddToCart\",\"CPQConfigure\",\"CPQOneTimeLabel\"]}"}
executeMethod data
{"sClassName":"vlocity_cmt.FlexCardCompiler","sMethodName":"upsertAttachment","input":"{\"sParentId\":\"a5a6S000007JdoAQAS\",\"sAttName\":\"a5a6S000007JdoAQAS.css\",\"sContent\":\"\",\"bEncoded\":false}","options":"{\"sParentId\":\"a5a6S000007JdoAQAS\",\"sAttName\":\"a5a6S000007JdoAQAS.css\",\"sContent\":\"\",\"bEncoded\":false}"}
Specified path does not exist. Creating it now...
  Deploying generated LWC components
  Using salesforce-alm
  Running source:convert
Using resolved username kevin.gossent-0586686738@industryapps.com from alias sfi_esm_win23
```

**Comment by AllanOricil** [comment]
Now we can open a ticket to vlocity so that they can fix that apex method that is failing. 😄

**Comment by centricadean** [comment]
Hi @KevinGossentCap and @AllanOricill, the issue with the Apex class is due to be fixed in the next patch (240.9) which is due to be released around 9 December.

**Comment by KevinGossentCap** [comment]
@centricadean @AllanOricil I've just tested again with 240.10
Still the same error....... (I expect the class to be corrected, not a component change to take back from industry CPQ LWC in the static ressources)

**Comment by KevinGossentCap** [comment]
@AllanOricil nothing changed at all, same errror in the same class (I had to add back the console logs to see that)
```
  Loading @vlocity-cme/flexcard-compiler@latest
  Compiling Flexcard with  FlexCard ID:  >> a5a6S000007JdoAQAS
Error while executing: getAllCardsByRecordType
{"sClassName":"vlocity_cmt.FlexCardCompiler","sMethodName":"getAllCardsByRecordType","input":"{\"recordType\":\"Flex\"}","options":"{\"recordType\":\"Flex\"}"}
APEX_ERROR: System.LimitException: JSON string exceeds heap size limit

(System Code)
    at HttpApi.getError (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:250:13)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:37:12)
    at C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\promise\lib\core.js:123:15
    at flush (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\node_modules\asap\raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errorCode: 'APEX_ERROR'
}
```

**Comment by AllanOricil** [comment]
@KevinGossentCap but what did you say about the static resouces? I did not get it at all

**Comment by KevinGossentCap** [comment]
> My remark was that I did not go through taking back vlocity provided static ressources that gives us the components I'm using to test the localCompile. they are part of vlocity industry CPQ LWC (and ESM).
> As the error was an APEX error, I expected as said by @centricadean that they'd fix the Apex class.

I edited my post to give the answer for that part

My remark was that I did not go through taking back vlocity provided static ressources that gives us the components I'm using to test the localCompile. they are part of vlocity industry CPQ LWC (and ESM).
As the error was an APEX error, I expected as said by @centricadean that they'd fix the Apex class.

**Comment by AllanOricil** [comment]
@KevinGossentCap is the deployment ok, even with this error? I mean, are u able to see all your flexicarda in your sandbox?

**Comment by KevinGossentCap** [comment]
@AllanOricil The salesforce deployment is successfull, but no way to be sure it's 100% produced as expected for the moment.
When not overloaded, I'll maybe try to force myself to retrieve both localcompile and pupetteer versions to compare them...

**Comment by KevinGossentCap** [comment]
@AllanOricil @centricadean I can confirm that the localCompile one is different from the pupetteer one...
![image](https://user-images.githubusercontent.com/20575643/208103623-70944206-6bba-4dab-9b6b-a901c98b3d7e.png)
![image](https://user-images.githubusercontent.com/20575643/208103672-e6cc8c6c-ec4c-4e46-9c06-e38bcf3d69a1.png)
![image](https://user-images.githubusercontent.com/20575643/208103711-173e51e0-b3c7-45a2-a907-aebf2a4f7af8.png)
![image](https://user-images.githubusercontent.com/20575643/208103762-55184f9e-75e7-4a69-8e66-5ac4fd140727.png)

**Comment by AllanOricil** [comment]
@KevinGossentCap this is a known issue. They are probably working on fixing it.

**Comment by thvd** [comment]
Can confirm the same. Logged case with ID: Case #43776753.

**Comment by centricadean** [comment]
Yep sadly this issue is not fixed in 240.9. I have a case open and they're saying it will be fixed in 240.11. I won't hold my breath though. Please do raise cases and raise this as an issue as I'm sure a case from each customer will help push Salesforce to rethink their testing practices before releasing and getting our hopes up.

**Comment by KevinGossentCap** [comment]
Hi @centricadean @AllanOricil @manas-sf , I've just tested with latest VBT and latest winter 23 patch (240.11).
Some of the more blocking errors are solved **BUT** there is a more problematic resulting issue now
- Apex error not there anymore
- localCompiled LWC are not the same as browser compile LWC

You can easily test using the SFI provided industry CPQ LWC.
The LWC are not exactly the same. There is even one that is so different that it doesn't even deploy...

**Comment by centricadean** [comment]
> Hi @centricadean @AllanOricil @manas-sf , I've just tested with latest VBT and latest winter 23 patch (240.11). Some of the more blocking errors are solved **BUT** there is a more problematic resulting issue now
> 
> * Apex error not there anymore
> * localCompiled LWC are not the same as browser compile LWC
> 
> You can easily test using the SFI provided industry CPQ LWC. The LWC are not exactly the same. There is even one that is so different that it doesn't even deploy...

Yep, sadly there are still issues with the local compiler. If you compile a Multi-Language FlexCard, then the labels aren't generated and just display as {Label.xxx} when you render the LWC.

I have no more updates from Salesforce on this. The saga continues...

**Comment by manas-sf** [comment]
Thanks for the feedback. We have Case#35690448 with FlexCard team and they looking into it.

**Comment by centricadean** [comment]
@manas-sf there is also Case #43894399

**Comment by thvd** [comment]
@manas-sf and there is also case #43776753. Already closed, but not solved.

**Comment by thvd** [comment]
Does anyone already run with 242? I have been told (tentative/safe harbour/...) it should have been solved in 242. 
Did anyone test already?

**Comment by pawel-id** [comment]
I would rephrase @thvd question: does anyone use local compilation? On which version if possible?

Reading this thread makes the impression that it just doesn’t work. I’m desperately searching for this possibility. We have huge Vlocity project (hundreds omniscripts, flex cards, etc). Currently we are on Spring’22 (900.456).  In our case full deployment of just this Vlocity part takes 3-4 hours. And most of the deployment time it is compilation and activation of LWC stuff via puppeteer. Moreover it is very vulnerable to all network and Salesforce instabilities. Then it fails frequently. With growing project size we are approaching the moment where we won’t be able to deploy Vlocity at all. Then local compilation could solve the problem, but does it really work? Anyone?

**Comment by thvd** [comment]
Currently it works for us. Latest version of everything. Works ok. As long
as the repository isn't down. Will try to list exact version numbers Monday.

Op za 4 mrt. 2023 16:58 schreef Paweł Idczak ***@***.***>:

**Comment by KevinGossentCap** [comment]
Not completely sure if it works as, if I follow my shared procedure
- asking an ESM trial ORG
- getting the industry CPQ LWC ressources
- unzipping etc
- launching deploy with everything and localCompile
We can see that there are **A LOT** of LWC not produced.
To really test, I'll have to produce a clean sandbox, full manually install vlocity managed package and then full manually do all CPQ LWC + ESM steps and then compare between trial ORG and produced sandbox...

**Comment by KevinGossentCap** [comment]
Replying to myself, it still violently crashes when trying to use it for initial vlocity CME industry CPQ LWC deployment...

**Comment by KevinGossentCap** [comment]
To sum it up
- localCompile of industry CPQ LWC **OmniScript** crashes (there are only 18 of them...)
- localCompile of industry CPQ LWC **VlocityCard** seem to create the LWCs (141 of them) but
  - if you let default "useSfdxCli: false" you get an very ugly saas error like months ago
  - if you specify "useSfdxCli: true" then it can't interpret or launch the convert do mdapi correctly and crashes
  - if you take the locally produced LWCs to manually convert them it works
  - if you deploy them afterwards the deployment is miraculously working (I'm yet to try comparing between locally compiled and browser compile for some of the LWCs... takes some time)

**Comment by AllanOricil** [comment]
@KevinGossentCap can you share the repository and the sfdx cli you used when you set "useSfdxCli" to true?

**Comment by KevinGossentCap** [comment]
@AllanOricil 

- I used a SFDC spring23 sandbox without SFI
- made the pre-install steps
- installed latest vlocity CME (242.6.900.480) and followed post-install steps
- components are directly taken from managed package static resources (if you only want to know where to find them here is the sub-guide https://help.salesforce.com/s/articleView?id=ind.comms_copy_datapacks_to_migrate_3.htm&language=en_US&type=5)
- my personal SFDX-CLI version is latest-rc so 7.191.3 (but it was the same I think with previous ones)
- my personal vlocity CLI version is latest so 1.17.1

**Comment by AllanOricil** [comment]
> @AllanOricil 
> 
> - I used a SFDC spring23 sandbox without SFI
> - made the pre-install steps
> - installed latest vlocity CME (242.6.900.480) and followed post-install steps
> - components are directly taken from managed package static resources (if you only want to know where to find them here is the sub-guide https://help.salesforce.com/s/articleView?id=ind.comms_copy_datapacks_to_migrate_3.htm&language=en_US&type=5)
> - my personal SFDX-CLI version is latest-rc so 7.191.3 (but it was the same I think with previous ones)
> - my personal vlocity CLI version is latest so 1.17.1

Could you share the error message u see when "useSfdxCli=true". I need information to determine why the metadata convertion step fails when running the sfdx command inside vlocity_build, but not when you manually convert it.

**Comment by KevinGossentCap** [comment]
I ran the command with verbose option (just in case)
```
Compiling Flexcard with  FlexCard ID:  >> a7s7Z0000008n0OQAQ
Specified path does not exist. Creating it now...
  Deploying generated LWC components
  Using sfdx cli
  Running source:convert
  Error: Error parsing stdout
    at _run (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\sfdx.js:11:9)
    at _sourceConvert (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\sfdx.js:28:9)
    at run (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\sfdx.js:37:10)
    at DataPacksJob.deployJob (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\datapacksjob.js:2796:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataPacksJob.doRunJob (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\datapacksjob.js:339:9)
    at async DataPacksJob.runJobWithInfo (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\datapacksjob.js:293:9)
    at async DataPacksJob.runJob (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\datapacksjob.js:95:26)
    at async Vlocity.runDataPacksCommand (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\vlocity.js:173:16)
    at async VlocityCLI.runJob (C:\KGO_Tools\node-v18-win-x64\node_modules\vlocity\lib\vlocitycli.js:725:12)
  Saving File Start
  Saving File End >> 149```

**Comment by KevinGossentCap** [comment]
@AllanOricil One information is that it's been 1 or 2 weekly release of SFDX-CLI that salesforce-alm is not used or present anymore.
That might be it.
Maybe the right time to try not pointing to package but only pure commands or the SFDX-CLI API

**Comment by AllanOricil** [comment]
@KevinGossentCap could you please run this command. 


`FORCE_COLOR=0 sfdx force:source:convert --rootdir "${rootdir}" --outputdir "${outputdir}" --json`


`rootdir` has to be the temp directory where your flexicard lwcs are. The lwc are probably in the vloctiy_tmp dir that is located in the root of ur sfdx project.

`outputdir` can be anywhere you want to save the output.

Save the output of this command to a file a post it here, please.

**Comment by KevinGossentCap** [comment]
Here it is, as I suspected
`
 ~#@❯  FORCE_COLOR=0 sfdx force source convert -d .\vlocity-temp\mdapi2\ -r .\vlocity-temp\tempDeployLWC\salesforce_sfdx\ --json                                                                                                                                                                   ❮  9m 38s 858ms   
FORCE_COLOR=0: The term 'FORCE_COLOR=0' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
`

**Comment by KevinGossentCap** [comment]
@AllanOricil you'll have to make it more generic with getting if env var exists, and if yes save back the value, then set your value, then put back the initial status of the env var

**Comment by AllanOricil** [comment]
> Here it is, as I suspected
> ```
>  ~#@❯  FORCE_COLOR=0 sfdx force source convert -d .\vlocity-temp\mdapi2\ -r .\vlocity-temp\tempDeployLWC\salesforce_sfdx\ --json                                                                                                                                                                   ❮  9m 38s 858ms   
> FORCE_COLOR=0: The term 'FORCE_COLOR=0' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> ```

@KevinGossentCap that might be the reason for you issue. I recommend you run vlocity on a container image based on Linux until that is fixed.

**Comment by KevinGossentCap** [comment]
@AllanOricil no can do. for many security policy reasons it's not an option.
We have to maintain windows OS compatibility for the CLI

**Comment by AllanOricil** [comment]
> @AllanOricil no can do. for many security policy reasons it's not an option.
> We have to maintain windows OS compatibility for the CLI

@KevinGossentCap 
I will see if I can open a PR. But it won't be released sooner. You can open the file where the error is thrown in your computer (the error message displays exactly which file throws the exception), then remove that FORCE_COLOR parameter from the _run function. After that, run vlocity build again, and post the output here.

**Comment by KevinGossentCap** [comment]
I think we can make it work as it should with this kind of inspiration : https://stackoverflow.com/questions/58805784/node-js-how-to-pass-environment-variables-with-a-shell-command
especially with the answer to help : https://stackoverflow.com/posts/58806874/revisions

**Comment by AllanOricil** [comment]
It is time for implementing integration tests with the following inputs to avoid these little mistakes

- node 14 and 16
- sfdx latest, rc, previous versions
- os: Darwin, Linux, windows
- few job file samples
