### ISSUE TITLE
Getting error while performing Promition migrations via the vlocityBuildTool are failing

### ISSUE THREAD

**Issue by padlakha** [vlocityinc/vlocity_build#48]
Getting error while performing Promition migrations via the vlocityBuildTool are failing

SASS Compilation Error VlocityUITemplate/cpq-cart-item-child-products1 Failed to compile SCSS: example_vlocity_build/VlocityUITemplate/cpq-cart-item-child-products1/cpq-cart-item-child-products1.scss SASS compilation failed, see error message for details: Error: no mixin named cpqProductChildLevelStyling

       Backtrace:
        /stdin:234
        on line 234 of /stdin
>>     @include cpqProductChildLevelStyling();
   -------------^

ContextDimension/714e3128-7844-3115-0bfd-abcca344a640 -- TvTplusnFunction -- Error Message -- No match found for vlocity_cmt__ContextMappingArgument__c.vlocity_cmt__ContextMappingId__c - uniqueId=VlocityRecordSourceKey:a8c7E000001xNHgQAM (vlocity_cmt)
VlocityStateModel/Contract State Model -- Contract State Model -- Error Message -- Only one state model can exist with the same Type Field Name and Type Field Value for Contract. State Model name has to be unique.

Product2/2811d309-e10c-b91e-477a-a1038cc3474f -- SjÃ³nvarpsÃ¾jÃ³nusta SÃ­mans -- Error Message -- No match found for vlocity_cmt__OverrideDefinition__c.vlocity_cmt__OverridingAttributeAssignmentId__c - vlocity_cmt__AttributeId__r.vlocity_cmt__Code__c=SM-ATTR-TP AND vlocity_cmt__IsOverride__c=true AND vlocity_cmt__ObjectId__c=01t9E000002armmQAA (vlocity_cmt)
Product2/74943bf2-25c5-c049-988a-9c924fd41386 -- Endalaust internet -- Error Message -- Duplicate child product cannot be selected
Product2/adac7afa-f741-80dd-9a69-f8a5aa61eb56 -- GrunnÃ¡skrift HeildsÃ¶lusjÃ³nvarps -- Error Message -- Product you are trying to add is missing a Pricebook Entry in pricebook >>B2C Price Book<< Please add product to pricebook and tryagain.
Product2/f8b0bc37-b6eb-49c0-2b4e-76d6870cc383 -- Endalausar mÃ­nÃºtur -- Error Message -- Duplicate child product cannot be selected
Promotion/0db795ae-59f9-6e8e-6334-7cbf21e67d23 -- XTrial SjÃ³nvarp SÃ­mans for 1 Month -- Error Message -- No match found for vlocity_cmt__OverrideDefinition__c.vlocity_cmt__OverridingAttributeAssignmentId__c - vlocity_cmt__AttributeId__r.vlocity_cmt__Code__c=SM-ATTR-TPV AND vlocity_cmt__IsOverride__c=true AND vlocity_cmt__ObjectId__c=01t9E000002armrQAA (vlocity_cmt)
Rule/All Relationships Rule -- All Relationships Rule -- Error Message -- No match found for vlocity_cmt__RuleAction__c.vlocity_cmt__ProductRelationshipId__c - vlocity_cmt__GlobalKey__c=20ea89ed-83bb-2e89-3c7c-5987baa3745b (vlocity_cmt)
Promotion/249cefd8-88f4-6783-be83-b0998e8bd73d -- GÃ³Ã° byrjun for Standard TV -- Error Message -- No match found for vlocity_cmt__OverrideDefinition__c.vlocity_cmt__OverridingAttributeAssignmentId__c - vlocity_cmt__AttributeId__r.vlocity_cmt__Code__c=SM-ATTR-TPV AND

**Comment by padlakha** [comment]
Promotion/0db795ae-59f9-6e8e-6334-7cbf21e67d23 -- XTrial Sjónvarp Símans for 1 Month -- Error Message -- insufficient access rights on cross-reference id: a5Y7E000000uxAj 
Promotion/249cefd8-88f4-6783-be83-b0998e8bd73d -- Góð byrjun for Standard TV -- Error Message -- insufficient access rights on cross-reference id: a5Y7E000000uxDi 
Promotion/26532257-1647-6321-5a6a-c7fa0fe5e8a6 -- XTrial Heimur - Evrópa for 1 Month -- Error Message -- insufficient access rights on cross-reference id: a5Y7E000000ux3x 
Promotion/26611a54-4b21-e4f5-e461-4396ff14fd4c -- XComp Heimur - Evrópa for 2 Month -- Error Message -- insufficient access rights on cross-reference id: a5Y7E000000uxBS 
Promotion/28b60626-284f-9620-191c-dc912b09c8bf -- XComp Heimur - Grunnur for 1 Months -- Error Message -- insufficient access rights on cross-reference id: a5Y7E000000ux71

**Comment by rutlabaga** [comment]
What type are those Ids?

**Comment by padlakha** [comment]
They are promotion IDs

**Comment by siminn-svavarhall** [comment]
Actually those are Compiled Attribute Override Id's. Those override objects are available on the source org but not on the target.

**Comment by rutlabaga** [comment]
This issue was just fixed yesterday. Please pull the latest and run packUpdateSettings before deploying.

**Comment by siminn-svavarhall** [comment]
Confirmed, all promotions are migrated now
