### ISSUE TITLE
Error Activating LWC - ERROR: Missing id query parameter

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#481]
From version 1.15.4 we are observing previously unseen intermittent issues with omniscript activation. Samples:

```
  Activated >> OmniScript/quote_clone_English  
  OmniScript LWC Activation Error >> OmniScript/quote_clone_English -  Error Activating LWC - ERROR: Missing id query parameter  
  Deactivating OmniScript  >> a337a000000ULDvAAO OmniScript was deactivated  
```

```
  Activated >> OmniScript/Order_assignBillingAccount_English  
  OmniScript LWC Activation Error >> OmniScript/Order_assignBillingAccount_English -  Error Activating LWC - ERROR: Missing id query parameter  
  Deactivating OmniScript  >> a335r0000009gdDAAQ OmniScript was deactivated  
  ```
  
  The deployment is failing at the end.

**Comment by rutlabaga** [comment]
I have added a fix that should prevent the OmniScript Id from ever being null when being activated in v1.15.5 but...

This is a surprising error message. Can you run with Verbose and see what the URL it prints is? 

It should be like:
`LWC Activation URL >> https://demoorg.my.salesforce.com/apex/omnistudio__OmniLwcCompile?id=0jN5f000000XbsrEAC&activate=true`

I am unable to reproduce that specific error without removing `id=0jN5f000000XbsrEAC&` which I am not sure how it is generating a URL without id as part of the code. If you still receive the error after 15.5 then please update and we will continue to look into it.

**Comment by pawel-id** [comment]
This problem is quite rare, but happening (including latest build). Please find a sample from our logs:

```
  Version Info >> v1.15.6 vlocity_cmt 900.456 
  ...
  ...
  Deploying OmniScript using legacy method... Local compiler disabled  
  Activated >> OmniScript/MACD_orderBlankSim_English  
  Activating LWC for OmniScript >> OmniScript/Contract_createFrameContract_English (a335r000000IH4kAAG) ERROR: Missing id query parameter  
  Elapsed Time >> 18m 59s  
  LWC Activation Error >> OmniScript/Contract_createFrameContract_English -  Error Activating LWC - ERROR: Missing id query parameter  
  Activating LWC for OmniScript >> OmniScript/selfServiceProcess_activationDeactivationStolenBarrings_English (a335r000000IH3dAAG) ACTIVATING...  
  Elapsed Time >> 18m 59s  
  Activating LWC for OmniScript >> OmniScript/internalCase_configureSubstitutionForMyWallet_English (a335r000000IH3XAAW) ACTIVATING...  
  Elapsed Time >> 18m 59s  
  Deactivating OmniScript  >> a335r000000IH4kAAG OmniScript was deactivated  
```

**Comment by pawel-id** [comment]
@agarcia-sf thank you, this is not happening
