### ISSUE TITLE
Failed to get package '@vlocity-ins/flexcard-compiler' Response error 401 Unauthorized 

### ISSUE THREAD

**Issue by tggagne** [vlocityinc/vlocity_build#485]
Depoying a single flexcard to our production org, I receive an error:

```
Loading @vlocity-ins/flexcard-compiler@890.333
An error occurred while loading OmniScript compiler: Error: Failed to get package '@vlocity-ins/flexcard-compiler' Response error 401 Unauthorized 
```

Ultimately, the card activates, but now I'm worried what I'm missing that might be broken or un-generated because of the 401.

I deploy it using
`vlocity packDeploy -job now.yaml -sfdx.username alias`

here's the yaml

```
projectPath: ./force-app/main/default/
expansionPath: vlocity
ignoreDependencies: true
maxDepth: 1
manifestOnly: true
manifest:
    - VlocityCard/PolicyRecordActions
```

**Comment by calvinle1** [comment]
@tggagne I believe you need to obtain an NPM key, see: https://github.com/vlocityinc/vlocity_build#initial-support-for-omniscript--flexcards-local-compilation

**Comment by tggagne** [comment]
I got the NPM key and the local compilation of omniscripts is great.  The output included missing LWCs that we wouldn't otherwise have found without tripping over the inactive OS and debugging why it wouldn't activate.

Now, we just have the issue with compiling flexcards which I understand is being discussed elsewhere.
