### ISSUE TITLE
Flex Card Compiler not working - throw new Error("Invalid javascript file " + filePath);

### ISSUE THREAD

**Issue by AllanOricil** [vlocityinc/vlocity_build#486]
The following issue only happens in our CICD build when using this vlocity cli

![image](https://user-images.githubusercontent.com/55927613/178515370-3d6d67ee-98b3-4e84-b252-4fad2e97baef.png)

this is how we configured our job file
![image](https://user-images.githubusercontent.com/55927613/178515554-05e7e761-7996-484a-ba43-2d171ca802c2.png)

and this is a picture that shows we have `flexcard-compiler@900.458.0` available in our repository
![image](https://user-images.githubusercontent.com/55927613/178515647-a1621dc5-83d2-4416-8e90-8fe908ed9774.png)

So, what could be the problem? None of our flex cards are compiling using this cli.

Below is the output I captured from my github actions logs

[flexcard-compilation-error-900.458.0.log](https://github.com/vlocityinc/vlocity_build/files/9094040/flexcard-compilation-error-900.458.0.log)

**Comment by pawel-id** [comment]
Tried today for the first local compilation and got very same error. If this issue is closed there must be a fix or workaround which I missed. Can anyone help?

```
  Compiling Flexcard with  FlexCard ID:  >> a5c7a000000c9n5AAA  
  /Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74
            throw new Error("Invalid javascript file " + filePath);
            ^

Error: Invalid javascript file /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/copy-anything/dist/index.cjs
    at PluginVm.load (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74:19)
    at PluginManager.load (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginManager.js:553:24)
    at PluginManager.require (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginManager.js:191:21)
    at PluginVm.sandboxRequire (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:252:33)
    at Object.assign.resolve (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:178:25)
    at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/utils.js:8:23
    at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/utils.js:127:2
    at Script.runInContext (node:vm:141:12)
    at PluginVm.vmRunScriptInSandbox (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:136:16)
    at PluginVm.load (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:61:22)
    at PluginVm.sandboxRequire (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:240:25)
    at Object.assign.resolve (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:178:25)
    at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/less-error.js:5:34
    at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/less-error.js:146:2
    at Script.runInContext (node:vm:141:12)
    at PluginVm.vmRunScriptInSandbox (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:136:16) 
```

I'm using latest VBT 1.16.3 and following setup:

```
lwcCompilerVersion: '900.456'
useSfdxCli: true
```

**Comment by centricadean** [comment]
> Tried today for the first local compilation and got very same error. If this issue is closed there must be a fix or workaround which I missed. Can anyone help?
> 
> ```
>   Compiling Flexcard with  FlexCard ID:  >> a5c7a000000c9n5AAA  
>   /Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74
>             throw new Error("Invalid javascript file " + filePath);
>             ^
> 
> Error: Invalid javascript file /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/copy-anything/dist/index.cjs
>     at PluginVm.load (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:74:19)
>     at PluginManager.load (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginManager.js:553:24)
>     at PluginManager.require (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginManager.js:191:21)
>     at PluginVm.sandboxRequire (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:252:33)
>     at Object.assign.resolve (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:178:25)
>     at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/utils.js:8:23
>     at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/utils.js:127:2
>     at Script.runInContext (node:vm:141:12)
>     at PluginVm.vmRunScriptInSandbox (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:136:16)
>     at PluginVm.load (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:61:22)
>     at PluginVm.sandboxRequire (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:240:25)
>     at Object.assign.resolve (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:178:25)
>     at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/less-error.js:5:34
>     at /Users/pawel/wrk/spartakus/navio/navio/vlocity-temp/plugins/less/lib/less/less-error.js:146:2
>     at Script.runInContext (node:vm:141:12)
>     at PluginVm.vmRunScriptInSandbox (/Users/pawel/.nvm/versions/node/v18.14.0/lib/node_modules/vlocity/node_modules/runtime-plugin-manager-clone/dist/src/PluginVm.js:136:16) 
> ```
> 
> I'm using latest VBT 1.16.3 and following setup:
> 
> ```
> lwcCompilerVersion: '900.456'
> useSfdxCli: true
> ```

Try lwcCompilerVersion: '900.472.8'

There is a known issue that the latest compiler doesn't work with Standard OmniStudio Runtime but if you're running Package Runtime then it may work...
