### ISSUE TITLE
Export Issues for DataRaptors

### ISSUE THREAD

**Issue by alinamitchell** [vlocityinc/vlocity_build#489]
Hello, 

I have been experiencing issues exporting DataRaptors that include formula - they export blank and only include Input Json and Expected Json. Are there any recommendations on how to solve this issue?

Thank you!

**Comment by rutlabaga** [comment]
Can you file a Salesforce Support case with this info? Are you able to export these through the Export button UI in Salesforce?

**Comment by alinamitchell** [comment]
@rutlabaga Ok, and no, it also exports empty using Export button.

**Comment by manas-sf** [comment]
It should be fixed now.
