### ISSUE TITLE
Failing on export as part of Bamboo build

### ISSUE THREAD

**Issue by IIvanov8888** [vlocityinc/vlocity_build#49]
TypeError: Object.values is not a function
--
06-Apr-2018 10:26:36 | at DataPacksUtils.printJobStatus (D:\BambooHome-2\xml-data\build-dir\CRM-DITSV-VDI2S\vlocity_build\lib\datapacksutils.js:790:29)
06-Apr-2018 10:26:36 | at Object.callback (D:\BambooHome-2\xml-data\build-dir\CRM-DITSV-VDI2S\vlocity_build\lib\datapacksjob.js:954:41)
06-Apr-2018 10:26:36 | at D:\BambooHome-2\xml-data\build-dir\CRM-DITSV-VDI2S\vlocity_build\node_modules\async\dist\async.js:2244:31
06-Apr-2018 10:26:36 | at D:\BambooHome-2\xml-data\build-dir\CRM-DITSV-VDI2S\vlocity_build\node_modules\async\dist\async.js:906:16
06-Apr-2018 10:26:36 | at D:\BambooHome-2\xml-data\build-dir\CRM-DITSV-VDI2S\vlocity_build\lib\datapacks.js:253:36
06-Apr-2018 10:26:36 | at D:\BambooHome-2\xml-data\build-dir\CRM-DITSV-VDI2S\vlocity_build\node_modules\jsforce\lib\promise.js:72:9
06-Apr-2018 10:26:36 | at _combinedTickCallback (internal/process/next_tick.js:73:7)
06-Apr-2018 10:26:36 | at process._tickCallback (internal/process/next_tick.js:104:9)

running on Node.js 8.0.0 

no issues on local machine , only on Bamboo

**Comment by rutlabaga** [comment]
This always means the Node version is not actually 8+.

**Comment by IIvanov8888** [comment]
closing the issue , problem was node version
