### ISSUE TITLE
Namespace local compilers don't work

### ISSUE THREAD

**Issue by centricadean** [vlocityinc/vlocity_build#492]
In my job pack I've got the following:

- lwcCompilerVersion: "900"
- lwcCompilerNamespace: "vlocity-cme"
- npmAuthKey: XXX

When I run packDeploy, it builds the vlocity-cme folder in vlocity-temp/plugins and it generates all of the LWC from the FlexCards, but all of the components are 'c' and not 'vlocity_cmt'.

Example:

`<c-flex-card-state if:true={record}  key={record._flex.uniqueKey} data-recordid={record.Id} record={record} data-statue="true"  data-index="0" data-rindex={rindex} class="cf-vlocity-state-0 cf-vlocity-state slds-size_12-of-12 "  tracking-obj={_childCardTrackingObj} >`

Expected:

`<vlocity_cmt-flex-card-state if:true={record}  key={record._flex.uniqueKey} data-recordid={record.Id} record={record} data-statue="true"  data-index="0" data-rindex={rindex} class="cf-vlocity-state-0 cf-vlocity-state slds-size_12-of-12 "  tracking-obj={_childCardTrackingObj} >
`

**Comment by AllanOricil** [comment]
@centricadean to solve this error you have to add do this change in the flexcard-compiler package

Change `FlexcardCompilerVBTIntegration` constructor in `vlocity-temp/plugins/@vlocity-cme/flexcard-compiler/index.js` to match the code from the image below

![image](https://user-images.githubusercontent.com/55927613/181232037-fd52ddf5-e644-403f-8880-884df54328e0.png)

**Comment by manas-sf** [comment]
Compiler issue is being looked into by FlexCard team currently. - Tracking GUS WI - W-11994573
