### ISSUE TITLE
/v1/GenericInvoke/ for getCustomLabels returns {"error":"OK"}

### ISSUE THREAD

**Issue by centricadean** [vlocityinc/vlocity_build#494]
Local compile is unable to get Custom Labels as the callout to Salesforce from VBT using /v1/GenericInvoke/ always returns {"error":"OK"}.

This is in flexCardUtils/api.js

I've tried calling the /v1/GenericInvoke/ API from Workbench and it also always returns {"error":"OK"}. As this is using FlexCardCompiler.cls which is in the managed package, I'm unable to see the method names to try and debug.

It feels like Custom Labels aren't ready with local compile.

**Comment by AllanOricil** [comment]
@centricadean did you get any response from Vlocity/Salesforce in the Case you opened?

**Comment by centricadean** [comment]
@AllanOricil yeah I was told it would be fixed in Winter 23 (just released) - we haven't upgraded yet so can't confirm

**Comment by centricadean** [comment]
@AllanOricil so from what I understand, they couldn't fix it in the package so they made a change in the @vlocity-cme plugin which is downloaded when you run packDeploy with the NPM key in your job file. I've checked fetchCustomLabels.js and I can't see any calls to Salesforce anymore so looks like they changed the way it works. However, it's still broken as it's still missing the sessionStorage dependency and a few other things. I raised an issue here: https://github.com/vlocityinc/vlocity_build/issues/520

**Comment by AllanOricil** [comment]
Ans does the error persists with v240?

**Comment by centricadean** [comment]
Yes it does @AllanOricil

**Comment by manas-sf** [comment]
Compiler issue is being looked into by FlexCard team currently. - Tracking GUS WI - W-11994573

**Comment by manas-sf** [comment]
It was recently fixed but seems to be still broken. Team is currently looking into it and should be fixed soon.

**Comment by AllanOricil** [comment]
@centricadean this is our case number
Case #43467130
