### ISSUE TITLE
Gitcheck: true is not working

### ISSUE THREAD

**Issue by Sujendrans** [vlocityinc/vlocity_build#495]
I have implemented CI-CD pipeline using bit-bucket and Vlocity build tool. The deployment from repo to target org is successful, however I need only recent commits to be deployed into the target org but everytime all the dataPacks are deployed to target org.
I used gitCheck: true in my job file but during deployment the pipeline says "git hash not found".
I also tried 
packGetDiffsAndDeploy but it is also deploying all the dataPacks to the target org

**Comment by AllanOricil** [comment]
I'm also facing this problem. Locally, in a mac, it works with no problem. But when I run in an Ubuntu instance, in github actions, I get the same error message

**Comment by manas-sf** [comment]
Git is not correctly setup here. You may need to figure out on your own to solve git hash issue.
https://github.com/vlocityinc/vlocity_build#git-changes-based-deploys

**Comment by AllanOricil** [comment]
@Sujendrans just add 

`-gitCheck=true -overrideOrgCommit=<GIT_SHA>`
