### ISSUE TITLE
Create E2E tests

### ISSUE THREAD

**Issue by AllanOricil** [vlocityinc/vlocity_build#496]
@rutlabaga 
Create E2E tests for each command and with different data pack types. This was actually an idea that @depill suggested to me.

I can do it for you. I would just need a dev and prod org.

**Comment by manas-sf** [comment]
@AllanOricil We already have good amount of tests using command - runTestJob. It run tests for different datapacktypes, custom vs new Omnistudio objects and so on.

**Comment by AllanOricil** [comment]
@manas-sf I mean tests for the cli, to ensure patches do not introduce new bugs.

**Comment by manas-sf** [comment]
runTestJob is for VBT only which gets validated while release build for VBT.

**Comment by AllanOricil** [comment]
But I mean something like this:

1 - giving a set of datapacks
2 - deploy to a sandbox
3 - open this sandbox
4 - navigate to where the datapack
5 - assert that the datapack works as designed: 
      for instance, a flexicard datapack was not only deployed to the org, but was also activated, and can be rendered properly on a sandbox
6 - take a screenshot or record a video showing this behavior.
      
 I believe these type of test spec would ensure nothing really broke.
