### ISSUE TITLE
An error occurred while loading OmniScript compiler: Error: Failed to get package '@vlocity-ins/omniscript-lwc-compiler' Response error 401 Unauthorized

### ISSUE THREAD

**Issue by yanansi** [vlocityinc/vlocity_build#499]
Hi,
I am using Vlocity Build v1.15.6 to deploy OmniScript with active set to true. the OmniScript activation throw the following error. This only stop working recently, cannot figure out what is the issue

```
Loading @vlocity-ins/omniscript-lwc-compiler@890.336
--
  | [2022-08-05T02:59:13Z]   Deploying OmniScript using legacy method... Local compiler disabled
  | [2022-08-05T02:59:13Z]   An error occurred while loading OmniScript compiler: Error: Failed to get package '@vlocity-ins/omniscript-lwc-compiler' Response error 401 Unauthorized
```

**Comment by centricadean** [comment]
Make sure you have your npmauthkey in your job file as 401 unauthorised looks like you're not able to access the Vlocity NPM repo.

Also make sure your job file is set to the following (for Vlocity-ins):

lwcCompilerVersion: "890"
lwcCompilerNamespace: "vlocity-ins"
npmAuthKey: YOURKEYHERE

**Comment by yanansi** [comment]
hi @centricadean 

thank you for your quick reply, would you mind show me where can i get the npmAuthKey pls.

**Comment by centricadean** [comment]
You need to request it from Salesforce Support. Just raise a case with the subject: "Request for Access Key to Vlocity's Private NPM Repository at https://repo.vlocity.com/repository/vlocity-public/ for using OmniOut / IDX CLI".

**Comment by KevinGossentCap** [comment]
@yanansi , it is a normal error when you don't use the 1.15 new feature : "localCompile".
this feature is still known to have issues.
If you continue using puppeteer to activate omniscripts and flexcards, that's an error to ignore.

**Comment by manas-sf** [comment]
Please try using latest version - 1.16.0. If still you face any issues, Feel free to raise case with Salesforce support.

**Comment by tggagne** [comment]
@yanansi , was issue resolved using npmAuthKey?  Did you need to specify anything else?
