### ISSUE TITLE
New Remote Actions will not deploy to existing OmniScript

### ISSUE THREAD

**Issue by LamereMichael** [vlocityinc/vlocity_build#50]
I have a new remote action that I have created in our develop sandbox and when I export and deploy to our devInt sandbox, that remote action is not getting created. I have attached screenshots of the Develop and DevInt OmniScript, along with my job YAML file and source file showing the export did pull the remote action.
![job yaml](https://user-images.githubusercontent.com/5972241/38457713-e8b29682-3a59-11e8-9410-70f785501c90.jpg)
![command](https://user-images.githubusercontent.com/5972241/38457714-e8c3eae0-3a59-11e8-84a7-ddb4ab47c988.jpg)
![sourcefile](https://user-images.githubusercontent.com/5972241/38457715-e8d41136-3a59-11e8-9dfd-4de542140943.jpg)
![devint](https://user-images.githubusercontent.com/5972241/38457716-e8e6d1d6-3a59-11e8-8a29-67a45cdab2b3.jpg)
![dev](https://user-images.githubusercontent.com/5972241/38457717-e8f6b61e-3a59-11e8-96ef-a3c519d8d4ed.jpg)

**Comment by rutlabaga** [comment]
Please file a support ticket through Vlocity's primary support. Please include the folder being deployed.

**Comment by rutlabaga** [comment]
The issue here was a duplicately named OmniScript Action. OmniScript is case sensitive, but this tool is not, so when two Actions only differed by case it deleted one. createNewQuoteDental vs createnewquotedental.
