### ISSUE TITLE
Error creating file. When trying to export using packExport

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#500]
When I try to pull the Vlocity code, I get an export error. What could be the issue?

**Example.YAML**
projectPath: .C:\Projects\Proton1
queries:
  - DataRaptor
  - OmniScript
  -  
**build_source.properties**
sf.username = test.name@testorg.com.qa
sf.password = PasswordpSecurityToken
sf.loginUrl = https://testportal.my.salesforce.com/

The command for export:
vlocity packExport -propertyfile VlocityBuildTool/build_source.properties -job C:\Projects\Proton1\vyaml\Example.yaml

Result:
It shows as 
Retrieved 729 items >> Exporting
Retrieved 729 items >> Exporting
  Job Complete >> Export 2m 46s  
Export error:
OmniScript/CPQ_AssetViewerOrderFlow_Multi-Language references IntegrationProcedure/CPQ_CreateOrder which was not found.
OmniScript/MACD_Move_Multi-Language references VlocityUITemplate/SelectAssetToMove.html which was not found.
OmniScript/MACD_Move_Multi-Language references VlocityUITemplate/MovedAssetReview.html which was not found.
OmniScript/CPQ_AssetViewerQuoteFlow_Multi-Language references IntegrationProcedure/CPQ_CreateQuote which was not found.

**Comment by rutlabaga** [comment]
These are just saying that the referenced  VlocityUITemplates / Integration Procedures were not found in your org. These are likely not even OmniScripts you have created, so probably you can just ignore this.
