### ISSUE TITLE
command not found: username

### ISSUE THREAD

**Issue by ModeratelyComfortableChair** [vlocityinc/vlocity_build#507]
I am performing the following command:
`vlocity packExport -sfdx.username MY_ALIAS -job MY_YAML.yaml`

MY_ALIAS is the org I am currently connected to in VSCode via SFDX

I keep getting the following error:
`Job Complete >> Export
  Command not found: .username
  Job Complete >> .username`

Without any actually export occurring.

If I create a build.properties file with the following
`sfdx.username = MY_ALIAS
sf.loginUrl = LOGIN_URL`
I will get the export, and the following error
`Command not found: .username  
  Job Complete >> .username   
.username error:
Command not found: .username`

Also, it will only use the alias defined in the build.properties. It will not use the alias defined in the command line flag. How can I have this actually use the alias from the command line argument and avoid having a build.properties file?

**Comment by balrick** [comment]
If you using windows computer make sure your terminal is Command prompt. Other computer OS,  use bash.  Do not use powershell.

**Comment by manas-sf** [comment]
You may need to authenticate the org using sfdx.

**Comment by tim-ingenuity** [comment]
This has been driving me nuts for a couple days now, definitely an issue with Powershell, bash and cmd work fine.
Thanks @balrick
