### ISSUE TITLE
Create Datapack Deploy Validation Service

### ISSUE THREAD

**Issue by AllanOricil** [vlocityinc/vlocity_build#509]
This Service should work in the same way as SF metadata Deploy does. Vlocity datapacks deployments must run in queues. There must be a Service that is able to validate datapacks and the Metadata it creates (like lwcs) before allowing features to be released. If the metadata generated by vlocity datapacks fails during vlidation | deployment, datapacks should return to their latest state | version automatically.

At the moment vlocity cli is able to Deploy and activate datapacks partially. This service would also handle "all or none" deployments.

**Comment by manas-sf** [comment]
VBT is a constructive tool. It won't remove partially deployed datapacks until it's completely failed. It can just let you know the current state of datapack so that re-deployment can be tried for failed datapacks.

**Comment by AllanOricil** [comment]
right, we have to keep building until we have no errors. That is fine.
