### ISSUE TITLE
VBT is not compiling LWC on latest Chrome 

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#519]
VBT is failing LWC compilation on mac M1 with Chrome v107 (latest).

not sure if this is limited to mac M1, but this is the setup where I can replicate it. Didn't try other configuration.

The sample log below is from version 1.15.9 but 1.16.0 is the the same.

```
  Loading @vlocity-cme/flexcard-compiler@latest
  Can also install compiler with npm install @vlocity-cme/flexcard-compiler
  An error occurred while loading OmniScript compiler: Error: Failed to get package '@vlocity-cme/flexcard-compiler' Response error 401 Unauthorized  - If you are using Puppeteer for LWC compilation this error can be ignored
  Legacy fall back flow for compiling Flexcards with Puppeteer
  Puppeteer initialization Failed, LWC Activation disabled - Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

  Finalizing Deployment
  Salesforce Org >> delta2
  Version Info >> v1.15.9 vlocity_cmt 900.456
```

I did quick research and found that VBT has dependency to ancient version of puppeteer-core@5. Bumping this to version 6 or newer fix the problem. I would also gently note that other VBT dependencies are heavily outdated with multiple critical vulnerabilities. Among all outdated dependencies this one with puppeteer-core makes VBT unusable.

**Comment by manas-sf** [comment]
@pawel-id Please feel free to raise the support case with Salesforce providing all the details. We need to reproduce it as latest version 1.16.0 is working fine for us.
