### ISSUE TITLE
Deployment errors on rules and entityFilters

### ISSUE THREAD

**Issue by siminn-svavarhall** [vlocityinc/vlocity_build#52]
Im having trouble moving data to a new sandbox:

ContextDimension/e45f9d65-fa3d-ecbe-77aa-8325a82c35db -- Channel -- Error Message -- Data Type: bad value for restricted picklist field: Text

VlocityStateModel/Contract State Model -- Contract State Model -- Error Message -- Only one state model can exist with the same Type Field Name and Type Field Value for Contract. State Model name has to be unique.

Rule/All Relationships Rule -- All Relationships Rule -- Error Message -- No match found for vlocity_cmt__RuleAction__c.vlocity_cmt__ProductRelationshipId__c - vlocity_cmt__GlobalKey__c=20ea89ed-83bb-2e89-3c7c-5987baa3745b (vlocity_cmt)

EntityFilter/Channel==Web -- Channel==Web -- Error Message -- No match found for vlocity_cmt__EntityFilterCondition__c.vlocity_cmt__ContextDimensionId__c - vlocity_cmt__GlobalKey__c=e45f9d65-fa3d-ecbe-77aa-8325a82c35db (vlocity_cmt)

EntityFilter/Check_DiscountProduct -- Check_DiscountProduct -- Error Message -- No match found for vlocity_cmt__EntityFilterConditionArgument__c.vlocity_cmt__ContextDimensionId__c - vlocity_cmt__GlobalKey__c=8553e128-2598-4bff-2faa-a14167e6b6f4 (vlocity_cmt)

EntityFilter/Test_TvTplusnRule1 -- Test_TvTplusnRule1 -- Error Message -- No match found for vlocity_cmt__EntityFilterConditionArgument__c.vlocity_cmt__ContextDimensionId__c - vlocity_cmt__GlobalKey__c=8553e128-2598-4bff-2faa-a14167e6b6f4 (vlocity_cmt)

Rule/Channel = Web Rule Set -- Channel = Web Rule Set -- Error Message -- No match found for vlocity_cmt__RuleFilter__c.vlocity_cmt__EntityFilterId__c - vlocity_cmt__GlobalKey__c=59114c9a-2421-2e9d-7601-47a744bc6d36 (vlocity_cmt)

Rule/Check Discount Product Rule Set -- Check Discount Product Rule Set -- Error Message -- No match found for vlocity_cmt__RuleFilter__c.vlocity_cmt__EntityFilterId__c - vlocity_cmt__GlobalKey__c=733fa1c4-69d5-d914-1305-2b0eb3cfb64a (vlocity_cmt)

Rule/Test_TvTplusn -- Test_TvTplusn -- Error Message -- No match found for vlocity_cmt__RuleFilter__c.vlocity_cmt__EntityFilterId__c - vlocity_cmt__GlobalKey__c=de8bf4ae-f3c7-13bf-8f09-79e098a93055 (vlocity_cmt)

Promotion/249cefd8-88f4-6783-be83-b0998e8bd73d -- Góð byrjun for Standard TV -- Error Message -- No match found for vlocity_cmt__RuleAssignment__c.vlocity_cmt__RuleId__c - vlocity_cmt__GlobalKey__c=233015a0-276b-e455-7756-5e8e04c2e90c (vlocity_cmt)

**Comment by rutlabaga** [comment]
Please file a ticket through Vlocity Support. The issue here is related to the data not existing in the org. You should try running `packRetry` anytime there is an error, but other than that, a better support channel is require to help solve these very specific issues.
