### ISSUE TITLE
Local compile still broken - @vlocity-cme plugin still needs fixing

### ISSUE THREAD

**Issue by centricadean** [vlocityinc/vlocity_build#520]
Local compile is still broken in the latest version of VBT. The @vlocity-cme plugin in the Vlocity private repo needs fixing. @vlocity-cme is downloaded when you define the NPM key in your job file. As this comes from the Vlocity private repo, I'm unable to suggest changes in this repo, so posting as an issue here.

1. In @vlocity-cme/flexcard-compiler/src/compiler/flexCardUtility/fetchCustomLabels.js 

```
'use strict';
let sessionStorage = require('sessionstorage'); 
```

needs adding to top of of the file

2. in @vlocity-cme/flexcard-compiler/package.json

```
"sessionstorage": "0.1.0"
```

needs adding to dependencies

3. In @vlocity-cme/flexcard-compiler/src/compiler/flexCardUtility/userProfile.js 

line 1 needs updating to: 

```
const getUserProfile = require('../flexCardUtils/flexCardUtils').getUserProfile;
```

Until these issues are fixed, you'll face sessionStorage and userProfile errors when trying to use local compile with FlexCards/VlocityCards.

**Comment by centricadean** [comment]
@rutlabaga any chance of getting engineering to look at this?

**Comment by manas-sf** [comment]
@centricadean If you are still facing issue with latest VBT#1.16.0, Please feel free to raise a case with Salesforce support providing all the details. I will make sure to have someone look into this. Thank you.
