### ISSUE TITLE
better order component based on dependencies for packDeploy

### ISSUE THREAD

**Issue by KevinGossentCap** [vlocityinc/vlocity_build#521]
VBT is already partially more or less ordering datapacks in some kind of order so that there is little dependencies errors at deployment.
But the dependency tree (I suppose) is not great and we frequently face errors of components that fail deployments because of dependent component not yet deployed.
It happens for products, but also for omniscripts/flewcards. You can easily use "industry CPQ LWC" and "ESM" as examples as they are vlocity own  tools.
If a dependency tree is created as a pre-deployment step to list the datapacks in the right order, all deployments will see benefits as we'll loose a lot less time (especially while waiting for omniscript/flewcards compilation waiting timeout...)

**Comment by manas-sf** [comment]
There is not much that could be done on reordering datapacks. VBT is already following the best possible way out. Unfortunately it still fails for some dependencies.
