### ISSUE TITLE
Local compile incorrectly compiling when you're in a managed package namespace

### ISSUE THREAD

**Issue by centricadean** [vlocityinc/vlocity_build#525]
If you're in a namespace such as vlocity_cmt then the local compiler is not compiling some elements correctly. One example is the cfCpqBrowsePhaseContainer FlexCard used in the LWC Cart. When compiling on-platform, all of the elements are correct, however, when using local compile, some of the elements are using c and not the namespace.

See an example below of code compiled on-platform (left) and locally (right):

![Screenshot 2022-11-15 at 5 02 47 pm](https://user-images.githubusercontent.com/104971277/201981155-dd433420-1f16-4f3a-83ac-ba251e206139.png)

This has been tested with the latest version of VBT.

Case #43628406 raised.

**Comment by thvd** [comment]
I can confirm the same. We have a case going for quite a while with number #43466400.

**Comment by manas-sf** [comment]
@thvd Please find new minor patch released - https://github.com/vlocityinc/vlocity_build/releases/tag/v1.16.1
