### ISSUE TITLE
VBT crashes and no log with important number of components to deploy

### ISSUE THREAD

**Issue by KevinGossentCap** [vlocityinc/vlocity_build#527]
Use case : 
VBT 1.16 (latest)
nodeJS 18.12.1 (latest)
Windows 10 (up to date)
packdeploy of a big catalog (catalogs, products, attributes, pricelists, etc.)
big meaning at least from 3000 (2000 no crash, 3000 crash) products with all relationship types possible
- name1_AttributeAssignments.json
- name1_DataPack.json
- name1_ObjectFieldAttributes.json
- name1_ParentKeys.json
- name1_PricebookEntries.json
- name1_PriceListEntries.json
- name1_ProductChildItems.json

At the end of the VBT listing all datapacks, everything stops, with no logs at all with this kind of result on commandline
  Automatically Updating Picklists Before Deploy

<--- Last few GCs --->

[12764:000002F794DB9650]  1352175 ms: Mark-sweep 3702.1 (4134.6) -> 3700.4 (4131.3) MB, 585.5 / 0.0 ms  (average mu = 0.786, current mu = 0.230) allocation failure; scavenge might not succeed
[12764:000002F794DB9650]  1353100 ms: Mark-sweep 3716.1 (4131.3) -> 3714.4 (4160.3) MB, 884.1 / 0.0 ms  (average mu = 0.560, current mu = 0.044) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6413B1B7F node_api_throw_syntax_error+203775
 2: 00007FF641331556 v8::internal::wasm::WasmCode::safepoint_table_offset+63558
 3: 00007FF6413328C2 v8::internal::wasm::WasmCode::safepoint_table_offset+68530
 4: 00007FF641DD47F4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF641DBFB52 v8::Isolate::Exit+674
 6: 00007FF641C41BBC v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF641C3EDDB v8::internal::Heap::CollectGarbage+3963
 8: 00007FF641C55013 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF641C558BD v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF641C5E20A v8::internal::Factory::AllocateRaw+810
11: 00007FF641C7164D v8::internal::FactoryBase<v8::internal::Factory>::NewHeapNumber<0>+685
12: 00007FF641C75AF8 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString+72
13: 00007FF64190D1FB v8::internal::StringStream::ClearMentionedObjectCache+9291
14: 00007FF641B5DC28 v8::sampler::Sampler::Stop+2824
15: 00007FF641B5EEC7 v8::sampler::Sampler::Stop+7591
16: 00007FF641B5F6C2 v8::sampler::Sampler::Stop+9634
17: 00007FF641B65039 v8::base::TimeDelta::operator!=+13817
18: 00007FF641B5F875 v8::sampler::Sampler::Stop+10069
19: 00007FF641B65039 v8::base::TimeDelta::operator!=+13817
20: 00007FF641B6108B v8::sampler::Sampler::Stop+16235
21: 00007FF641B63A86 v8::base::TimeDelta::operator!=+8262
22: 00007FF641D68EFF v8::internal::Builtins::code+99375
23: 00007FF641E71F81 v8::internal::SetupIsolateDelegate::SetupHeap+558449
24: 00007FF5C22D17AC

VBT should be able to build and scale using streams maybe instead of everything in plain Strings maybe ?
At least how to leverage all that to permit industrial processes (meaning not manually splitting item list to not trigger such bad crash)

**Comment by manas-sf** [comment]
Thanks for your suggestion. Will try to fix once we have bandwidth.

**Comment by KevinGossentCap** [comment]
@manas-sf if you set it as fixed, could you link the related pull-request or commit implementing that ?
