### ISSUE TITLE
VBT OverrideSettings not working

### ISSUE THREAD

**Issue by KevinGossentCap** [vlocityinc/vlocity_build#531]
VBT 1.16
nodeJS 18.12.1
Windows 10

I'm trying to overcome VBT folder and file overwrite on catalog datapacks because of names too similar.
For that, I'm trying all possible ways to use the OverrideSettings in my job file to change the catalog foldername
As of now, nothing works.
How to make it work ? or is it broken ?

**Comment by KevinGossentCap** [comment]
I finished at last to find how it works.
It's definitely not easy to the théorie of the structure and differences to make compared to "lib/datapacksexpandeddefinition.yaml".

you should explain clearly that, even if the vlocity_namespace is nowhere in "lib/datapacksexpandeddefinition.yaml", for overrideSettings you HAVE to put it if it's an element of the namespace (we can write vlocity_namespace instead of vlocity_cmt etc, but we have to put it)

**Comment by manas-sf** [comment]
https://github.com/vlocityinc/vlocity_build#overriding-datapack-settings
