### ISSUE TITLE
VBT exports only 1 row of 12-row CalculationMatrix

### ISSUE THREAD

**Issue by tggagne** [vlocityinc/vlocity_build#551]
The source org has 7 versions of the matrix, the most recent has 12-rows of data.  When I export it by itself I'm only getting the 1st rows.

job.yaml:
`
projectPath: ./force-app/main/default/
expansionPath: vlocity
verbose: true
manifest:
  - CalculationMatrix/Agreements 
 `

I've tried deleting the directory inside CalculationMatrix/Agreements.  I can see the 12 rows in the source org so I don't think it's a permission problem.

I noticed multiple of the versions are "enabled" but I'm unsure the significance of that since these aren't Omniscripts or IPs.

Has anyone else bumped into this before?  Why would VBT see only one row?

**Comment by tggagne** [comment]
So this particular matrix is a row-version matrix.  So version 7 only updated once row, and that's the row that gets exported.  The problem is, how do I deploy the CalculationMatrix if it only deploys the most recent version?  It appears that on deploy all the previous rows are removed and replaced with the most recent.

**Comment by thvd** [comment]
Not sure whether this would help, but can you try to add the setting: `separateMatrixVersions: true` to the config.yaml file?

**Comment by tggagne** [comment]
My bad for not following this up.  We started doing it by hand (ugh) and so I hadn't come back to this.  I'll try to verify.
