### ISSUE TITLE
Failed deployment datapacks gets deployed in the next successful deployment

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#557]
We use VBT in our Git Actions-based deployment.
Scenario: We have a PR with 10 datapacks and while deploying 9 got deployed and 1 failed due to some LWC dependency issue. Due to the failure the Git hash was not updated in the org by the VBT script nor did we do it manually.
Next, we try to deploy another PR with 2 data packs. They get deployed + the previous 10 data packs also get deployed which were part of the previously failed deployment.

Expected Result: As per Git hash difference only 2 data packs should have been deployed

Actual Result: 2 data packs that are expected and 10 not expected gets deployed.

Why does this happen, when previously failed deployment data packs gets deployed?
How to handle this scenario without we manually updating the Git hash from the failed deployment.

**Comment by AllanOricil** [comment]
@irfanlai 
You have to use local diff instead of org diff to compute the diffs.

**Comment by irfanlai** [comment]
> @irfanlai You have to use local diff instead of org diff to compute the diffs.
> 
> https://github.com/vlocityinc/vlocity_build#git-changes-based-deploys
> 
> When you deploy something, create a git tag to mark the state of the deployment to a particular environment. Then when running the job again, pass this tag to this param `overrideOrgCommit`. This way the source of truth for your deployments is going to be git and not the org, and you won't have to redeploy things that were already deployed.

This is interesting. I have never done this. Do you have an example of how this is to be done?
