### ISSUE TITLE
Any solution to pull the delta details before packDeploy executes

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#559]
We use GitHub actions for our salesforce deployment. We use SGD-Delta for Salesforce metadata and VBT for Vlocity deployments using Gitcheck. With SGD-Delta we can get the metadata delta details before the actual deployments, We can print what's going to be deployed in our actions. This way developer knows what is the delta which is going to be deployed.

I am looking for a similar solution that shows Vlocity Git delta which is going to be deployed? Are there any commands which can help me pull the data before I run the packDeploy command?

**Comment by AllanOricil** [comment]
@irfanlai 

`vlocity -propertyfile <filepath> -job <filepath> packGetDiffs`

**Comment by irfanlai** [comment]
> @irfanlai
> 
> `vlocity -propertyfile <filepath> -job <filepath> packGetDiffs`
> 
> `packDeploy` also prints the diffs before starting.
> 
> If you use this feature https://github.com/vlocityinc/vlocity_build#git-changes-based-deploys and overwrite the git command, you will see the list of changes that is going to be deployed.

I have used the packGetDiffs and it took a very long time(53 mins to be precise) to execute that command and I was confused with the result I got.

Do you mean packDeploy command when it starts deploying? That's way to fast and by the time you realize something which is not required will be deployed, a couple of them are already deployed.

How will the overwrite command show the list of changes? Can you elaborate, please?

**Comment by AllanOricil** [comment]
> Do you mean packDeploy command when it starts deploying? That's way to fast and by the time you realize something which is not required will be deployed, a couple of them are already deployed.

Yes. When this command is running, it outputs lots of logs. The first log messages display exactly which datapacks will be deployed.


> How will the overwrite command show the list of changes? Can you elaborate, please?

When you overrwrite the base commit, the cli print log messages with the changes it found between the 'HEAD' of your branch and the Overrwrite commit. It basically runs this `git diff MY_COMMIT..mybranch` and prints it in the terminal

````shell
...
changes
A ./vlocity/Omniscript/my_omniscript
M ./vlocity/Flexcard/my_flexcard
....
...
````

**Comment by AllanOricil** [comment]
The cli also logs all this information to a `json` file located at `./vlocity-temp/currentJobInfo.json` 
The `vlocity-temp` directory is located in the root of your sfdx project.

**Comment by manas-sf** [comment]
Seems like already answered by AllanOricil.
