### ISSUE TITLE
packGetDiffsAndDeploy always lists all of the vlocity components in repository as New

### ISSUE THREAD

**Issue by rpiotrowski91** [vlocityinc/vlocity_build#563]
Hello. We use Bitbucket pipelines for our CI/CD process for Salesforce metadata (with sfdx) and Vlocity components (with VBT). For the Vlocity part we wanted to use packGetDiffsAndDeploy command in order to deploy only changed items. However, apparently VBT recognizes all of the Vlocity components we have in our repository as new each time the pipeline runs. So basically it works the same as packDeploy. Could you please provide any insights on this?

**Comment by gswinarski** [comment]
Same here. Every deployment creates a new version of the component on the target environment.

**Comment by manas-sf** [comment]
For packGetDiffsAndDeploy command to work, everything should be strictly same i.e all the configs, attributes & properties etc. In IDX, differences can be visualised.

For command verification, I exported datapacks from org and tried re-deploying the datapacks back to same org using the command, but none got deployed as they were unchanged. 

Logs must be having something like - Diff Status >> Unchanged OmniScript/CaseDetails_CaseOwnerDetails_English if they are unchanged.

**Comment by rpiotrowski91** [comment]
In our case, new have a couple of Vlocity components developed few weeks back. They were not changed since they were added to out git repository for the first time. However, when someone runs the deployment pipeline (due to some changes in other components), we always see 

Retrieving Vlocity  
  Diff Status >> New

for all of our Vlocity components. So we are really not sure where the diff is coming from, since the items in repo were not touched.

**Comment by manas-sf** [comment]
You can visualise differences in IDX workbench. Datapacks are in JSON format, any property change can cause re-deployment.  I tested by exporting and importing back to same org and could see unchanged status.

**Comment by manas-sf** [comment]
Also in Version Compare section of IDX, you can compare two versions of IP/OS specifically.

**Comment by manas-sf** [comment]
webComponentKey has been added to ignore list.
