### ISSUE TITLE
repo.vlocity.com down

### ISSUE THREAD

**Issue by thvd** [vlocityinc/vlocity_build#568]
For the local compiler we relay on the repo.vlocity.com repo.
But it's down: 502 Bad Gateway

**Comment by AllanOricil** [comment]
We should start adding it as a dev dependency in sfdx projects, using node's package.json. We can then use cicd vendor tools caching mechanisms to avoid having to re-download it all the time.
When is it going to be open sourced? Can't you publish them to a private namespace called `@vlocity` in npm?

**Comment by AllanOricil** [comment]
relates https://github.com/vlocityinc/vlocity_build/issues/533
