### ISSUE TITLE
packExport is filling by user with Attachments and not deleting them

### ISSUE THREAD

**Issue by inglazarev** [vlocityinc/vlocity_build#57]
Hello,

When I run `packExport`, my user get filled with Attachments like the next one and they are not getting deleted while the script is going forward, causing the environment to run out of space.

`{"VlocityPrimarySourceId":null,"VlocityPreviousPageKey":null,"VlocityMultiPackParentKey":null,"VlocityDepthFromPrimary":0,"VlocityDataPackType":"ObjectLayout","VlocityDataPackStatus":"Ready","VlocityDataPackRelationshipType":"Child","VlocityDataPackRecords":[],"VlocityDataPackParents":["4e4e6bfd8dc847e302f1f5e08f4e6dfb","416b4fad72780e0165ef4e38d416ee91"],"VlocityDataPackName":"Id: a1k6C000000C1w8QAC","VlocityDataPackMessage":null,"VlocityDataPackLabel":"ObjectLayout","VlocityDataPackKey":"73d86108b5af946d2b36cf9e35096503","VlocityDataPackIsNotSupported":false,"VlocityDataPackIsIncluded":true,"VlocityDataPackData":{"VlocityDataPackRelationshipType":"Child","VlocityDataPackKey":"73d86108b5af946d2b36cf9e35096503","VlocityDataPackLabel":"ObjectLayout","VlocityDataPackType":"ObjectLayout","Id":"a1k6C000000C1w8QAC"},"VlocityDataPackAllRelationships":{"416b4fad72780e0165ef4e38d416ee91":"Reference by Salesforce Id"},"DataPackAttachmentSize":0,"DataPackAttachmentParentId":null,"DataPackAttachmentId":null,"ActivationStatus":"NA"}`

**Comment by rutlabaga** [comment]
I have added to the cleanData.js command deleting old stale VlocityDataPack__c records. This should hopefully eliminate this issue.
