### ISSUE TITLE
Puppeteer is still invoked for some scenarios with local compilation

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#573]
Some Vlocity metadata still require puppeteer and chrome even local compilation is turned on. This happens for UILayouts. Please find the sample output provided below:

```
Compiling Flexcard with  FlexCard ID:  >> a5c1X000000Oc5dQAC
  {}
  Puppeteer call by: onDeployFinish UILayout
  Starting LWC Activation for Classic Card >> VlocityUILayout/b2bSampleAppCard
  Activating Classic Card LWC >> VlocityUILayout/b2bSampleAppCard DEPLOYING
  ...
  Elapsed Time >> 30m 44s
  Activating Classic Card LWC >> VlocityUILayout/b2bSampleAppCard DEPLOYING
  Elapsed Time >> 30m 49s
  Activating Classic Card LWC >> VlocityUILayout/b2bSampleAppCard DONE
  Elapsed Time >> 30m 54s
  LWC Activated >> LWC Activated for Card: VlocityUILayout/b2bSampleAppCard
  Puppeteer call by: onDeployFinish UILayout
  Deploying generated LWC components
  Using sfdx cli
  Running source:convert
  source:convert ended successfully
  Running mdapi:deploy
  ...
```

I think this is that part of code which triggers puppeteer https://github.com/vlocityinc/vlocity_build/blob/master/lib/datapacktypes/vlocityuilayout.js

It is expected that providing local compilation key cause puppeteer and chrome not required. This is crucial for CI/CD systems where preparation depends on fact that chrome / puppeteer is requred or not.

Tested on v1.17.0

**Comment by AllanOricil** [comment]
@pawel-id according to a work colleague, these VlocityUILayout datapacks generate Angular components and that is the reason they can't be "compiled" with the local "lwc compilers"
