### ISSUE TITLE
useSfdxCli: true is incompatible with VBT version 1.17.1

### ISSUE THREAD

**Issue by lpsouzalima** [vlocityinc/vlocity_build#584]
After updating the VBT version from 1.16.0 to the most current one, we started to receive error when deploying omniscripts.
In the Job file, we use the parameter useSfdxCli: true. When we remove this parameter the error no longer occurs.
We updated SFDX to the latest version and the problem continued to occur when keeping the parameter in the job file.

Error:

Deploying generated LWC components Using sfdx cli Running source:convert Error: Error parsing stdout at _run (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\sfdx.js:11:9) at _sourceConvert (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\sfdx.js:28:9) at run (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\sfdx.js:37:10) at module.exports.DataPacksJob.deployJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:2796:23) at async module.exports.DataPacksJob.doRunJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:339:9) at async module.exports.DataPacksJob.runJobWithInfo (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:293:9) at async module.exports.DataPacksJob.getDiffsAndDeploy (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:3101:9) at async module.exports.DataPacksJob.doRunJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:349:9) at async module.exports.DataPacksJob.runJobWithInfo (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:293:9) at async module.exports.DataPacksJob.runJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:95:26) Back to Ready Deploying Vlocity Deploying generated LWC components Using sfdx cli Running source:convert Error: Error parsing stdout at _run (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\sfdx.js:11:9) at _sourceConvert (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\sfdx.js:28:9) at run (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\sfdx.js:37:10) at module.exports.DataPacksJob.deployJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:2796:23) at async module.exports.DataPacksJob.doRunJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:339:9) at async module.exports.DataPacksJob.deployJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:2855:13) at async module.exports.DataPacksJob.doRunJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:339:9) at async module.exports.DataPacksJob.runJobWithInfo (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:293:9) at async module.exports.DataPacksJob.getDiffsAndDeploy (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:3101:9) at async module.exports.DataPacksJob.doRunJob (C:\Users\luiz.felipe.cunha\AppData\Roaming\npm\node_modules\vlocity\lib\datapacksjob.js:349:9) Finalizing Deployment

**Comment by AllanOricil** [comment]
@lpsouzalima create a public repository and add the steps to reproduce the error in a README. Include the environment details so that I can reproduce the error.
