### ISSUE TITLE
Delta changes are not deployed when using packGetDiffsAndDeploy

### ISSUE THREAD

**Issue by AllanOricil** [vlocityinc/vlocity_build#585]
I noticed that delta deployments won't happen if we use `packGetDiffsAndDeploy` command with `-gitCheck=true -overrideOrgCommit=$git_ref_name`

For example, the following command does a full deployment

`vlocity -sfdx.username=$instance_alias -job $job_file_path packGetDiffsAndDeploy -gitCheck=true -overrideOrgCommit=$git_ref_name`

while the next one does a delta deployment

`vlocity -sfdx.username=$instance_alias -job $job_file_path packDeploy -gitCheck=true -overrideOrgCommit=$git_ref_name`

The only difference between both is the command. It seems weird that `packDeploy` works with `-gitCheck=true -overrideOrgCommit=$git_ref_name` but not with `packGetDiffsAndDeploy` because the word `diffs` is in the name of the latter.

**Comment by jfgarcia268** [comment]
@AllanOricil Please Use PackDeploy when using gitCheck=true

**Comment by AllanOricil** [comment]
The behavior works as expected like you said, but the commands are not well named. It can cause confusion. 

 

There is 2 ways of doing Delta deployments:
1. using org comparison
2. using git

The 1st approach is done using the "packDiffsAndDeploy" command, while the 2nd with "packDeploy".

Doesnt it feel odd? It confused me, and I have experience not as a User, but with the cli source code.
My suggestion is to have a single command that does deployments and use flags to control extra behaviors, such as doing delta deployments using Org comparison or Git comparisons.

With this suggestion the confusion that I had would be gone:

1. full deployment: `deploy --all`
2. org based delta deployment: `deploy`
3. git based delta deployment: `deploy --git`
4. git based delta deployment overwritting org git sha/ref: `deploy --git --overwriteOrgSha=git_ref`
