### ISSUE TITLE
Local compilation does not work behind proxy

### ISSUE THREAD

**Issue by pawel-id** [vlocityinc/vlocity_build#586]
We are using VBT on the infrastructure behind the proxy. It works well for generic operations and any operations via puppeteer. It honours standard proxy environment variables *_PROXY. This is fine

However if we try local compilation then it is not able to get the connection behind the proxy. It is not able to get the local compilation libraries and then it falls back to puppeteer operations. Below trace from v1.17.2

```
Loading @vlocity-cme/omniscript-lwc-compiler@latest
Can also install compiler with npm install @vlocity-cme/omniscript-lwc-compiler
An error occurred while loading OmniScript compiler: FetchError: Failed to get package '@vlocity-cme/omniscript-lwc-compiler' request to https://repo.vlocity.com/repository/vlocity-public/@vlocity-cme%2Fomniscript-lwc-compiler failed, reason: connect ETIMEDOUT 44.233.139.161:443  - If you are using Puppeteer for LWC compilation this error can be ignored
Deploying OmniScript using legacy method... Local compiler disabled
```

Expected behaviour: VBT local compilation will work behind corporate proxy.

**Comment by pawel-id** [comment]
I did little investigation and it turns out that VBT is using module ‘runtime-plugin-manager-clone’ which seems to be forked version of another module which is not supporting proxy: https://github.com/davideicardi/live-plugin-manager/issues/48

**Comment by AllanOricil** [comment]
@pawel-id did u try verdaccio?
