### ISSUE TITLE
ContentVersion - Underfined

### ISSUE THREAD

**Issue by AdeloyeB** [vlocityinc/vlocity_build#592]
We seem to getting an underfined error - ContentVersion/7b616361-acbd-3678-9684-37c04953f6af - undefined

Even with all the dependencies included in the Pull Request. 

Furthermore, we're also getting a 'No Match Found' error even with all the relevant OmniStudio components included

**Comment by AllanOricil** [comment]
Check if this error relates to this

https://success.vlocity.com/s/article/Error-DML-currently-not-allowed-in-OmniScript-Designer

**Comment by AdeloyeB** [comment]
Hey @AllanOricil , I had a look at my issue seems to be unrelated.

Here is a snippet of the error we're getting:

`ContentVersion/7b616361-acbd-3678-9684-37c04953f6af - undefined
ContentVersion/f833a90d-5194-2da9-475c-f1b53570503b - undefined
DataRaptor/DocGenExtractDocumentTemplate - undefined
DataRaptor/DocGenExtractParticipantDetails - undefined
DataRaptor/DocGenTransformParticipantDetails - undefined
DocumentTemplates/Participant Registration Letter -- DataPack >> Participant Registration Letter -- Error Message -- No match found for DocumentTemplateContentDoc.LatestContentVersionId - ExternalDocumentInfo2=7b616361-acbd-3678-9684-37c04953f6af AND Title=Template Registration Letter 240523 (1).docx AND VersionNumber=1 (System Code)
`
