### ISSUE TITLE
How to export and deploy Integration Retry Policy?

### ISSUE THREAD

**Issue by sandyiit** [vlocityinc/vlocity_build#594]
Unable to find the relevant VlocityDataPackType for Integration Retry Policy

**Comment by 92SGupta** [comment]
@sandyiit : Just use the DataPackType as IntegrationRetryPolicy with VBT to export or deploy the same.

**Comment by sandyiit** [comment]
Thanks Shubham.
Kindly update the README as well on supported DataPackTypes

**Comment by 92SGupta** [comment]
Added the DataPackType in the README with PR #597
