### ISSUE TITLE
Local Compilation support for OmniScripts & Flexcard after Vlocity to OmniStudio Core Metadata Migration

### ISSUE THREAD

**Issue by gsaraswathcg** [vlocityinc/vlocity_build#595]
Hi Team, 

Today, we can use Vlocity build tool's Local Compilation feature to compile Omniscripts and Flexcards on our own computer locally and create, and deploy the corresponding LWC components to Salesforce.

As we migrate our OmniScripts and Flexcards from the Vlocity package namespace objects to OmniStudio Core Standard Objects and their related Metadata, I don't see any option available in Vlocity build tool which can use the generated metadata of OmniScript and Flexcard to compile and generate LWC Components locally. 

Is there a way in the Vlocity build tool to recompile all the LWC components after the migration, instead of manually activating each component individually?

Thanks.

**Comment by AllanOricil** [comment]
I believe you can overwrite the object names in the local compilers using the job file. Would you be able to give me the name of the new objects? I could open a PR to fix it if it is not supported already

**Comment by gsaraswathcg** [comment]
@AllanOricil I believe the platform has made some changes in how data used to get saved in legacy OmniScript or Vlocity UI card Objects vs how it is getting saved now in OmniProcess & OmniUiCard metadata. 

But yeah new object names are OmniProcess, and OmniUICard.

**Comment by AllanOricil** [comment]
I will take a look for free for Salesforce since I'm unemployed 😭
Maybe one day their engineers will notice me 🤓
If I find something I will share the changes to you @gsaraswathcg I just won't be able to open a PR because the local compilers are not open source.

**Comment by AllanOricil** [comment]
@gsaraswathcg It seems the compiler is suppose to work with OmniUICard already

![image](https://github.com/vlocityinc/vlocity_build/assets/55927613/7e25f636-486b-48a4-b432-207e5c8e1e68)

You can just extract all your datapacks after upgrading the objects and do a full deploy using vlocity build tool and the local compilers.

**Comment by 6andrey** [comment]
Growing tired with manual activations on OmniScripts and other Omnistudio components (*reactivations* actually, so amount of clicks doubled), I wonder if this makes sense to try:
- Source org has Omniscript and LWC compiled based on it, so I can can retrieve them both via MDAPI

For example, the 1st OmniScript that comes with developer org:

```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>reusableSampleEnglish</members>
		<name>LightningComponentBundle</name>
	</types>
	<types>
		<members>Reusable_Sample_English_1</members>
		<name>OmniScript</name>
	</types>
	<version>58.0</version>
</Package>
```

- LWC name can be derived from OmniScript name. What's interesting, LWC component name stays unchanged with next versions on the OmniScript
- In this case, only SFDX would be required to deploy both OmniScript and LWC components into a target org

Will provide update after some testing!
