### ISSUE TITLE
Setup on Windows 7 

### ISSUE THREAD

**Issue by IIvanov8888** [vlocityinc/vlocity_build#6]
Hi, 
I tried to setup the build on windows 7 , but unfortunately there are some steps missing I think,
I had to install windows-build-tools (python, add env variable), but still Im gettting errors trying to run Grunt tasks ... This is done on Node 4.3 

`$ grunt #>> Vlocity Build Tools
Loading "browserify.js" tasks...ERROR
>> Error: Cannot find module 'browser-pack'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'entities/maps/legacy.json'
Cannot find module 'handlebars'
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ivanoviv\vlocity_build\node_modules\grunt-istanbul\node_modules\istanbul\lib\report\html.js
:7:18)
>> Error: Cannot find module 'vow-fs'
Loading "sass.js" tasks...ERROR
>> Error: Cannot find module 'lodash.clonedeep'
Loading "zip.js" tasks...ERROR
>> Error: Cannot find module 'pako'
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './lib/jsforce'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
`

Are there are any setup instructions for Windows ? I tried to run the Ant task as well , but unsuccessfully, maybe an example how to run the ant jobs

**Comment by rutlabaga** [comment]
There was an update just now that I believe will address issues with windows. Please let me know if it does not fix your issues.

**Comment by IIvanov8888** [comment]
no issues now on Windows , thank you

**Comment by bpradeeptime** [comment]
Hi ,

I am facing below issue 
Error: Cannot find module 'D:\rabitInstaller\RBA\buildagent\projects\autorabit.com-W6d1rU_Pvc\node_modules\vlocity\lib\vlocitybuild.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
Preparing packExport command... for the OrgName : autorabit.com-W6d1rU Project Name : Pvc BuildNumber : 17
packExport command... vlocity.cmd packExport -propertyfile D:\rabitInstaller\RBA\buildagent\automation-scripts\autorabit.com-W6d1rU_Pvc\cijobsettings.properties -job D:\rabitInstaller\RBA\buildagent\projects\autorabit.com-W6d1rU_Pvc\dataPacksJobs\Example.yaml
module.js:549
throw err;
^
