### ISSUE TITLE
Recently been getting following error when deploying VlocityCard - Definition: data value too large

### ISSUE THREAD

**Issue by irfanlai** [vlocityinc/vlocity_build#602]
We are using Git based deployment and we are getting following error only in the production instance when VlocityCard is getting deployed. Same VlocityCard gets deployed to other lower env without any issues.

What could be the reason for this failure?

VlocityCard/SUS_AccountOverview -- DataPack >> SUS_AccountOverview -- **Error Message -- Definition: data value too large:** {<br> &quot;dataSource&quot;: {<br> &quot;contextVariables&quot;: [<br> {<br> &quot;id&quot;: 1,<br> &quot;name&quot;: &quot;recordId&quot;,<br> &quot;val&quot;: &quot;0012600001P9BLnAAN&quot;<br> }<br> ],<br> &quot;orderBy&quot;: {<br> &quot;isReverse&quot;: &quot;&quot;,<br> &quot;name&quot;: &quot;&quot;<br> },<br> &quot;type&quot;: &quot;IntegrationProcedures&quot;,<br> &quot;value&quot;: {<br> &quot;dsDelay&quot;: &quot;&quot;,<br> &quot;inputMap&quot;: {<br> &quot;ConsumerAccId&quot;: &quot;{recordId}&quot;<br> },<br> &quot;ipMethod&quot;: &quot;Overview_ViewServiceAccount&quot;,<br> &quot;resultVar&quot;: &quot;&quot;,<br> &quot;vlocityAsync&quot;: false<br> }<br> },<br> &quot;enableLwc&quot;: true,<br> &quot;isFlex&quot;: true,<br> &quot;lwc&quot;: {<br> &quot;DeveloperName&quot;: &quot;cfSUS_AccountOverview_20_OrgName&quot;,<br> &quot;Id&quot;: &quot;0Rb26000000XpEOCA0&quot;,<br> &quot;ManageableState&quot;: &quot;unmanaged&quot;,<br> &quot;MasterLabel&quot;: &quot;cfSUS_AccountOverview_20_OrgName&quot;,<br> &quot;NamespacePrefix&quot;: &quot;c&quot;<br> },<br> &quot;multilanguageSupport&quot;: true,<br> &quot;osSupport&quot;: true,<br> &quot;selectableMode&quot;: &quot;Multi&quot;,<br> &quot;states&quot;: [<br> {<br> &quot;actions&quot;: [<br> ],<br> &quot;childCards&quot;: [<br> ],<br> &quot;components&quot;: {<br> &quot;layer-0&quot;: {<br> &quot;children&quot;: [<br> {<br> &quot;children&quot;: [<br> {<br> &quot;class&quot;: &quot;slds-col &quot;,<br> &quot;element&quot;: &quot;outputField&quot;,<br> &quot;elementLabel&quot;: &quot;Block-1-Text-0&quot;,<br> &quot;key&quot;: &quot;element_element_block_0_0_outputField_0_0&quot;,<br> &quot;name&quot;: &quot;Text&quot;,<br> &quot;parentElementKey&quot;: &quot;element_block_0_0&quot;,<br> &quot;property&quot;: {<br> &quot;card&quot;: &quot;{card}&quot;,<br> &quot;data-conditions&quot;: {<br> &quot;group&quot;: [<br> {<br> ... (max length=1310...

**Comment by manas-sf** [comment]
This is limitation on LWC framework itself where LWC should not exceed certain size. Please re-visit your cards and OmniScripts to shorten them or use navigation links instead of all cards/OS in one parent item.
