### ISSUE TITLE
Is there a way to do destructiveChanges?

### ISSUE THREAD

**Issue by victorng8** [vlocityinc/vlocity_build#603]
In non-omnistudio components we can simply do 
`sfdx force:source:deploy --manifest manifest/package.xml --predestructivechanges manifest/destructiveChangesPre.xml --postdestructivechanges manifest/destructiveChangesPost.xml`

How can we achieve the same thing for vlocity omnistudio?

**Comment by victorng8** [comment]
Or is there a way to deploy de-activated omnistudio components of Flexcards/omniscript/dataraptor/integration procedures ?

**Comment by victorng8** [comment]
Have engaged SF Support. They said 

Happy Day!

I have verified further and got below response from Team:

Destructive Changes are Manual in OmniStudio.
To Deploy Inactive components we need to use queries section in the JobFile to retrieve the version other than the active one.
However it would still be deployed as Active only.
Sample Snippet :
=============
ProjectPath: ./Exportfile1
queries:

VlocityDataPackType: DataRaptor
query: Select Id from %vlocity_namespace%_DRBundlec where Name LIKE ‘%Team’ and %vlocity_namespace%IsActive_c = false LIMIT 1
Please refer below Trailhead to get more details on IDX and using Queries Section:

Trailhead Reference :
================
https://trailhead.salesforce.com/content/learn/modules/omnistudio-developer-tools/meet-idx-build-tool-

**Comment by AllanOricil** [comment]
Ask someone to purge ur instance

**Comment by AllanOricil** [comment]
you have no sense of humor @victorng8

**Comment by centricadean** [comment]
If you ever decide to migrate to standard objects, you can use SFDX instead of VBT.

**Comment by victorng8** [comment]
I heard some good news that SF trying to convert the Omnistudio **data to metadata** (https://help.salesforce.com/s/articleView?id=sf.os_enable_omnistudio_metadata_api_support.htm&type=5) so destructive changes can be supported in future! 

which then can be captured to the VCS
