### ISSUE TITLE
Problem with printing job status on Ubuntu 16.04

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#61]
When vlocity build is called from jenkins server (in our case Ubuntu 16.04) we are getting following error:
[exec]  [31m Uncaught Job Error >>[0m {
     [exec] }  [0m
     [exec] (node:2004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Object.values is not a function
     [exec]  [0m Vlocity Build v1.4.2 [0m
     [exec]  [36m Org >>[0m <.....user that does deployment ....>  [0m
     [exec]  [36m Running Pre Job Apex >>[0m ResetDataPackMappings.cls  [0m
     [exec]  [36m Loading Apex >>[0m /usr/lib/node_modules/vlocity/apex/ResetDataPackMappings.cls  [0m
     [exec]  [31m TypeError: Object.values is not a function
     [exec]     at DataPacksUtils.printJobStatus (/usr/lib/node_modules/vlocity/lib/datapacksutils.js:807:29)
     [exec]     at DataPacksJob.deployJob (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:1276:37)
     [exec]     at DataPacksJob.doRunJob (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:334:14)
     [exec]     at /usr/lib/node_modules/vlocity/lib/datapacksjob.js:271:22
     [exec]     at /usr/lib/node_modules/vlocity/lib/datapacksjob.js:269:16
     [exec]     at process._tickCallback (internal/process/next_tick.js:109:7) [0m

It works fine on Windows or Mac.

Any suggestions how to correct the problem?

**Comment by rutlabaga** [comment]
This error means you have an older version of Node installed. Please install Node v8+.
