### ISSUE TITLE
Components without "..._DataPack.json" file does not exist in the "currentJobInfo.json" 

### ISSUE THREAD

**Issue by Dm1tryKarpenko** [vlocityinc/vlocity_build#612]
When we deploy components that does not have "..._DataPack.json"(I don't know reason for it, but looks like it retrieved without it) we can't get correct information about status of deployment for this component becouse this component does not exist in "currentJobInfo.json" log file, I mean field "currentStatus"
![image](https://github.com/vlocityinc/vlocity_build/assets/57008480/0ca0ab8b-3a21-4be3-8532-080c9f2b3220)

I am Flosum developer and working on integration for retrieve/deploy vlocity components, and without it we unable show correct status of deployment

![image](https://github.com/vlocityinc/vlocity_build/assets/57008480/e4cf3205-a621-4627-949c-27b9aa3b3e51)

**Comment by AllanOricil** [comment]
Try to use the ID of that dapatack with its name. Datapacks are just records in salesforce. If you can't fetch the name from the `currentJob.json` using the ID, do it with some queries (rest api)
