### ISSUE TITLE
Export of VlocityPicklist Fails

### ISSUE THREAD

**Issue by maristei** [vlocityinc/vlocity_build#615]
Export of some Vlocity picklists fails due to characters in picklist value fields with errors:
>Invalid id: 10/100/1000Base-TX Class.vlocity_cmt.DRProcessObject.setAllRelevantIds: line 1808, column 1\nClass.vlocity_cmt.DRProcessObject.setAllRelevantIds: line 1813, column 1\nClass.vlocity_cmt.DRProcessObject.setAllRelevantIds: line 1813, column 1\nClass.vlocity_cmt.DRProcessObject.getAllRelevantIds: line 1829, column 1\nClass.vlocity_cmt.DREngine.getAllRelatedMatchingKeys: line 2273, column 1\nClass.vlocity_cmt.DREngine.getAsJSON: line 2361, column 1\nClass.vlocity_cmt.DREngine.exportAsJson: line 2380, column 1\nClass.vlocity_cmt.DREngine.runProcess: line 457, column 1\nClass.vlocity_cmt.DRProcessor.runDREngine: line 1141, column 1\nClass.vlocity_cmt.DRProcessor.beginProcessing: line 559, column 1\nClass.vlocity_cmt.DRProcessor.runExport: line 1047, column 1\nClass.vlocity_cmt.DRDataPackService.continueExportDataPack: line 3072, column 1\nClass.vlocity_cmt.DRDataPackService.runDataPackProcess: line 2374, column 1\nClass.vlocity_cmt.DRDataPackService.exportDataPack: line 3004, column 1\nClass.vlocity_cmt.DRDataPackRestResource.doPostDataPacks: line 154, column 1\nClass.vlocity_cmt.DRDataPackRestResource.doPost: line 29, column 1">

and 

>VlocityPicklist --- Test picklist --- Unknown Error - Use --verbose to see more information
>undefined - Unknown Error - Use --verbose to see more informatio

In this example export of picklist "Test picklist" fails if it has value record with the following values (see attached GIF for more details):
- Text Value: 10/100/1000Base-TX
- Label: 10/100/1000Base-TX
- Abbreviation: 10/100/1000Base-TX

Export is successful after 2nd symbol "/" is removed from picklist value fields.

![Test_Picklist](https://github.com/vlocityinc/vlocity_build/assets/17293543/29e84c9c-a71b-4c65-9fc0-1710c6901780)
[logs_and_job_file.zip](https://github.com/vlocityinc/vlocity_build/files/12682945/logs_and_job_file.zip)

**Comment by AllanOricil** [comment]
@maristei how are you exporting this DR?

**Comment by maristei** [comment]
@AllanOricil 
I'm exporting by running "packExport":
vlocity -propertyfile properties\Picklist_source.properties -job dataPacksJobs\PicklistSingleJob.yaml packExport --verbose true

PicklistSingleJob.yaml is in attached ZIP file.
