### ISSUE TITLE
Apex heap size too large: 12426421

### ISSUE THREAD

**Issue by tggagne** [vlocityinc/vlocity_build#618]
Trying to deploy a product.

```
tgagne@HWKMAC-C02DN69QMD6M dx-mga % cat VlocityBuildErrors.log 
Org: devmerge
Version: 1.17.4
PackageVersion: 890.379
Namespace: vlocity_ins
Job: /tmp/job.36126/job.yaml
Action: Deploy
ProjectPath: ./force-app/main/default/
Errors:
Product2/452687e7-d3d7-06b2-822c-297880f6bd5d -- DataPack >> <hidden> -- Error Message -- Apex heap size too large: 1242642
```

Also, using the same script deploying to the same target I sometimes get an Apex CPU time limit exceeded.

What is the best way to get a peek behind the curtain to see where the error is coming from so we might figure out how to work around it?

**Comment by manas-sf** [comment]
This is sometimes dependent on complexity of datapacks involved and also the nested depedencies.

**Comment by tggagne** [comment]
@manas-sf , I don't think this should be closed until there's a way to deploy complex datapacks or a way to find and remove overrides or perhaps an OOTB way to delete products so they may be redeployed again over a clean slate.
