### ISSUE TITLE
packGetDiffsAndDeploy

### ISSUE THREAD

**Issue by bertjanssens93** [vlocityinc/vlocity_build#62]
Hi,

First of all thanks for the tool! It makes life easier.
But currently I am not able to properly use the packGetDiffsAndDeploy command. It is not only deploying the objects that I have defined in the Job File, but all components in my repository.
For example: I defined to deploy OmniScripts and it deployed everything in my repository.

Kind Regards,
Bert

**Comment by rutlabaga** [comment]
In the v1.5.3 you can now use the following syntax to accomplish what you are trying to do. 
`vlocity packGetDiffsAndDeploy -manifest '["OmniScript"]'`

The queries node does not actually control deploy, but this will use default queries to get active omniscripts and diff them against the ones in local folders, then only deploy the OmnIScripts.

**Comment by bertjanssens93** [comment]
Ok, Thanks for the quick answer.

What objects are possible to deploy with packGetDiffsAndDeploy? Only the ones that are available for Manifest?

**Comment by rutlabaga** [comment]
You can use the JSON-like Manifest for any type as part of the CLI API:
https://github.com/vlocityinc/vlocity_build#cli-api

You can run the following command to see all the available VlocityDataPackKeys in your Org:
`vlocity -propertyfile build_test.properties --nojob packGetAllAvailableExports`

And you can add: `--json-pretty` to get some more details for each one.

Then use those in the command line like in the documentation, or use a List of those in the yaml file like:
manifest:
- OmniScript/MACD_Move_English
- OmniScript/MACD_Add_English

But this will make it so it always only deploys those 2 folders. Manifest works slightly different for deploy as it does for export. For Export it will export the item and its dependencies. For Deploy it will deploy *only* those items. For export you could force this same behavior with `-maxDepth 0`.
