### ISSUE TITLE
Error Message - setting mismatch between source and target orgs

### ISSUE THREAD

**Issue by petroutassos** [vlocityinc/vlocity_build#622]
Hello,
Even though I have performed `packUpdateSettings` on both orgs I am still getting the following message.

`Error Message -- DataPack contains data that was not deployed due to setting mismatch between source and target orgs. Please run packUpdateSettings in both orgs to ensure the settings are the same.`

Any ideas? Is there a way to troubleshoot this in more detail?

**Comment by manas-sf** [comment]
Hi @petroutassos , packUpdateSettings is one work-around to fix this issue. Another attempt would be to go through datapacks manually to make sure we don't have any deprecated or missing elements.
Also I am assuming that you are not deploying standard data model datapacks to old custom data model org.

If still you need any help, please raise salesforce support ticket.
