### ISSUE TITLE
Omniscripts does not get deployed properly

### ISSUE THREAD

**Issue by cossss** [vlocityinc/vlocity_build#631]
We have some issues with deploying Omniscripts since we upgraded to the latest vlocity_ins package. 

The issue is that certain Omniscripts (not always the same), the LWC are not generated properly. So for example if we deploy 22 Omniscripts, only 15 of them have a new LWC generated.

No errors, etc. Just the LWC generation is missing. We can manually deactivate and activate the Omniscripts and then it works fine.

We also logged a case: 45859895

Versions:
vlocity_ins: 'Winter 24 9 November package
VBT: 1.17.5

**Comment by manas-sf** [comment]
Hi @cossss There is already a logged bug where OmniScript activation doesn't work if we activate while import. Your use-case seems to be a bit different where only few OmniScripts don't work. This may also depend on OmniScripts complexity as well. 
For more details and RCA, please log Salesforce Support case.

**Comment by cossss** [comment]
Just for future reference: we got a response from Salesforce support:

_"Thanks for bringing up this issue to our notice. As discussed over the call, this issue is identified as a bug and it will be fixed in the future release.

As a workaround you can deploy the components in minimal count and activate the omniscripts manually."_
