### ISSUE TITLE
Permission denied during installation

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#65]
Hi Adam,
We are currently facing an issue with vlocity_build installation. We are getting an error "/Users/stepanruzicka/.npm/_cacache/tmp/git-clone-a7c28034/.git: Permission denied". Do you know what's happening?
Thanks,
Stepan
<img width="1333" alt="screen shot 2018-06-05 at 15 51 39" src="https://user-images.githubusercontent.com/33927875/40983949-a76e6c7a-68d8-11e8-9acf-5fc21b6b7b42.png">

**Comment by rutlabaga** [comment]
Generally this means that npm was installed with `sudo`. Usually you can run the vlocity build install command with sudo as well to force the install. Or fix the permissions for the folder with `chmod`

**Comment by Stepan007** [comment]
Hi,

Yes, it was installed with sudo, so I would expect it working without any
permission issue.

It is a temporary folder created by the installation procedure so the only
folder we can change the peemission to is the temp. But it doesn't help.

It's not working either with sudo and without sudo. Any ideas?

Thanks,

Stepan

**Comment by Stepan007** [comment]
Hi Adam,
This was sorted. You were right. Node had to be reinstalled without sudo.
Thanks,
Stepan
