### ISSUE TITLE
Activation Error

### ISSUE THREAD

**Issue by Stepan007** [vlocityinc/vlocity_build#68]
We are getting the following error during deployment:
Activation Error >> OmniScript/Contract_Create_English Update failed. First exception on row 0 with id a1z0E000000Q53oQAC; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, For the same Type, Sub Type and Language Code, there can only be one active OmniScript record.: []

Do you know what could be the issue?

**Comment by rutlabaga** [comment]
Can you check the DataPack.json file for that OmnIScript and make sure there is only 1 entry and that in your target org there is only 1 that is currently Active. And also make sure there is no OmniScript in your project with just the no Type = Contract, SubType = Create and no Language.

**Comment by rutlabaga** [comment]
Please update if still occurring.
