### ISSUE TITLE
Custom Settings - update into existing.

### ISSUE THREAD

**Issue by jimjamming** [vlocityinc/vlocity_build#70]
Using VBT to load/ synchronise the custom settings
YAML
  - VlocityDataPackType: SObject
    query: Select Id from vlocity_cmt__GeneralSettings__c

ERROR:
SObject_GeneralSettings/CardActivationJob -- Datapack >> CardActivationJob -- Error Message -- There is already an item in this list with the name CardActivationJob: Name
Account>Quote -- Datapack >> Account>Quote -- Error Message -- There is already an item in this list with the name Account>Quote: Name

Tested against
- SObject_PDFDocumentTemplate
- SObject_GeneralSettings
- SObject_CustomObjectMap/

Other custom settings worked, such as
- CQPConfigurationSetup
- ContractManagementConfigurationSetup

**Comment by rutlabaga** [comment]
There are some instructions on migrating custom settings in the documentation:

https://github.com/vlocityinc/vlocity_build#advanced-export-individual-sobject-records
