### ISSUE TITLE
Not throwing error on Build Fail

### ISSUE THREAD

**Issue by bertjanssens93** [vlocityinc/vlocity_build#71]
Hi,

I am using Jenkins Pipeline running a script that uses this Vlocity Build Tool to deploy components to the next environment. When deployment of one or more components fails, it doesn't throw an error. Without throwing an error, it looks in Jenkins like the build succeeded even though there could be errors. 

Kind Regards,
Bert

**Comment by muminekimalami** [comment]
The same for me (but not in all builds). Bottom of the log:
    [exec] OmniScript/Payment Information - Add_English -- Datapack >> PaymentInformation--1 -- Error Message -- Some records were not processed. Please validate imported data types.
     [exec]  [31m Error >>[0m 134  [0m
     [exec] Result: 1

**Comment by rutlabaga** [comment]
This should be fixed in v1.6.0. The exit code of the Process should only be 0 now if it gets to the Success callback as opposed to be set to 1 in the Error callback. Please let me know if there are any issues.
