### ISSUE TITLE
Continuous Integration - product hierarchy flat after deployment

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#72]
We have continuous integration procedure (build after merge to development branch - according to canonical git flow). After each build product hierarchy is somehow lost. It can be verified in Order - CPQ module (CPQ button clicked from Order) - when you add product to cart only top-level product is added (see attachment).

![image](https://user-images.githubusercontent.com/36472902/41858710-cdf68f18-789a-11e8-9196-5dd9f874a0e9.png)

We have to manually run maitenance jobs after each build: 
PRODUCT HIERARCHY MAINTENANCE 
REFRESH PRICEBOOK 
CLEAR MANAGED PLATFORM CACHE 
It makes automation impossible to achieve.

Question: what post installation job/code should we execute in order to avoid any amual activities?

**Comment by rutlabaga** [comment]
Can you please email me at arutland@vlocity.com and we can discuss further there. Thanks

**Comment by jvandrewala** [comment]
Thanks for raising query @muminekimalami!
Do we have any updates on this, please?

Tx- Jamshid

**Comment by rutlabaga** [comment]
These can be run with Anonymous Apex code post deployment.
