### ISSUE TITLE
Cannot sync Omniscript Custom HTML

### ISSUE THREAD

**Issue by Dberto83** [vlocityinc/vlocity_build#74]
Hi,

I'm facing this behaviour when trying to sync the Custom HTML of an Omniscript:

- When i perform a packExport the custom HTML is downloaded correctly but if I try to repeat the operation the changes are not downloaded unless I delete the local copy of the custom HTML

- The pack Deploy does not work on the custom HTML

Thanks
Daniele

**Comment by rutlabaga** [comment]
Can you please upload the DataPack Folder?
