### ISSUE TITLE
Having issues setting up Vlocity_build

### ISSUE THREAD

**Issue by LamereMichael** [vlocityinc/vlocity_build#77]
After I clone the repo, I run npm install and I keep getting the following warnings. 
-------------------------------------------------------------------------------------------
npm install
audited 1353 packages in 2.848s
found 9 vulnerabilities (5 low, 3 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
-------------------------------------------------------------------------------------------

I do try a npm Link and running the vlocity help command with no luck. 

michael_l@MIKE-LAMERE MINGW64 /c/smile/vlocity_build (master)
$ npm link
audited 1353 packages in 2.786s
found 9 vulnerabilities (5 low, 3 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
C:\Users\Michael_L\AppData\Roaming\npm\vlocity -> C:\Users\Michael_L\AppData\Roaming\npm\node_modules\vlocity\lib\vlocitybuild.js
C:\Users\Michael_L\AppData\Roaming\npm\node_modules\vlocity -> C:\smile\vlocity_build

michael_l@MIKE-LAMERE MINGW64 /c/smile/vlocity_build (master)
$ vlocity help
bash: vlocity: command not found

**Comment by rutlabaga** [comment]
It is much easier to use the installation instructions than to clone the actual repo. 

`npm install --global https://github.com/vlocityinc/vlocity_build`

Then you can also update any time by rerunning that same command.
