### ISSUE TITLE
./apex/AllGlobalKeysBatch.cls is missing 3 GlobalKey references

### ISSUE THREAD

**Issue by DripLeBuk** [vlocityinc/vlocity_build#79]
The Apex Class AllGlobalKeysBatch is missing the following three entries, so their Global Keys are never checked/fixed by CheckOrgData but fail DataPackExport:
    vlocityNamespace + 'Attribute__c',
    vlocityNamespace + 'AttributeCategory__c',
    vlocityNamespace + 'DRBundle__c',

**Comment by rutlabaga** [comment]
Fixed in v1.9
