### ISSUE TITLE
./javascript/cleanData.js is missing 3 GlobalKey references and Product2 queries assume all are Vlocity’s

### ISSUE THREAD

**Issue by DripLeBuk** [vlocityinc/vlocity_build#80]
The JavaScript cleanData is missing the following three entries, so their Global Keys are never checked/fixed by CheckOrgData but fail DataPackExport.

Within the AddGlobalKey section:
                'SELECT Id FROM vlocity_namespace__Attribute__c WHERE vlocity_namespace__GlobalKey__c = null',
                'SELECT Id FROM vlocity_namespace__AttributeCategory__c WHERE vlocity_namespace__GlobalKey__c = null',
                'SELECT Id FROM vlocity_namespace__DRBundle__c WHERE vlocity_namespace__GlobalKey__c = null',

And the entry for Product2 needs to include and additional condition to support sites where Vlocity are not the only supplier of Products (Vlocity was predated by other CPQ solutions)  
                'SELECT Id FROM Product2 WHERE RecordType.DeveloperName=\'Product\' AND vlocity_namespace__GlobalKey__c = null',

And more from within the CheckDuplicates section:
                'SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM vlocity_namespace__Attribute__c GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1', 
                'SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM vlocity_namespace__AttributeCategory__c GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1',
                'SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM vlocity_namespace__DRBundle__c GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1',

And again the entry for Products…
                'SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM Product2 WHERE RecordType.DeveloperName=\'Product\' GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1',

**Comment by DripLeBuk** [comment]
On further reflection I now doubt the exclusion of non-Vlocity era products at the cleanOrgData stage is such a good idea unless just such a restriction/focus is applied at the export stage too.   If exporting all of Products2 for deployment then all products should have been checked first.  

Still think the missing three objects should be included though.

**Comment by rutlabaga** [comment]
The Objects listed do not have a functional requirement for GlobalKeys as they all have other Unique Keys that are enforced unique in Salesforce or through Vlocity UI / Triggers. Will look into adding in future if there becomes a functional need for filling in Global Key Data.

**Comment by DripLeBuk** [comment]
Does this mean any duplication of, or missing values for Global Keys, does not affect the packExport/packDeploy process for the Attribute, Attribute Category, and DR Bundle objects?

**Comment by DripLeBuk** [comment]
Just in case you don’t spot the added comment after the ticket was closed…

Does this mean any duplication of, or missing values for Global Keys, does not affect the packExport/packDeploy process for the Attribute, Attribute Category, and DR Bundle objects?


Regards,

__________________________________________________________
David Kubel
Business Analyst | Salesforce | Application Services UK
Planned Absences: August 14th, August 27th to September 11th, and September 19th.

Capgemini UK | North West England
Mob.: +44 (0) 7717 726438
www.capgemini.com<http://www.capgemini.com/>

[https://visualidentity.capgemini.com/capgemini.png]
____________________________________________________________________
Connect with Capgemini:
[cid:image009.png@01D42AFD.422301F0]<https://www.capgemini.com/insights-and-resources/blogs> [cid:image010.png@01D42AFD.422301F0] <https://www.twitter.com/capgemini>  [cid:image011.png@01D42AFD.422301F0] <https://www.facebook.com/capgemini>  [cid:image012.png@01D42AFD.422301F0] <https://www.linkedin.com/company/capgemini>  [cid:image013.png@01D42AFD.422301F0] <https://www.youtube.com/capgeminimedia>  [cid:image014.png@01D42AFD.422301F0] <https://www.slideshare.net/capgemini>  [cid:image015.png@01D42AFD.422301F0] <https://plus.google.com/+CapgeminiGlobal>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.

**Comment by rutlabaga** [comment]
Correct. You can see all the default cardinality Fields for each Object in the table here:
https://github.com/vlocityinc/vlocity_build#current-matching-keys

Unless the GlobalKey is the MatchingKey field here, then duplicate keys will not explicitly affect the import / export. However these may be changed in the future (but not for the 3 objects listed).
