### ISSUE TITLE
Export Product Catalog with Vlocity Build - attachments URLs are not exported

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#81]
Issue similar to:
https://github.com/vlocityinc/vlocity_build/issues/47

I cannot export images for products with Vlocity Build.

I'm using predefined EPC.yaml job in order to export Product Catalog + query to add Vlocity Attachments:

VlocityDataPackType: VlocityAttachment
query: Select Id from %vlocity_namespace%__VlocityAttachment__c where %vlocity_namespace%__ContentType__c = 'Image'

Attachments are exported but with empty URL:
"%vlocity_namespace%__Url__c": ""
and without URL Long field.

We are using v.1.5.5 but problem existed before we installed it - it just stopped work in some moment of time.

**Comment by rutlabaga** [comment]
This should be fixed in v1.6.0. Please test and reopen if there are any issues.
