### ISSUE TITLE
Product Catalogue: attempt to de-reference a null object

### ISSUE THREAD

**Issue by strzalj** [vlocityinc/vlocity_build#82]
Versions 1.5.6 and 1.5.7 cannot export/deploy product catalogue properly. 
Product console gives an error 'attempt to de-reference a null object' and maintenence job gives an error First error: Insert failed. First exception on row 647; first error: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: a0L0Q000000Ccnf: [] 
As far as we could see it might be related to attributes/attachments export.

**Comment by rutlabaga** [comment]
Please file a Vlocity Support Case for this issue.

https://vlocitysupport.force.com/SupportCenter/apex/SupportCenterHome

support@vlocity.com

Thanks
