### ISSUE TITLE
Document Templates are not activated after deployment

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#83]
despite using:
  activate: true
setting in yaml file.

**Comment by rutlabaga** [comment]
Document Template Activation is not currently supported. I will create an internal tickets to add support for this.

**Comment by ABhalla2** [comment]
what's the status of this? is Document Template Activation supported now?

is there any other way to mass-activate Document Templates that are deployed?

Can DataPacks be used for this?
