### ISSUE TITLE
Way to get apex pre and post job code from PROJECT folder

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#84]
From documentation about Anonymous Apex:
Apex files live in vlocity_build/apex

But I have this file commited in my project under source control and I cannot copy it manually to vlocity_build folder on each computer each time it is updated.

Is there ANY way to call this code from local folder and not from vlocity_build folder?

**Comment by rutlabaga** [comment]
You can reference Apex Classes relative to the `projectPath`. I will fix documentation to be more clear.
