### ISSUE TITLE
Pricing Adjustment - relationship to Context Rule not deployable

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#88]
In fact I think it is non-retrievable.

Data marked with yellow marker on below screen is not retrieved so we cannot deploy it and we have to move it manually between environments.

![image](https://user-images.githubusercontent.com/36472902/44339459-bf2e0200-a481-11e8-82e2-23cbed6f4816.png)

We are using Vlocity Build v.1.5.5 and standard EPC.yaml job file.

**Comment by rutlabaga** [comment]
Hi,

Can you please file a Vlocity Support case and put the case # here?

https://vlocitysupport.force.com/SupportCenter/login
