### ISSUE TITLE
Cannot find module '\node_modules\vlocity\lib\vlocitybuild.js'

### ISSUE THREAD

**Issue by bpradeeptime** [vlocityinc/vlocity_build#89]
Hi ,

I am facing below issue
Error: Cannot find module '\node_modules\vlocity\lib\vlocitybuild.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3

throw err;
^

**Comment by rutlabaga** [comment]
What command are you running to install?
What command are you running to get this error?

**Comment by bpradeeptime** [comment]
vlocity packExport command

**Comment by rutlabaga** [comment]
What command did you run to install?

**Comment by rutlabaga** [comment]
Please email support@vlocity.com if continuing to experience issues.
