### ISSUE TITLE
packBuildFile and packExpandFile missing from build.xml?

### ISSUE THREAD

**Issue by LucaNardini** [vlocityinc/vlocity_build#9]
packBuildFile: Build a DataPacks Directory into a DataPack file of
packExpandFile: Create a DataPack Directory from a previosuly exported file

Those jobs are missing from the build.xml file?

**Comment by rutlabaga** [comment]
This has been reworked a bit and the idea of using ant in this project is less documented. Grunt is the preferred method of deploy.
