### ISSUE TITLE
Destructive changes using vlocity_build tools

### ISSUE THREAD

**Issue by ivanovivelin** [vlocityinc/vlocity_build#91]
Hi,

Is it possible to do destructive changes with the tool ?

**Comment by rutlabaga** [comment]
This is not currently supported.

**Comment by SamuelMoy** [comment]
Is it on the roadmap somewhere?

**Comment by rpawar655** [comment]
Is it possible to delete some components from org?

**Comment by antonycroazzoacce** [comment]
is it possible deploy/retrive whith ant migration tool ?

**Comment by rpawar655** [comment]
@antonycroazzoacce no not posible
