### ISSUE TITLE
Duplicated records

### ISSUE THREAD

**Issue by AndreasRikstad** [vlocityinc/vlocity_build#93]
Hi.
In source org I have product with names: Product A, Product B, Product C, Product D.
In tagret org I have products with names: Product A, Product D.
After deploy to target org I have:
Product A, Product A, Product B, Product C, Product D, Product D.

Is possible to avoid this?

**Comment by jamonntoast** [comment]
In your target org - you should of done a comparison of the products and then updated the target.GlobalKey = source.GlobalKey.
