### ISSUE TITLE
(node:12865) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by jamonntoast** [vlocityinc/vlocity_build#94]
Using 1.63 got this error when running the 
vlocity -x y z cleanOrgData
yaml file is exporting everything.

Works on another PC. May be PC specific?

`CheckDuplicates >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__UISection__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  CheckDuplicates >> SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM vlocity_namespace__VlocityFunctionArgument__c GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1
  Running Query >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__VlocityFunctionArgument__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  Records >> 0
  CheckDuplicates >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__VlocityFunctionArgument__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  CheckDuplicates >> SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM vlocity_namespace__VlocityFunction__c GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1
  Running Query >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__VlocityFunction__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  Records >> 0
  CheckDuplicates >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__VlocityFunction__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  CheckDuplicates >> SELECT Name, count(Id) FROM vlocity_namespace__InterfaceImplementation__c GROUP BY Name HAVING count(Id) > 1
  Running Query >> SELECT Name, count(Id) FROM vlocity_cmt__InterfaceImplementation__c GROUP BY Name HAVING count(Id) > 1
  Records >> 0
  CheckDuplicates >> SELECT Name, count(Id) FROM vlocity_cmt__InterfaceImplementation__c GROUP BY Name HAVING count(Id) > 1
  CheckDuplicates >> SELECT vlocity_namespace__GlobalKey__c, count(Id) FROM vlocity_namespace__Catalog__c GROUP BY vlocity_namespace__GlobalKey__c HAVING count(Id) > 1
  Running Query >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__Catalog__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  Records >> 0
  CheckDuplicates >> SELECT vlocity_cmt__GlobalKey__c, count(Id) FROM vlocity_cmt__Catalog__c GROUP BY vlocity_cmt__GlobalKey__c HAVING count(Id) > 1
  CheckDuplicates >> SELECT vlocity_namespace__CatalogId__c, vlocity_namespace__Product2Id__c, count(Id) FROM vlocity_namespace__CatalogProductRelationship__c GROUP BY vlocity_namespace__CatalogId__c, vlocity_namespace__Product2Id__c HAVING count(Id) > 1
  Running Query >> SELECT vlocity_cmt__CatalogId__c, vlocity_cmt__Product2Id__c, count(Id) FROM vlocity_cmt__CatalogProductRelationship__c GROUP BY vlocity_cmt__CatalogId__c, vlocity_cmt__Product2Id__c HAVING count(Id) > 1
  Records >> 0
  CheckDuplicates >> SELECT vlocity_cmt__CatalogId__c, vlocity_cmt__Product2Id__c, count(Id) FROM vlocity_cmt__CatalogProductRelationship__c GROUP BY vlocity_cmt__CatalogId__c, vlocity_cmt__Product2Id__c HAVING count(Id) > 1
  Uncaught Job Error >> {
}
(node:12865) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Object.values is not a function`

**Comment by IIvanov8888** [comment]
Make sure you are running on Node.js 8.0.0 or bigger
