### ISSUE TITLE
Vlocity Dataraptor Deployment Issue

### ISSUE THREAD

**Issue by KaustuvDas** [vlocityinc/vlocity_build#95]
Data raptor is working as expected in higher environments if it is deployed manually, but it is not working properly when we deploy it through Vlocity build tool.

Issue:
Contact(lookup field) in existing driver(Quote line Item) is getting overridden, when we try to add another driver using below omni script and data raptor.

DataRaptor/MotorQouteVersioning

Note: This Issue is specific when we deploy the data raptor using Vlocity build, things are working as expected in development org, Vlocity support Case Number:00131537 
[VlocityBuildIssue.docx](https://github.com/vlocityinc/vlocity_build/files/2454851/VlocityBuildIssue.docx)

**Comment by KaustuvDas** [comment]
Any suggestions here please?

**Comment by KaustuvDas** [comment]
I am using Vlocity Build v1.6.2 and Node js v8.11.4. Any help on this will be appreciated.

**Comment by rutlabaga** [comment]
Hi, can you provide the DataPack that is not working?

**Comment by KaustuvDas** [comment]
Hello,
Sorry for late reply.
Project.yaml Excerpts:
![image](https://user-images.githubusercontent.com/42804518/47282396-ac0fed80-d5fc-11e8-909a-d04bdcf6a386.png)

Strangely every other DataRaptor works fine except this one.

More Overview:
When I manually export this Dataraptor from source Org, the file size is bigger as compared to the one which I am extracting using vlocity build.

Please let me know if anything else is required.

Regards,
Kaus

**Comment by rutlabaga** [comment]
Can you provide the actual DataPack file? Preferably the UI exported JSON that is working.

**Comment by KaustuvDas** [comment]
Hi,
I am attaching 3 files.
1. Vlocity build tool extract snapshot(No errors found while extracting using packExport command)
2. MotorQouteVersioning.json -Extracted using VlocityBuildTool
3. Vlocity DataRaptor Bundles Multipack json file - Manual Import from Org

Please have a look and ask if anythingelse required.

Regards,
Kaus
![vlocity build tool extract snapshot](https://user-images.githubusercontent.com/42804518/47368117-aac6e980-d6fe-11e8-8c63-2b589cd76c2a.PNG)
[MotorQouteVersioning-VlocityBuildTool.zip](https://github.com/vlocityinc/vlocity_build/files/2506546/MotorQouteVersioning-VlocityBuildTool.zip)
[Vlocity DataRaptor Bundles Multipack - Manual Import from Org.zip](https://github.com/vlocityinc/vlocity_build/files/2506547/Vlocity.DataRaptor.Bundles.Multipack.-.Manual.Import.from.Org.zip)

**Comment by KaustuvDas** [comment]
Please Any help here?

**Comment by rutlabaga** [comment]
I am unable to see anything that should cause an issue like this. Can you please follow up on your Vlocity Support case and have them escalate it.
